### ISSUE TITLE
Delete vs put in trash

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#104]
I wonder if we should offer `drive_trash()` instead of `drive_delete()`.

And then have a function to empty the trash.

And `drive_untrash()` to pull something back out of the trash.

The browser UI makes it much harder to truly delete things than we currently do. I don't want to make it easy for people to shoot themselves in the foot.

**Comment by LucyMcGowan** [comment]
Do you think we should have both and just put a big warning with `drive_delete()` that it will be gone forever?

**Comment by jennybc** [comment]
I think you should go ahead and add `drive_trash()`, `drive_untrash()`, and `drive_empty_trash()`.

We can ask Hadley for an opinion about `drive_delete()` when he reviews.
