### ISSUE TITLE
Use service token for auth

### ISSUE THREAD

**Issue by Serenthia** [tidyverse/googledrive#115]
I have a Google service account for which I can generate a token using [googleAuthR](https://github.com/MarkEdmondson1234/googleAuthR)`::gar_auth_service`.

This method doesn't create an .httr-oauth file, however.

I believe that I can use the token for auth in `googledrive::drive_auth`, however this function requires a secret - something no longer provided with service accounts.

Do you know of a way that I can authenticate `googledrive` without use of a browser, please?

**Comment by jennybc** [comment]
At the moment, you can't do this with googledrive but that is coming very soon! We know about the need to use a service account token and will support it. If you're willing to use our low-level functions, you can probably already provide it via `token` but we will make this smoother.

**Comment by jennybc** [comment]
Will be handled bia #102
