### ISSUE TITLE
README.Rmd

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#12]
Also not urgent, but good to initiate once the UI starts to settle down. Below is boilerplate content, so use your judgment.

### `README.Rmd`

  * [x] Switch from `.md` to `.Rmd`

  * [x] Install instructions:

````r
```{r, eval = FALSE}
# The easiest way to get readr is to install the whole tidyverse:
install.packages("tidyverse")

# Alternatively, install just readr:
 install.packages("readr")

# Or the the development version from GitHub:
# install.packages("devtools")
devtools::install_github("tidyverse/readr")
```
````

  * [ ] Overview: 1-2 paragraphs including brief description/goals. Add h2, and set:

   ```yaml
   home:
     strip_header: true
   ```

  * [ ]  Link to appropriate R4DS chapter:

   ```md
   If you are new to readr, the best place to start is the
   [data import chapter](http://r4ds.had.co.nz/data-import.html) in R
   for data science.
   ```

  * [ ] Add link to `_pkgdown.yaml`

   ```yaml
     links:
     - text: Learn more
       href: http://r4ds.had.co.nz/data-import.html
   ```

  * [x]  Usage section shows a few examples.

#

**Comment by LucyMcGowan** [comment]
@jennybc does this go in the `_pkgdown.yaml`? I am not sure where to stick it for the README.
```
home:
  strip_header: true
```

**Comment by jennybc** [comment]
I'm not even sure of the context, yet I note that I have this in the [readxl `_pkgdown.yaml`](https://github.com/tidyverse/readxl/blob/cb2b98144f2e7bb7374a08435c1286c46baeeefd/_pkgdown.yml).

What's the connection / need re: the README?

**Comment by LucyMcGowan** [comment]
I'm not sure, it's from the third checklist item above:
> Overview: 1-2 paragraphs including brief description/goals. Add h2, and set:
```
home:
  strip_header: true
```

**Comment by jennybc** [comment]
It must be something in the pkgdown setup that is relevant to pkgdown's treatment of README, which is basically the basis for index.html by default. So I think you can disregard until you're using  pkgdown.

**Comment by jennybc** [comment]
In #34 I also added an explicit token load to the setup chunk for `README.Rmd`. This way we are both using the dev account. By way of explanation, you need to capture a token for that account that is *noncaching*, i.e. it doesn't write itself to `.httr-oauth` every time it refreshed. You will need to this:

```
token <- drive_auth(new_user = TRUE, cache = FALSE)
# do the browser dance
saveRDS(token, "tidyverse-noncaching-token.rds")
```

I am now using such a token for README and tests (so I've copied this token file into tests as well).

**Comment by jennybc** [comment]
I think our README is fine and, if anything, will get leaner as we add to the website.
