### ISSUE TITLE
How do you examine current sharing status?

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#129]
@LucyMcGowan How do you examine current sharing status? Seems like we don't have a nice workflow for that.

**Comment by jennybc** [comment]
Some information can be found in `files_resource`, but I'm thinking we need a better way to inspect current permissions in general (sharing and publishing).

**Comment by dsdaveh** [comment]
I had the same question and ended up writing a hack (see get_drive_perms below) that did the job, but doesn't feel very elegant.

I was modeling it after gs_perm_ls and was expecting to find a drive_perm_ls.  Another alternative might be to just to return the perms if drive_share has no role/type (now it throws an error).  Is this a candidate for a PR? 

Example (requires authentication for both googlesheets and googledrive):
some_email <- 'xxxx@gmail.com'
get_drive_perms <- function(file) {
    perm_list <- file$drive_resource[[1]]$permissions
    perms <- tibble(seq = 1:length(perm_list))
    perms$emailAddress <- purrr::map_chr(file$drive_resource[[1]]$permissions, 'emailAddress')
    perms$displayName <- purrr::map_chr(file$drive_resource[[1]]$permissions, 'displayName')
    perms$type <- purrr::map_chr(file$drive_resource[[1]]$permissions, 'type')
    perms$role <- purrr::map_chr(file$drive_resource[[1]]$permissions, 'role')
    perms$perm_id <- purrr::map_chr(file$drive_resource[[1]]$permissions, 'id')
    return(perms)
}
new_sheet <- gs_new("random_sheet")
handle <- drive_get(as_id(new_sheet$sheet_key))
get_drive_perms(handle)
drive_share(handle, emailAddress = some_email, role='reader', type = 'user')
handle <- drive_get(as_id(new_sheet$sheet_key))
get_drive_perms(handle)
gs_delete(new_sheet)

**Comment by LucyMcGowan** [comment]
This is quite timely - I am actually currently working on a PR that will be a heftly overhaul of `drive_publish()` and `drive_share()` (along with some helper functions around them). The current solution I've been working through adds the permission information to your `dribble` rather than outputting a full `tibble` of permissions - do you think that would suit your needs, our would the full `tibble` be preferable? For example, after running this function (currently named `drive_show_sharing()`) you'd see 
name owner reader id drice_resource

**Comment by jennybc** [comment]
As a general principle, it's better to have predictable output structure. So to riff on the `drive_show_sharing()` example, the new columns that are introduced would not depend on the data, they would be known in advance. The downside is, of course, lots of columns and the possibility of columns full of `NA`. But usually predictability wins in the end. I realize this may, in fact, already be the plan.

If you want to allow for the columns to vary, then perhaps the user can submit some subset of `"owner"`, `"reader"`, `"commenter"`, etc. with a reasonable default (all of them?). But then you come back around to that fact that this post hoc grooming is easy to achieve with `dplyr::select()` and "combining simple things" has proven to be a powerful overall philosophy for the tidyverse.

I guess the main message is we want to nicely package the quick thing most people want for inspection. And then make it easy for them to use general tidyverse strategies for more ambitious work.

**Comment by LucyMcGowan** [comment]
Ah yes you've read my mind! The current state of it is the user provides the columns (current it defaults to only `owner`, but I could change this to all of them). The main piece I am still struggling with is whether this is sufficient information (it only tells you the email address of the user with the give privilege, or if it is `anyone`).

**Comment by jennybc** [comment]
High-level advice: err on the side of building into googledrive the bare minimum of functionality. Then write an article on workflows for getting sharing/publishing info into other readable and useful forms. 
We can take some time to consider if any of that should be pushed down into an official function. It's very had to remove functionality and easy to add it.

I don't think we want to get into the business of pulling out `n` individual columns. It's so easy to demonstrate and ... why aren't we doing it for mime type or starred status or this or that? I would only make special effort to wrangle this permissions data into a form that puts it within reach of standard tidyverse wrangling tools. Then switch into documentation mode.

**Comment by dsdaveh** [comment]
The output of the example I wrote above looks like this (I added another role as well):

`> get_drive_perms(handle)
# A tibble: 3 x 6
    seq              emailAddress displayName  type      role              perm_id
  <int>                     <chr>       <chr> <chr>     <chr>                <chr>
1     1        dhurst79@gmail.com  Dave Hurst  user     owner 13748610123221591404
2     2 o9e4g9@u.northwestern.edu David Hurst  user    writer 13052913081444099008
3     3   davehurst.dev@gmail.com  Dave Hurst  user commenter 10724034039649260860`

One row per user seems 'tidier' and provides consistent columns.  As I mentioned, I modeled it after gs_perm_ls, which I found really intuitive to use.  BTW, I don't think its possible for a user to have multiple roles, I believe each role encompasses the lower roles (i.e 'owner' implies 'reader')

**Comment by jennybc** [comment]
A big difference between the direction @LucyMcGowan is heading and @dsdaveh's example above is dribble-ness, i.e. is the Drive file itself still a row or observation.

We are working inside that paradigm, because changing the permissions has to be that way. And thus we're trying to handle permission display/query similarly. It's also consistent with everything else and something we're already fully committed to.

@dsdaveh's approach is to produce a non-dribble-object of permissions for a single file (I'm guessing `handle` specifies the file). But the resulting tibble doesn't keep track of which file it's about anymore.

I suspect the "official functions" need to stay dribble focused and then we provide documentation on how to do what @dsdaveh is doing. I know that's a very conservative approach. It doesn't rule out adding something else later.

**Comment by dsdaveh** [comment]
I'm starting to see the dilemma.  I've got some catching up to do on dribble paradigm.

**Comment by jennybc** [comment]
> dribble paradigm

😆ha! You make it sound very official! It's more that this is how we've decided to store the info on one or more Drive files or Team Drives. And hewing to that makes workflows very fluid. Output of this can be input to that.

If we suddenly create a one-off data structure for a single file with, say, one row per person/role, we've got a dead end. That's a perfectly valid thing for us to demo in a workflow, because it might be exactly what a specific user needs! But I'm not sure we want to build functions into the package and commit to an interface and maintenance.

**Comment by dsdaveh** [comment]
Any time my head hurts, I blame a paradigm shift... its a low bar :-)

I'm having trouble figuring out how to handle all my use cases without changing the grain. I think the governing constraint is this one:

> Goal is to allow Drive access that feels similar to Unix file system utilities, e.g. find, ls, mv, cp, mkdir, and rm.

That seems like a great guiding principle, but won't it break down where Drive functionality doesn't doesn't map to unix functionality?  In this case, user specific permissions, which in Unix are typically handled with groups (not sure how these play in the Drive UI) or get/setfacl (but that also changes the grain).  The Drive UI itself suggests this, since in the advanced sharing UI its one row per user on a single file.  As a user of the package, it would be nice to have helper functions that return information about a file in a tibble (a fibble?), such as the `permissions Resource` in a form that is congruent with the Drive UI. The dribble already contains the necessary info in the `permissions Resource` if a developer does want to stay at the dribble grain, but it would be nice to be able to switch to another grain

> If we suddenly create a one-off data structure for a single file with, say, one row per person/role, we've got a dead end.   

I prefer the term "destination" ;-)
