### ISSUE TITLE
Deleting multiple files at once

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#137]
Noticed while preparing demo: what if you have several dribbles lying around and you want to delete them all? It's cumbersome to delete one by one. But you can't take advantage of the current vectorization of `drive_delete()` (soon to become `drive_rm()`), which requires them to be in one dribble or to form a vector of paths or ids. Think on this.

**Comment by LucyMcGowan** [comment]
One current option would be to bind all the `dribble`s you have together into a single `dribble` and remove those.
```
folder1 <- drive_mkdir("test1")
folder2 <- drive_mkdir("test2")
folder3 <- drive_mkdir("test3")

all_folders <- dplyr::bind_rows(folder1, folder2, folder3)

all_folders %>% 
  drive_rm()
```
