### ISSUE TITLE
Allow `q` to be passed to `drive_get()`

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#140]
This is currently needed so we can query the trash for `drive_untrash()`, but I can see other circumstances where we wish we could give a path and also pass something to the `q` parameter.

**Comment by jennybc** [comment]
In 68fa3b1ff9b3c7fc2db87e1a92ea0f742190a89d I refactored the trash functions and I believe this is no longer needed for that reason.

Can you describe some of the other reasons why we might want to pass `q` to `drive_get()`?

**Comment by LucyMcGowan** [comment]
Ah no I believe it was just that looks :ok_hand: now!
