### ISSUE TITLE
Download by ID

### ISSUE THREAD

**Issue by mramos-stellar** [tidyverse/googledrive#145]
There are instances where filenames can be duplicate found within Google Drive so it would be a good idea to use ID instead.

**Comment by LucyMcGowan** [comment]
I believe this is currently possible using the `as_id()` syntax:
```
id <- "1xw_M2OBUdPjoOVrmWKWNu07BW_PHCh-EMSfJN5WEJDE" ## stick your drive id here
drive_download(as_id(id))
```
