### ISSUE TITLE
Requesting version update for major functional/syntax changes

### ISSUE THREAD

**Issue by mramos-stellar** [tidyverse/googledrive#146]
Hi,

Thank you so much for this library. I'm currently using it for our project. I realized however, that as the changes are certainly greatly improving, I'd like to request if possible that you manage the releases better. Since all changes are in master and there are no tags created, all sudden syntactic changes breaks my existing code. 

For example: changes in drive_search to drive_find, drive_file to drive_get.

These changes impact the code and hence not allowing it to be automatically re-usable and repeatable.

Let me know how I can help as well.

Mark

**Comment by jennybc** [comment]
Hi @mramos-stellar -- thanks for trying it out! We are in the thick of developing the package, so yes there are lots of changes, though things are settling down a lot. googledrive hasn't had a CRAN release yet. Once it does, we will not change the interface the way we are doing now! You'll be able to count on versioning, a NEWS file, etc.

In the meantime you can pin yourself to specific commits by using this syntax:

```r
install_github(c("hadley/httr@76e8da4"
```

and catch up with HEAD at your convenience.

We will strive to start tagging with some development versions soon, so your point is well taken. Thanks again for kicking the tires.
