### ISSUE TITLE
"house" code style

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#15]
@LucyMcGowan 

There is a developing notion of a tidyverse code style. I might point this out at times but it feels like it would be more efficient to do one massive run at this.

To get a sense of what I'm talking about, install lintr from CRAN and, in the googledrive package/project, run `devtools::lint()`. You should get a long report of all the style "violations". There is a small number of themes here, but they each come up a lot.

Maybe you can do one massive lint-related PR?

Also let's figure out if your editor / dev process could be changed so that more of this just happens automatically.

**Comment by jennybc** [comment]
The main two documents for style are:

http://style.tidyverse.org

and

http://adv-r.had.co.nz/Style.html

I think the former is or is planned to supersede the latter (?). In any case, I don't think they contradict each other.

**Comment by LucyMcGowan** [comment]
I've given this a go in the `drive_list` branch 🤞

**Comment by jennybc** [comment]
OK I consider this message as "transmitted"  and "received". Compliance will remain an ongoing goal. lintr is a good thing to keep running, but it misses some things. Let know, maybe when we're together person?, if you want some help with your editor/IDE setup. This shouldn't be something you have to think about very much.
