### ISSUE TITLE
bulletize() helper

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#161]
This appears in many places:

```
glue_data(file, "  * {name}: {id}")
```

This might be overwrought but it could even be a generic, with methods for character and dribble.

In general, there is probably too much diversity in how the bulleted messages are formed.

**Comment by LucyMcGowan** [comment]
Sticking this here so we _maybe_ think about it later. 

We have a lovely double space before each bullet for our "hand-made" bulletize messages, but when we use `glue::collapse()`, these spaces don't exist 😞. For example `drive_rm()` messages are 👎, whereas `drive_upload()` messages are 👍 💃 .

**Comment by jennybc** [comment]
If I run, say, the `drive_rm()` example, everything looks fine. I don't think we have a problem with our result? I just don't like the way we're getting there.

**Comment by LucyMcGowan** [comment]
This is super minor, but when I run `drive_rm()` it doesn't have the space before the *, but `drive_upload()` does. For example:

```
file <- drive_upload(system.file("DESCRIPTION"))
#>Local file:
#>  * /Library/Frameworks/R.framework/Resources/library/base/DESCRIPTION
#>uploaded into Drive file:
#>  * DESCRIPTION: 0B0Gh-SuuA2nTcmVfbnEwSUVqbnc
#>with MIME type:
#>  * text/plain
```

Whereas `drive_rm()` the * is right up against the edge of the console. (Again super minor, but I kind of like that space 🙊 )
```
drive_rm(file)
#>Files deleted:
#>* test: 0B0Gh-SuuA2nTWGgzZl9ubTJydDg
```

**Comment by jennybc** [comment]
Maybe you need to update glue.

**Comment by LucyMcGowan** [comment]
🙈🙊

**Comment by jennybc** [comment]
This sort of thing is going to happen by centralizing all our UI stuff in, e.g., [cli](https://github.com/r-lib/cli). I will not be investing more time in UI beautification that is googledrive-specific.
