### ISSUE TITLE
drive_upload() and metadata

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#163]
Once #158 is done, we should revisit `drive_upload()`. It should probably have greater capabilities re: metadata.

**Comment by LucyMcGowan** [comment]
One simple option would be to just include `...` (with our new `dots-metadata` template) & subsequently pass it to the `drive_update()` call. I could include that in #158 if you think that'd suffice.

**Comment by jennybc** [comment]
I think #158 is a beast already. I'll merge it soon and then will you tackle this? And any appropriate examples and tests.
