### ISSUE TITLE
Naming pattern for functions that reveal details

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#172]
We need to do something to unify functions that show you the current state of files in a dribble wrt trashed-ness, path, sharing status, publishing status, etc.

Should it be:

`drive_show_trash()`
`drive_show_path()`
`drive_show_sharing()`
`drive_show_publish()`
etc.
?

Should be clearly distinct from functions that **do** something like put files in the trash, move files, or alter the sharing/publishing status.

**Comment by jennybc** [comment]
Browser links are another candidate for the "promote" treatment.

**Comment by LucyMcGowan** [comment]
Are you thinking something like `drive_show_link()`?

**Comment by jennybc** [comment]
I'm not sure yet, but they all have a common feel.

**Comment by jennybc** [comment]
MIME type
