### ISSUE TITLE
authentication does not generate .httr-oauth file

### ISSUE THREAD

**Issue by mramos-stellar** [tidyverse/googledrive#176]
Originally this works but right now it does not generate the file anymore. This is essential when knitting. Now I'm getting errors when knitting since it requires to connect and request for authentication due to the fact that the knitting is run in a separate R session.

Is this the expected behavior?

**Comment by jennybc** [comment]
Turns out that's a buglet in httr 1.3.0 that is going to be fixed shortly in a new point release.

See https://github.com/r-lib/httr/issues/475.

You could downgrade httr to previous version if this is a problem for you today, then update when the fix it on CRAN.
