### ISSUE TITLE
drive_download() return local file path as new column in returned dribble

### ISSUE THREAD

**Issue by MilesMcBain** [tidyverse/googledrive#183]
I'd like to suggest that the dribble returned form `drive_download()` contain a column or field in drive_resource which maps the remote file to the local path. 

For files that you might have some automated post processing for this would be amazingly handy (e.g. pandoc'ing).

Also useful for batch update with `drive_update()`.

P.S. I am pretty excited about what might be possible with this package. Amazing work! :+1: :star:

**Comment by jennybc** [comment]
That's a good idea. I had already pondered this or whether `drive_download()` should just return the local path. Have you considered that option? I think you're probably right about creating local path as a column in the dribble, though.

Name it `local_path`? We already use `path` in the case where user does something that causes the Drive path to get added to the dribble.

**Comment by MilesMcBain** [comment]
Seems like if I got a list of paths I would join them to the GD metadata in pretty short order. Makes it easier to pipe with the dribble and I think that is going to be good thing.

**Comment by jennybc** [comment]
OK will add this before release
