### ISSUE TITLE
Do not send an API key with a token (service account or OAuth)

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#184]
https://github.com/r-lib/gargle/issues/12

@craigcitro can you remind me or point me to something re: why this is to be avoided?

Note to self: consider NOT sending an API key with an OAuth token. I.e. only send API key when explicitly in an un-authorized state and sending no token whatsoever. This now seems like the best plan.

**Comment by craigcitro** [comment]
If you send both a token and an API key, the API backend will validate that they come from the same project.

So if you're baking in an API key for a project you own, and someone provides their own service account, this should fail with an error about a project mismatch.

**Comment by jennybc** [comment]
Ha! Thanks. I was modifying my above comment at the same time. I now think I should never send the API key with OAuth or service account token. Sound sane?

**Comment by craigcitro** [comment]
Yep, I think that's the right way to go.
