### ISSUE TITLE
BioC_mirrors.csv not found

### ISSUE THREAD

**Issue by hturner** [tidyverse/googledrive#186]
The examples in the "Upload files" section of the googledrive website (http://googledrive.tidyverse.org/#upload-files) uses the `BioC_mirrors.csv` file as an example, e.g. 

    (mirrors <- drive_upload(R.home('doc/BioC_mirrors.csv'), "README-mirrors.csv"))

For my R installation on Ubuntu 14.04, `R.home('doc/BioC_mirrors.csv')` returns `"/usr/lib/R/doc/BioC_mirrors.csv"`, yet there is no such file. However using

    `file.path(R.home("doc"), "BioC_mirrors.csv")`

as in `utils::chooseBioCmirror` returns `"/usr/share/R/doc/BioC_mirrors.csv"` which does exist, so specifying the file this way would fix this issue for me and presumably is a more general solution as that is what `utils::chooseBioCmirror` uses.

Note the path is used twice in this section.

**Comment by jennybc** [comment]
Thanks @hturner! Good to know that this is platform-dependent. We'll adjust accordingly. I find this sort of peculiar but will just accept that it is so.
