### ISSUE TITLE
Instructions in CONTRIBUTING.md for setting up OAuth token need updating

### ISSUE THREAD

**Issue by hturner** [tidyverse/googledrive#187]
The instructions for setting up an OAuth token don't work with the current package. Specifically

    token <- drive_auth(new_user = TRUE, cache = FALSE)

gives as error because `new_user` is not an argument of `drive_auth`. Perhaps the default would be no arguments, for someone who has already used the package?

**Comment by jennybc** [comment]
No, you're right. `drive_auth()` has changed since I wrote that. Use `reset = TRUE` instead of `new_user`. Will update.

For storing a token for these purposes, it's best to get a fresh one and be extremely deliberate.

**Comment by jennybc** [comment]
@hturner Have you actually attempted this = running our tests? I would be fascinated to know if you have and it works. Either way, would owe you one!

**Comment by hturner** [comment]
I have! I tried it before your earlier response, so didn't reset my token, but the check passed once I had save my token in tests/testthat. If I delete "testing-token.rds" though, the tests fail: `skip_if_no_token` gives an error because it cannot find the function `skip`. I'm not sure why, because presumably **testhat** is loaded when running the tests, but it seems a testthat::skip is needed there. If I add that in, the check passes, though you still get a warning which would be good to suppress:

    Warning message:
    In gzfile(file, "rb") :
      cannot open compressed file '/.../googledrive/tests/testthat/testing-token.rds', probable reason 'No such file or directory'

**Comment by jennybc** [comment]
Thanks @hturner! It's great to hear of your (substantial) success. I'll work on those rough edges.

**Comment by jennybc** [comment]
I still need to address the issue about not finding `skip()`.

**Comment by jennybc** [comment]
> If I delete "testing-token.rds" though, the tests fail: `skip_if_no_token` gives an error because it cannot find the function `skip`.

How did you run the tests when you saw this? I can't replicate with `devtools::test()` or with RStudio *Build > Test package*.

I *can* see the warning you're talking about.

**Comment by hturner** [comment]
I get the error in running the package check, via RStudio *Build > Check*. I just pulled your recent changes to my fork and still get this error on package check (without the token). This is the log I get 

    ==> devtools::check(cleanup = FALSE, args = c('--no-vignettes','--no-build-vignettes'))

    Updating googledrive documentation
    Loading googledrive
    Unable to load token
    Error in skip("No Drive token") : could not find function "skip"
    Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> doTryCatch -> skip_if_no_token
    In addition: Warning message:
    `cleanup` is deprecated 
    Execution halted

    Exited with status 1.

**Comment by jennybc** [comment]
That I can reproduce.

But if I do `check()` in the Console, I don't get the error. This is when the token is absent. Is that true for you as well?

This seems like it might be a peculiarity of whatever RStudio is doing via those menu-based check workflows.
