### ISSUE TITLE
Mimetype table

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#19]
* Store this in .drive environment.
* Centralize all info needed to act this way versus that based on mime type.

**Comment by LucyMcGowan** [comment]
@jennybc I've [started this](https://github.com/tidyverse/googledrive/blob/mimeType_tbl/data-raw/mime-types.R) & created the tables, how do I stick them in the `.drive` environment within the package? Do I save as .rdata & load into?

**Comment by jennybc** [comment]
Minor point: If I follow correctly, `zoo::na.locf(.)` could probably be replaced with `tidyr::fill()`, to stay more within tidyverse.

Here's an example of me [using `devtools::use_data(..., internal = TRUE)`](https://github.com/tidyverse/googlesheets2/blob/90ba56c18c11631a28b532b66c0c708776e8f549/data-raw/discovery-doc-prep.R#L188) to make a list named  `.endpoints` available to package functions. That is one option. But it does not put the object into any particular environment.  The `.drive` environment does seem like a logical place to store this.

Also, if you want to stash multiple objects, I think you would need to have them all available and do that at once. So this is possibly not the best approach in this case?

I suspect you should have an explicit assignment of this information to a tibble in `.drive`. It's great that you already have a data fetching/preparation script in `data-raw`. I suggest you write the results to csv below `inst/extdata` and load this to an internal data frame. About to push a commit to the relevant branch with a demo. You'll need to adapt to you scenario.

**Comment by LucyMcGowan** [comment]
* use the mime type table to intelligently choose upload file type

**Comment by jennybc** [comment]
Did you mean to close this when you merged #28?

**Comment by LucyMcGowan** [comment]
😱 yes!
