### ISSUE TITLE
Unable to authorize from shinyapps.io server

### ISSUE THREAD

**Issue by dsdaveh** [tidyverse/googledrive#202]
This is similar to #79 , but unfortunately the OOB workaround doesn't work on the shinyapps.io Connect server. I think the only way to do this might be to be to modify the underlying calls (httr?) so they can be passed through the Shiny UI, but I wanted know if there is a working example before I disappear into that brier patch.

**Comment by jennybc** [comment]
Yeah, explicit Shiny support must be added but that will definitely be implemented in gargle (#102), versus here in googledrive, so we can enjoy it across all Google APIs. The code exists in private gists, so that is on the horizon.

**Comment by jennybc** [comment]
Are you talking about using a static token (so, built into the app) or having the user authenticate via a Shiny app?

The former is possible, with the easiest thing being a service account token (vs OAuth token).

The latter has not gotten any explicit attention.

**Comment by oganm** [comment]
Was talking about the latter.

**Comment by jennybc** [comment]
I'm afraid I don't have a nice answer for you then 😔 You should be able to hack something together using examples/ideas from googlesheets and the newer auth that's here. That is, indeed, what I need to do and don't expect someone else to do. But that is the path forward.

**Comment by rensa** [comment]
Hi @jennybc, I'm working on a Shiny app where we're considering what @oganm is proposing: a Shiny app on a public server that allows individual users to auth with _their_ Google account and access private resources.

Right now I'm doing the easier thing: building on the assumption that the app'll run locally and only has to deal with one set of credentials. But I'm thinking about your last comment and trying to sketch out the next steps. is it okay if I do a bit of thinking out loud here? I don't want to burn up your time, but I'm hoping @oganm or others might also be able to chip in 😄 

In our specific case, users don't actually need access to entirely private or individualised resources: I in fact just need to verify that they have access to a shared Team Drive. So maybe a shortcut here is just [setting up a service token](https://github.com/tidyverse/googledrive/issues/115) based on my account and putting the site behind a proxy with a static password.

But if I were to go the full-fat solution here, my understanding is that I would need to essentially manage several sets of tokens (each user who logs in). I don't want any random person being able to use previously cached credentials, though, so my feeling is that:

1. any cached token from a successful auth needs to be sent back to the client browser in some form (maybe something being hashed and stored as a cookie?).
2. Then subsequent auth requests would first check for a cookie or stored data, compare the hash in the browser storage (if found) to hashes from cached tokens on the server, and on a match reuse the cached token.

How does that sound? Security is not something I'm trained in, so I'm playing it pretty conservatively until I'm confident that I understand how to handle credentials and tokens properly.

**Comment by jennybc** [comment]
This has become a very long thread, with multiple story lines and describing a moving target (googledrive). I'm closing.

To the extent that a Shiny app can be addressed with a single token managed by the app: I think non-interactive auth is easier and better documented in the coming v1.0.0, which uses gargle. The gargle vignette [Non-interactive auth](https://gargle.r-lib.org/articles/non-interactive-auth.html) is the definitive guide now.

If we're talking about managing user tokens, making this work well in a Shiny context is really a gargle-level issue. And is therefore being tracked by https://github.com/r-lib/gargle/issues/14.

I'm not saying Shiny is solved by any means. Just that this issue doesn't really represent a "work item".
