### ISSUE TITLE
Error downloading from team drive

### ISSUE THREAD

**Issue by philmikejones** [tidyverse/googledrive#205]
Dear Jenny and Lucy,

I am having difficulty downloading files from a team drive. I'm really going to struggle with a minimal reproducible example because of file confidentiality, but I've shared what I can below.

I have several small text files (`*.txt`) in a subfolder in a team drive, i.e.

- Datasets/keys/1234.txt
- Datasets/keys/5678.txt
etc

I am able to list these using:

```
keys = 
    googledrive::drive_ls(team_drive = dribble_team) %>% 
    filter(str_detect(name, ".txt$")) %>% 
    filter(str_detect(name, "^[0-9]....txt$"))
```

Where `dribble_team` is a `dribble` object linking to my team drive. The `keys` object is now a `dribble` in itself with the item `name`s, `id`s, and `drive_resource`s. 
When I try to download these items with `purrr::walk()` I get the following error:

```
walk(keys$id, googledrive::drive_download)
# Error: 'file' does not identify at least one Drive file.
```

Which I don't understand because `keys` is a dribble that contains info on several files. I've even checked by explicitly passing one known ID:

```
keys$id[1]
# [1] "0B-TotVDejb_xxxxxxxxxxxxxxxx"

drive_download(file = keys$id[1])
# Error: 'file' does not identify at least one Drive file.
```

I can only think this is because this file exists on a team drive; I've been able to download from my own drive before.
I can't share these particular files but let me know if there's something that would be useful for you to replicate this problem and I'll do what I can.

Thanks.

**Comment by jennybc** [comment]
I'm not in a position to run a Team Drive test right now but can later this week.

But one quick thing to try: what if you do this: `walk(keys$id, ~ googledrive::drive_download(as_id(.x))`.

**Comment by philmikejones** [comment]
Thanks @jennybc 

Using `as_id()` worked, so I was able to use `walk2()` to use the `id` and `name` to download and save to a file name respectively. I can see now that the documentation for `drive_download()` says to mark "a file id or URL" with `as_id()`, sorry!

**Comment by barbosawf** [comment]
Dear @philmikejones! Could you please show me how do you use walk2 to use the id and name to download and save to a file name respectively.?

**Comment by jennybc** [comment]
@barbosawf There are a few relevant examples in this thread of "workflows": https://github.com/tidyverse/googledrive/issues/123
