### ISSUE TITLE
Unshare google drive folder/file

### ISSUE THREAD

**Issue by cowlumbus** [tidyverse/googledrive#206]
Thank you for develop this beautiful tool. I use it to manage my course sharing. Now a new semester is coming. I want to unshare the course folder for the 140 students from last semester and then share it with new students. I didn't find the way to unshare a folder. Did I miss anything?

**Comment by LucyMcGowan** [comment]
I'm pretty sure we don't have a function exported for that -- the endpoint you are interested in is `drive.permissions.delete`, so something like this, using our lower level functions:

```{r}
folder <- drive_get("my_folder") # get your folder

req <- generate_request(
    "drive.permissions.delete",
    list(fileId = folder$id, 
         permissionId = file$drive_resource[[1]]$permissionIds[[2]]), 
    token = drive_token()
)
response <- make_request(req, encode = "json")
process_response(response) # this should be "TRUE" if it worked
```
You'll have to check which permission ids you want to delete, in general the first is the owner, so you can't delete that, in the code above, I picked the second with `folder$drive_resource[[1]]$permissionIds[[2]]`

We should probably incorporate this functionality though, thanks for submitting (& trying the 📦)!

**Comment by jennybc** [comment]
I think this is a specific case of #180

**Comment by cowlumbus** [comment]
Works like a charm!

For some reason, it returns an error message on my system:
`Error: These parameters are not recognized for this endpoint: token`

After delete `token = drive_token()`, it flies.

Thanks again.

**Comment by yb2125** [comment]
Thanks for the solution! Is there an endpoint for changing "viewersCanCopyContent" to TRUE/FALSE? If yes, how to adapt the code to make updates? Thanks!

**Comment by jennybc** [comment]
@yb2125 please see https://github.com/tidyverse/googledrive/issues/326#issuecomment-820802725

**Comment by yb2125** [comment]
@jennybc This is great! Thank you so much!
