### ISSUE TITLE
`drive_upload` doesn't use file extension when `type` is `NULL`

### ISSUE THREAD

**Issue by jarodmeng** [tidyverse/googledrive#207]
`drive_upload()` documentation says that file extension is used to determine type when `type` is `NULL` (see [here](https://github.com/tidyverse/googledrive/blob/master/R/drive_upload.R#L20)).

[This line of code](https://github.com/tidyverse/googledrive/blob/master/R/drive_upload.R#L114) determines the type included in params. It doesn't take into consideration the file extension. When `type` is `NULL`, `drive_mime_type` simply doesn't return anything.

```r
params[["mimeType"]] <- drive_mime_type(type)
```

I might be interpreting the documentation in a wrong way. Does it mean that the extension would be used by *Google Drive* rather than the `googledrive` package to determine the mime type? I was expecting to see something similar to what `drive_download()` has.

```r
ext <- file_ext_safe(path)
export_type <- type %||% ext %||% get_export_mime_type(mime_type)
export_type <- drive_mime_type(export_type)
```

**Comment by jennybc** [comment]
Hmm ... can you create an example to illustrate your concern? My mind is far away from this right now. But I think you may be correct that if we don't send a MIME type, then we're relying on Google Drive to determine if from file extension. In any case, would be easier to discuss in the context of "here's what I expect" vs. "here's what actually happens".

**Comment by LucyMcGowan** [comment]
I believe this statement is based on how `httr::upload_file()` handles when MIME types aren't given. It uses the `mime::guess_type()` function, which looks up the MIME type based on the extensions of the given filename.

**Comment by jarodmeng** [comment]
Here's my use case.

I'm using Google's [Colaboratory](https://colab.research.google.com) in Drive. Colab notebook is usually stored with file extension `ipynb` and has mime type `application/vnd.google.colab`.

This mime type is not included in `googledrive`'s [`mime_tbl.csv`](https://github.com/tidyverse/googledrive/blob/master/inst/extdata/mime_tbl.csv) or `mime`'s [`mimemap`](https://github.com/yihui/mime/blob/master/R/mimemap.R) and [`mimeextra`](https://github.com/yihui/mime/blob/master/R/mime.R#L61).

What I want to achieve is when I `drive_upload` an `ipynb` file, it's recognized as a Colab notebook automatically with the mime type `application/vnd.google.colab`. At the moment, I need to manually pass `type = "application/vnd.google.colab"` to `drive_upload()`.

My initial thought is that if `drive_upload()` looks for a mime type based on a file's extension using the `drive_mime_type()` function, then I can simply add a line to the `mime_tbl.csv` file mapping `ipynb` file to `application/vnd.google.colab`. During the research process, I discovered that `drive_upload()` actually doesn't pass the file's extension to `drive_mime_type()`.

@LucyMcGowan You're right that `httr::upload_file()` takes care of the mime type guessing. I think I will add a mapping between `ipynb` and `application/vnd.google.colab` to `mime`'s [`mimemap`](https://github.com/yihui/mime/blob/master/R/mimemap.R) and send Yihui a PR.

In the meantime, I'm wondering if I should also send a PR to `googledrive` to add the mapping in `mime_tbl.csv` since it's actually not being used in `drive_upload`.

**Comment by jennybc** [comment]
I think we were relying on some combination of the Google Drive API and `httr::upload_file()` to guess the MIME type. Here's a quote from the [docs on the `files.create` endpoint](https://developers.google.com/drive/api/v3/reference/files/create):

> The MIME type of the file. Google Drive will attempt to automatically detect an appropriate value from uploaded content if no value is provided.

But it's clear that neither Drive nor httr is expecting MIME type ` application/vnd.google.colaboratory` or `application/vnd.google.colab`.

I think the first thing to do is to teach googledrive about this MIME type, so that a direct specification works. I'm hesitant to explicitly set MIME type based on file extension, in general, because then I own that logic/data, whereas I think it really belongs upstream.

**Comment by jennybc** [comment]
You can now upload Colaboratory notebooks like so:

```
drive_upload("foo.ipynb", type = "colab")
drive_upload("foo.ipynb", type = "application/vnd.google.colab")
```

It still won't work automatically based on file extension because googledrive doesn't actually have any of that logic. That would require the Drive API to recognize Colab notebooks or a PR into the `mimemap` object in the mime package.
