### ISSUE TITLE
Error in eval(expr, envir, enclos) : could not find function ":="

### ISSUE THREAD

**Issue by njudd** [tidyverse/googledrive#209]
**not sure if this is an actual bug or my own issue (probably user based)**

Simply want to list all the id's within a folder containing csv data, so I can then read_csv all of them.

drive_ls() # lists all content in the drive
When I add a path, drive_ls(path = "abc")
Error in eval(expr, envir, enclos) : could not find function ":="

This error continuously comes up, regardless of how I enter the path.

**Comment by jennybc** [comment]
It sounds like you may have somehow gotten googledrive installed w/o all of its dependencies? Can you tell me what happens when you re-install from CRAN via `install.packages()`, quit R, restart R, `library(googledrive)` and try again?

**Comment by njudd** [comment]
I just tried it twice, it made no difference.

<img width="653" alt="screen shot 2018-01-30 at 6 59 35 pm" src="https://user-images.githubusercontent.com/24483076/35582683-c5d48da8-05ef-11e8-8bba-929c709395db.png">

**Comment by njudd** [comment]
Hey, thanks for your reply! I tried that a few times and it didn't work.

<img width="595" alt="screen shot 2018-01-30 at 7 20 49 pm" src="https://user-images.githubusercontent.com/24483076/35583584-b9b1b8a4-05f2-11e8-9b1d-d721e5676bc5.png">

**Comment by jennybc** [comment]
Can I see the output  of `devtools::session_info()`? I'm especially interested in your version of rlang.

**Comment by njudd** [comment]
**Version 0.1.6**
<img width="410" alt="screen shot 2018-01-30 at 7 31 37 pm" src="https://user-images.githubusercontent.com/24483076/35584100-4300c964-05f4-11e8-8c60-b09630f44d42.png">

**Comment by njudd** [comment]
Updated all of my packages and it seems to work now.
