### ISSUE TITLE
full path of files

### ISSUE THREAD

**Issue by RNA-Ninja** [tidyverse/googledrive#210]
`my_dir` contains two directories (`dir-1` &` dir-2`) and each of these directories have a `file.txt`. `drive_ls("my_dir", recursive = TRUE)` shows me that I have 2 `file.txt`. However it doesn't tell which file is from which directory. Is there a build-in function to show the full path (or path relative to `my_dir`) of files? For example: 
```
/my_dir/dir-1/file.txt
/my_dir/dir-2/file.txt
```

**Comment by jennybc** [comment]
Once you have those files in a dribble, feed that to `drive_reveal(..., what = "path")`. The examples for `drive_reveal()` should help.

**Comment by jennybc** [comment]
googledrive files don't actually know their own path! They only know who their direct parent(s) are. So it is some work to determine the path(s) to a specific file.
