### ISSUE TITLE
Trying to download but encounter error message

### ISSUE THREAD

**Issue by lohancock** [tidyverse/googledrive#211]
I hope it is OK I posted this on stackexchange at https://stackoverflow.com/questions/48693250/tidyverse-googledrive-download-from-google-drive-to-rstudio

I have installed googledrive so I could connect Google Drive to the R environment. I have duly supplied my password. I have checked that the connection works correctly by using drive_find(pattern="Lxxx"), and verified this produced the correct list of files. But

drive_download("L2018")

returns an error:

Error in eval(expr, envir, enclos) : could not find function ":="

Someone answered suggesting I install rlang, which I did, but there is still an error although different:
Error: Each variable must be a 1d atomic vector or list. Problem variables: ':=(!(!nm), val)' 

This package will be so helpful when done, I am rooting for You.

**Comment by LucyMcGowan** [comment]
Can you post the output of `devtools::session_info()`? This sounds similar to #209, but if you've already updated rlang, perhaps it is another package.

**Comment by lohancock** [comment]
It follows.  Before I do that - note - I achieved a download today by using the dribble as argument to drive_download, this way:  drive_download(solarfiles[1,]).  This achieved the download I had been unable to achieve using file name, e.g., drive_download("filename").  but after the file download it still sent an error message afterward as follows:
Error: Each variable must be a 1d atomic vector or list.  Problem variables: '`:=`(!(!nm), val)'

And attached is the sessioninfo.  
[sessionInfo.txt](https://github.com/tidyverse/googledrive/files/1712952/sessionInfo.txt)

Thank you for your help.  Even with the error message googledrive is already a HUUUGE help.
- Lucy

**Comment by jennybc** [comment]
@lohancock you have rang version 0.1.6 which was released on CRAN 2017-12-21.

Since then a new version has come out on 2018-02-20: version 0.2.0.

I think updating rlang is likely to fix your problem.

Do `install.packages("rlang")`. Restart R for good measure. Then confirm the version via `packageVersion("rlang")`. Then try your googledrive workflow again and let us know how it goes.



rlang_0.1.6

**Comment by jennybc** [comment]
Even if I downgrade googledrive (to CRAN) and rlang (past 2 CRAN versions), I cannot reproduce this error. So if you keep seeing it, I will be very interested to to see a reprex with session info and/or `packageVersion()`.

https://www.tidyverse.org/help/

**Comment by jennybc** [comment]
OK I can reproduce errors like yours with an old version of tibble installed.

So tibble is the package you really need to update.

`install.packages("tibble")`

**Comment by lohancock** [comment]
THANK YOU! 





-----Original Message-----
