### ISSUE TITLE
drive_update() changes the file URL on googledrive

### ISSUE THREAD

**Issue by sanjmeh** [tidyverse/googledrive#212]
Unless it is by design, this seems a bug.
`drive_update(media = "abcd.csv",file=dribble_1)`
This command should ideally upload the media into the same file as pointed to by dribble_1.
Now the problem is, googledrive silently changes the URL, so the linkages in google sheets all break.
I was trying to solve a limitation of `googlesheets` package where `gs_edit_cells` used to hang. So we had this solution suggested by @jennybc  as a work aroiund to use drive_upload or drive_update. But unfortunately both these functions create new URLs on google drive. Could this be something that can be fixed easily?  Right now we are on a roadblock as we have no way to update existing google sheets and the `gs_edit_cells is buggy.` Thanks for reading through.

**Comment by LucyMcGowan** [comment]
Hi @sanjmeh, I am not able to reproduce your result -- when I update a file, the resulting object has the same id as the previous.

```
library(google drive)
d <- drive_upload(
  drive_example("chicken.csv"),
  name = "chicken-sheet-upload.csv",
  type = "spreadsheet"
)
#> Local file:
#>   * /Library/Frameworks/R.framework/Versions/3.4/Resources/library/googledrive/extdata/chicken.csv
#> uploaded into Drive file:
#>   * chicken-sheet-upload.csv: 1VX3owMkORCQU80Ie3EZ_WHVlIyhZnx1AqBywxSCTuOE
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet
d$id
#> [1] "1VX3owMkORCQU80Ie3EZ_WHVlIyhZnx1AqBywxSCTuOE"
d <- drive_update(d, drive_example("chicken.csv"))
#> File updated:
#>   * chicken-sheet-upload.csv: 1VX3owMkORCQU80Ie3EZ_WHVlIyhZnx1AqBywxSCTuOE
d$id
#> [1] "1VX3owMkORCQU80Ie3EZ_WHVlIyhZnx1AqBywxSCTuOE"
``` 
Can you maybe show me a small example of what happens in your case?

**Comment by jennybc** [comment]
Yes, I echo @LucyMcGowan.

You're right @sanjmeh that `drive_update()` should NOT change a file's id.

Can you provide an example where it does so? Thanks.

**Comment by sanjmeh** [comment]
I have to confirm that drive_update **does** work. It does not change the previous URL. Apologies for raising this issue without confirmations from repeated tests.
