### ISSUE TITLE
Auth process using Client and Secret

### ISSUE THREAD

**Issue by tarunparmar** [tidyverse/googledrive#213]
Hi @jennybc ,
I have tried below with googlesheets packages and able to authenticate and save token for my custom app.
```
options(googlesheets.client_id = "<client-id>",
        googlesheets.client_secret = "<secret>",
        googlesheets.httr_oauth_cache = FALSE)
gs_token <- gs_auth(cache = FALSE)
gd_token()
saveRDS(gs_token, file = "googlesheets_token.rds")
```

But this did not work:
```
options(googledrive.client_id = "<same-client-id>",
        googledrive.client_secret = "<same-secret>",
        googledrive.httr_oauth_cache = FALSE)

drive_token <- drive_auth()
drive_token()
saveRDS(drive_token, file = "googledrive_token.rds")
```

Is this possible in `googledrive` package ?

**Comment by jennybc** [comment]
Can you elaborate on "did not work"?

**Comment by tarunparmar** [comment]
I setup an app and enabled both Drive and Sheets API. I had to get that app approved through our IT team and once approved I tested it out. 
I know I should have named it generic for both Drive and Sheets but I named it "rstudio googlesheets" not knowing that I could have both authenticated through same app. 

So when I first authenticate googlesheets using above code, I see this :
![image](https://user-images.githubusercontent.com/17690950/38375852-2954019e-38c5-11e8-8793-4a7f19a87ee4.png)

But when I run googledrive auth code, I see this:
![image](https://user-images.githubusercontent.com/17690950/38375813-0f3d314a-38c5-11e8-9678-20c554bfa31f.png)


So was wondering if the app for Drive is hardcoded or I could somehow manually point it to use my client/secret for authentication.

**Comment by jennybc** [comment]
The auth config works differently for googledrive than for googlesheets.

This is in the process of getting centralized into a single package that I/RStudio will use for any package that wraps a Google API. So it will be less confusing in the future.

But for now you need to tell google**drive** about your app in the way it needs to hear it. `drive_auth_config()` is the gateway to all of this in google**drive**.

So yes you should be able to use the same app but the syntax differs between these two packages.

**Comment by tarunparmar** [comment]
I followed the `drive_auth_config()` [reference](http://googledrive.tidyverse.org/reference/drive_auth_config.html) and provided clientid and secret to `httr::oauth_app()` but not sure how they link. May be I am missing something or not able to follow the example in reference.

**Comment by jennybc** [comment]
Can you show me the output of the example given in `drive_auth_config()`?

``` r
drive_oauth_app() # I'd expect to see the default tidyverse app at this point
my_app <- httr::oauth_app(
  "my-awesome-google-app",
  key = "123456789.apps.googleusercontent.com",
  secret = "abcdefghijklmnopqrstuvwxyz"
)
drive_auth_config(app = my_app)
drive_oauth_app() # I'd expect to YOUR app at this point
```

**Comment by tarunparmar** [comment]
`drive_auth_config()` lists tidyverse as oauth app. 
But assigning output of `httr::oauth_app()` and using that object in `drive_auth_config()`  was what I was missing. 
It worked ! :tada: 
I can see it shows my app to authenticate now when I use `drive_auth()` or other functions. 

Thank you so much! :+1: 
I didn't get what `drive_oauth_app()` was..

**Comment by jennybc** [comment]
`drive_auth_config()` is the main function for viewing or setting auth configuration.

`drive_oauth_app()` is a lightweight diagnostic function to reveal the app currently in force.
