### ISSUE TITLE
Problem with download from scheduled script

### ISSUE THREAD

**Issue by DavidGarciaEstaun** [tidyverse/googledrive#214]
Hi,

I am having problems with the download function when it is executed from the taskscheduleR package.
When I execute manually everything works fine.
I do the authentication from a static rds file:
drive_auth("C:/Users/davidgae/Documents/dAuth.rds")

Trace:
Auto-refreshing stale OAuth token.
Error in gzfile(file, mode) : no se puede abrir la conexión
Calls: drive_download ... <Anonymous> -> <Anonymous> -> cache_token -> saveRDS -> gzfile
Además: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '.httr-oauth', probable reason 'Permission denied'
Ejecución interrumpida

Can you please help me?
Thanks in advance.

David.

**Comment by jennybc** [comment]
It sounds like the user associated with the process that runs taskscheduleR might not be the same user who owns `dAuth.rds`. I suggest putting some lines earlier in your script that messages or logs some facts about who is the current user and listing files (definitely including `dAuth.rds`) in a way that reveals permissions. The fs package has a handy function [`dir_info()`](https://fs.r-lib.org/reference/dir_ls.html) that presents this info in a very readable form.
