### ISSUE TITLE
Slightly uninformative error when search returns no Team Drive

### ISSUE THREAD

**Issue by romunov** [tidyverse/googledrive#215]
If a user makes a mistake when entering Team Drive name (in `drive_find`), an error

```
Error: length(teamDriveId) == 1 is not TRUE
```

is produced. This is slightly obscure, in my opinion, and would be better read as something along the lines of "No Team Drives by that name were found". This is handled [here](https://github.com/tidyverse/googledrive/blob/abb6bdd34980be58680d0a7b60285a65a05ba8c3/R/team_drive_params.R#L113). Would you be susceptible to a PR for this?

**Comment by jennybc** [comment]
Sure! It looks like we didn't really write a user-facing error message here, so happy to have one.
