### ISSUE TITLE
Unable to refresh token, with 'Error: HTTP error [401] Invalid Credentials'

### ISSUE THREAD

**Issue by shawzhifei** [tidyverse/googledrive#223]
This issue happens several days ago, around June 4th, 2018. I used to save the token file and use drive_auth('token.rds') as authentication and it works well all the time. But recently I found out I have to recreate this token file by 'token = drive_auth()'. 

If not, it will show up this error when I try to use drive_upload function

Auto-refreshing stale OAuth token.
Error: HTTP error [401] Invalid Credentials
  * domain: global
  * reason: authError
  * message: Invalid Credentials
  * locationType: header
  * location: Authorization
In addition: Warning message:
Unable to refresh token

**Comment by shawzhifei** [comment]
I believe this happens as soon as refresh stale OAuth token is needed. Because the newly created auth file failed as soon as the Auto-refreshing stale OAuth token message appeared

**Comment by jennybc** [comment]
Refresh tokens do not last forever, i.e. you can't necessarily use one to get a new access token. The two most common reasons for a refresh token to become invalid are:

  * Falls off the end. You can only have a certain number (maybe 30?) of active refresh tokens. So if you are doing any sort of work that keeps requesting new tokens, it will cause existing ones to become invalid.
  * Inactivity. If you don't use a refresh token for a while (maybe 6 months?), you will no longer be able to get an access token with it.

**Comment by jennybc** [comment]
If you create a completely new token and store it to to file (such as `token.rds`) are you back in business?

**Comment by shawzhifei** [comment]
Thanks for the quick response. I have created a new token and store it to file, it was working for like 10 mins. And then 'Auto-refreshing stale OAuth token' message shows up and then the 401 error appeared again. The same newly created token file was used. This issue happens only recently. It happened on my own laptop, server and also my colleague's laptop, who was using another google account.

**Comment by jennybc** [comment]
It's very hard to see that this is specific to googledrive (as opposed to, say, a problem or change of behaviour at Google).

**Comment by shawzhifei** [comment]
After days of trying, I believe the issue is with the tidyverse app during authentication. I've created a project myself and use the google drive app in the drive_auth_config, and the issue is solved.

Some more info before I found the solution. If I keep doing the key$refresh(), the offline token can survive several hours, or else the key$validate() will be False in less than an hour.
