### ISSUE TITLE
Is it possible to authenticate without browser? 

### ISSUE THREAD

**Issue by Diego-MX** [tidyverse/googledrive#225]
It looks like [issue number 79](https://github.com/tidyverse/googledrive/issues/79) is related, yet I've moved several things and no success.

I'm not using a server per se, but I'd like to authenticate via an automated process.   I'm using Microsoft's PowerBI, which allows R scripts to create and refresh sources; and thus I want to download a google sheet in order to have it loaded.  
However I have little control on how P-BI runs the those scripts, and it looks like it gets stuck waiting for authentication whenever I try to use `drive_download(file)`.  

Even before getting to issue 79's solution with `drive_auth(new_user = TRUE)` y tried running `drive_auth('.httr-oauth')` in RStudio and got: 
```
> drive_auth(".httr-oauth")
Not a Token2.0 object.
Error in eval(parse(text = text, keep.source = FALSE), envir) : 
object 'token' not found 

```
Am I doing this right?  Thanks,

**Comment by jennybc** [comment]
First, if you can make the target sheet readable by anyone with a link, you could turn off auth entirely via `drive_auth_config(active = FALSE)`. Then googledrive will not attempt to get and send a token.

If that doesn't work, you have to find a way to get a token and then put it into force on PowerBI (which unfortunately I know nothing about).

If you are going to work with an OAuth token (the "usual" kind of token obtained in an interactive session), you need to do this once in a browser setting. You can let that token get written to the default fault file `.httr-oauth` or you can purposefully store it to an `.rds` file yourself. Either way, you must now get that token file onto PowerBI. If it's in the working directory of the R process from which you are calling googledrive, `.httr-oauth` should be discovered. If you chose to write the token object to an `.rds` file yourself, then you load it via `drive_auth("path/to/token.rds")`. Note: you do not use `drive_auth()` with `.httr-oauth`. I realize that is confusing, but the format of `.httr-oauth` is not the same as writing a single token to file, hence the error you got above.

Finally, the very best way to work with Drive (or most Google APIs) non-interactively is to get a service account and use a service account token. If you are going to be doing this a lot, that is worth setting up. Then you will have a simple JSON file containing the token. You put that where you need it and load via `drive_auth("path/to/service-token.json")`.

**Comment by Ivanaz916** [comment]
Hi, Im having a similar issue but when trying to automate an R script which calls:
drive_download("File", type = "csv", overwrite = TRUE)
and this R script is to be automated via Windows Task Scheduler.

As Jenny suggests in solution #1, I added:
drive_auth_config(active = FALSE).

From the log file, I get the following error:
googledrive auth state: inactive
oauth app: tidyverse
API key: set
token: not loadedError: HTTP error [403] The user does not have sufficient permissions for this file.
  * domain: global
  * reason: insufficientFilePermissions
  * message: The user does not have sufficient permissions for this file.
Execution halted

Im unclear on solutions #2 and #3 above.  How would I get the OAuth token to be used by Windows Task Scheduler?

**Comment by jennybc** [comment]
The `drive_auth_config(active = FALSE)` solution only works **if** the file has been made world readable.

Is that true?

If not, then you must make an authorized request on behalf of an authenticated user. So you have to make sure that the correct token will be found and used automatically.

Are you using CRAN googledrive or dev?

**Comment by Ivanaz916** [comment]
Thank you.  the file is not world readable/public so I guess I have to take the token route.

Is there a posting you can point me to which explains how I can get a token and make it usable for the windows task scheduler?

Im using CRAN googledrive.

**Comment by jennybc** [comment]
I'm going to close this and let #239 be the issue for non-interactive auth. This will be different -- hopefully much more straightforward! -- in the next release, once [gargle](https://gargle.r-lib.org) is on CRAN and I can release an update to googledrive. The dev version of googledrive has already switched over.
