### ISSUE TITLE
Passing tokens into functions

### ISSUE THREAD

**Issue by tsmith64** [tidyverse/googledrive#227]
I'm having a problem in a shiny app with multiple simultaneous users. Because the authorization call effects a global variable, when one person logs on, the others end up logged in to their google drive as well. I am still relatively new to R, so I'm not sure if I'm making a simple mistake. Currently I call the library function outside the server module that uses it. I think that calling the library function inside this module will not make a difference, but I'm not completely sure based on what I've been reading online. My current solution is to call the authorization function with the cached token before each drive_upload, drive_update, and drive_download call; however this is definitely not ideal. 

My question: is it possible to pass the authorization token discretely to each function call? I have not found this in the documentation.

**Comment by jennybc** [comment]
> is it possible to pass the authorization token discretely to each function call?

In general, no.

The high-level functions have generally not been written to support this, because it's pretty uncommon and adds complexity. `drive_auth()` and `drive_auth_config()` are the functions for dealing with tokens and auth config, respectively. Then those settings remain in effect for subsequent calls.

googledrive *does* expose lower-level functions (you'll see them called in all the high-level functions), e.g. `generate_request()` and friends. If you want to manage tokens yourself, you probably want to call these lower-level functions directly.

How many googledrive functions do you call in your app? I assume/hope it's a relatively small set and you can create wrappers for yourself that rely on the lower-level API and achieve the token behaviour that you want.

Alternatively, you might want to create a [withr-style](http://withr.r-lib.org) `with_token()` for yourself so that you could use the existing high-level functions.

**Comment by tsmith64** [comment]
I mainly use the `drive_upload()`, `drive_update()`, `drive_download()`, and `drive_ls()` functions. Thank you for the advice! I will look into the withr-style functions and alternately create wrapper functions for the low-level function calls. 

Thank you once again!

**Comment by jennybc** [comment]
Just to give you a heads up: `generate_request()` is going to live in a not-yet-on-CRAN package, [gargle](https://github.com/r-lib/gargle), so we can also use it from [googlesheets4](https://github.com/tidyverse/googlesheets4), [bigrquery](https://cran.r-project.org/web/packages/bigrquery/index.html), [gmailr](https://github.com/jimhester/gmailr), etc.. So if you decide to use it, be mentally prepared to switch from `googledrive::generate_request()` to `gargle::generate_request()` in the next few months. The interface shouldn't change much but just FYI.

**Comment by tsmith64** [comment]
I ended up modifying the googledrive functions that I'm using to pass tokens through. I'm not sure how to modify the `drive_get` function though as it does not appear to be a wrapper function around the `generate_request` function. I'm also running not able to call certain functions like `toCamel` and `partition_path`. Can I gain access to these library specific functions? There seem to be a lot of them. 
Here is a sample of how I modified your code on just one of the drive functions:
```
# Added the token argument into the function call
drive_upload_2 <- function (media, path = NULL, name = NULL, type = NULL, ..., 
                            verbose = TRUE, token=drive_token()) 
{
  if (!file.exists(media)) {
    stop_glue("\nFile does not exist:\n  * {media}")
  }
  if (!is.null(name)) {
    stopifnot(is_string(name))
  }
  if (is_path(path)) {
    confirm_clear_path(path, name)
    path_parts <- partition_path(path, maybe_name = is.null(name))
    path <- path_parts$parent
    name <- name %||% path_parts$name
  }
  dots <- toCamel(list(...))
  dots$fields <- dots$fields %||% "*"
  params <- c(uploadType = "multipart", dots)
  if (!is.null(path)) {
    path <- as_parent(path)
    if (!is.null(params[["parents"]])) {
      stop_collapse(c("You have specified parent folders via both 'path' and 'parents'.", 
                      "Pick one.", "If you want multiple parents, just use the 'parents' parameter."))
    }
    params[["parents"]] <- path$id
  }
  params[["name"]] <- name %||% basename(media)
  params[["mimeType"]] <- drive_mime_type(type)

# Added token into generate_request
  request <- generate_request(endpoint = "drive.files.create.media", 
                              params = params, 
                              token = token)

  meta_file <- tempfile()
  on.exit(unlink(meta_file))
  writeLines(jsonlite::toJSON(params), meta_file)
  request$body <- list(metadata = httr::upload_file(path = meta_file, 
                                                    type = "application/json; charset=UTF-8"), media = httr::upload_file(path = media))
  response <- make_request(request)
  out <- as_dribble(list(process_response(response)))
  if (verbose) {
    message_glue("\nLocal file:\n  * {media}\n", "uploaded into Drive file:\n  * {out$name}: {out$id}\n", 
                 "with MIME type:\n  * {out$drive_resource[[1]]$mimeType}")
  }
  invisible(out)
}
```
