### ISSUE TITLE
Planned date for next CRAN release

### ISSUE THREAD

**Issue by Serenthia** [tidyverse/googledrive#228]
The latest CRAN version is 0.1.1, released in August 2017. As of recently, pretty much every function is throwing a glue deprecation warning because of the move from `collapse()` to `glue_collapse()`.  I see this was fixed in PR #222 so I can install from Github, but is there a plan to update the CRAN version to the latest code?  Many thanks.

**Comment by jennybc** [comment]
I hadn't fixed a date in my mind, but thanks for the nudge. There are some bigger changes coming under the hood for auth, but it's probably a good idea to NOT wait for that. I'll start to plan a small release in the near future.

**Comment by jennybc** [comment]
In the works now.
