### ISSUE TITLE
Foreign character file names

### ISSUE THREAD

**Issue by eeenilsson** [tidyverse/googledrive#229]
Trying to download files with foreign characters in filename (Swedish) gives the following error:

`Error: 'file' does not identify at least one Drive file.`

This was using `drive_download`. After renaming file download worked as expected.

Suggestion: Make it possible to download via file id so that file does not have to be renamed before download.

**Comment by jennybc** [comment]
I can download a file, by name, with non-ascii characters in the name:

``` r
library(googledrive)

drive_get("äggplanta")
#> # A tibble: 1 x 4
#>   name      path       id                                    drive_resource
#>   <chr>     <chr>      <chr>                                 <list>        
#> 1 äggplanta ~/äggplan… 1HcC4kHJ19aNrtPNuWDUcrO-PhKJb1g0_e3h… <list [34]>
```

As @LucyMcGowan says, though, once you get your hands on the file id, you can refer to the file that way, as a end run around this issue.

@eeenilsson Let me guess: you are on Windows? It should be possible to fix this for you.

**Comment by jennybc** [comment]
Fixed in https://github.com/jeroen/curl/pull/183.

To sum up:

  * The current workaround for non-ascii file paths on Windows is to find some other way to refer to the file, presumably by id, and use that.
  * The next time curl updates on CRAN, the problem should fixed at its source.
