### ISSUE TITLE
Report progress from high-level functions that use map()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#235]
Report progress when we use `purrr::map()` to make one API call per file. For example, `drive_reveal()` can be very slow and it would be good to know what it's doing.

**Comment by jbayham** [comment]
On a related note, it would also be nice to have a progress bar for large downloads using drive_download()

**Comment by jennybc** [comment]
This will be handled through some combination of adopting [httr2](https://httr2.r-lib.org) and using batch requests #360. I'm certainly not going to do any more work on the sub-optimal purrr stuff. The next step is to remove it.
