### ISSUE TITLE
Authentication for googledrive and googlesheets packages simultaneously?

### ISSUE THREAD

**Issue by grabear** [tidyverse/googledrive#243]
Hello!

I'm working on a Shiny app that I would like to use to create folders and files, as well as manipulate Google Sheets from the app.  So I decided to learn how to use OAuth through googlesheets/googledrive.  Below is an overview of my workflow, and where I'm at now:

- [x] Learn how to create a web application with Google Developer Console
    - [x] Activate Google Drive and Google Sheets APIs for my application
- [x] Learn how to use googlesheets (not under development) and googledrive from shiny
- [x] Augment [shiny example code](https://github.com/jennybc/googlesheets/tree/master/inst/shiny-examples/20_gs-explorer) to fit my needs
- [x] Troubleshoot OAuth setup in Google Developer Console
- [ ] Troubleshoot shiny app

I've currently got the basics of authentication working properly.  I'm authenticating `googlesheets` correctly with my custom settings:
```r
options("googlesheets.webapp.client_id" = MY_CLIENT_ID)
options("googlesheets.webapp.client_secret" = MY_CLIENT_SECRET)
options("googlesheets.webapp.redirect_uri" = MY_REDIRECT_URI)
```
And I'm even authenticating with `googledrive` properly using:

```r
    googledrive::drive_auth_config(
      app = 
        httr::oauth_app(
          appname = "Shiny Loot Dashboard", 
          key =  MY_CLIENT_ID, 
          secret = MY_CLIENT_SECRET, 
          redirect_uri = "http://127.0.0.1:4642"
          )
      )
```
However, I would like to authenticate both at the same time.  Currently, I have to authenticate twice to progress in my shiny app, and that's not a good solution.

Is there any way to authenticate both at the same time?  Should I make either package store a cached token, or can I somehow use `googleAuthR` or `httr` to accomplish what I need?

**Comment by grabear** [comment]
As an afterthought should I be using the up and coming `googlesheets4`?  And if so how do I solve the same problem there?  `googledrive` and `googlesheets4` seem to function with the `gargle` package so I'm assuming this might be easier?

**Comment by jennybc** [comment]
Yes, we are centralizing our google API logic, including auth, in the not-yet-released package called gargle:

https://github.com/r-lib/gargle

This should make it easier to use a token that has enough scope with both packages. But the exact flow is not worked out yet. Now that rstudio::confidence is over, I am returning to the gargle/googlesheets4/googledrive space. So keep your 👀 open. Maybe watch those repos and feel encouraged to test drive and provide feedback.

**Comment by grabear** [comment]
@jennybc.

I thought you might be tied up with rstudio::conf.  It looked like a ton of fun.  Anyways, thank you for the insight on the google/gargle projects.

> Maybe watch those repos and feel encouraged to test drive and provide feedback.

I will!  I've got my app working to some degree so I will simply put up with the double authentication for now and work on the functionality.  I hope to have something to submit to the rshiny contest.  

Cheers,
@grabear

**Comment by grabear** [comment]
Hi @jennybc!

Over the Christmas break, I'm going to return to my project.  I was wondering if gargle/googlesheets4/googledrive are at a point so that I can authenticate once for drive/sheets?

I hope that all has been well with you.

Cheers,
@grabear

**Comment by jennybc** [comment]
That is documented here:

https://googlesheets4.tidyverse.org/articles/articles/drive-and-sheets.html

**Comment by grabear** [comment]
Thanks @jennybc!
