### ISSUE TITLE
Error in curl

### ISSUE THREAD

**Issue by stapial** [tidyverse/googledrive#244]
I have been using drive_download function several times to sync a google sheet I'm working on into my group github repo automatically.

It has been working perfectly all the times I've used it. However, today I got an unexpected error that I have no idea how to go about

Here is the code I am using

```r
drive_download("AdCap conceptual model indicator table",  
type="xlsx", path="SocialResilienceConceptualModel/AdCap conceptual model 
indicator table.xlsx", overwrite=TRUE)
```
Today, for the first time, I started getting this error

> Error in curl::curl_fetch_disk(url, x$path, handle = handle) : Failed to open file SocialResilienceConceptualModel/AdCap conceptual model indicator table.xlsx.

As mentioned, I have been using this exact same function with the exact same arguments all this time and never got an error, until today. I also double checked that the working directory was the directory of the repo I'm working in, as it has been on the original drive_download() runs

Any leads?

**Comment by jennybc** [comment]
I've got no idea what's going on. Did it self-resolve?

**Comment by stapial** [comment]
Hi @jennybc. Thank you for responding.

It has not. I gave up on it. My guess is it has to do with the authentication process with the google account? As I said, it worked at first and stopped working (I remember having to go through a pop-up screen asking for a google login). Could it have anything to do with the fact that I have multiple google accounts?

Best

**Comment by jennybc** [comment]
This error just does not look like a credentials problem. But you can always use `drive_user()` to see which identity google drive is currently working with.

General due diligence suggestion: update the curl package.

Otherwise, it would be interesting to see the traceback.

**Comment by jack-gregory** [comment]
Thanks @jennybc!  I had the exact same issue as @stapial except using the `boxr` package.  Updating `curl` resolved the issue.
