### ISSUE TITLE
Cannot download shared file

### ISSUE THREAD

**Issue by arendsee** [tidyverse/googledrive#247]
I am the maintainer of the ropensci/onekp package. This package is a portal to public data that was previously available though FTP, but now it is on a shared Google Drive. When I try to download these files with `curl`, Google directs me to a page that requires confirmation to bypass the virus scan (ropensci/onekp#2).

As an alternative to directly using `curl`, I have been trying to download the files with `googledrive` using the UUIDs. But this fails:

```r
library(googledrive)
googleID <- as_id("1GrB19Tl87zAbpqh3wgO8NCi9xR371MZq")
x <- drive_get(googleID)
x
#> # A tibble: 1 x 3
#>   name             id                                drive_resource
#> * <chr>            <chr>                             <list>        
#> 1 URDJ.faa.tar.bz2 1GrB19Tl87zAbpqh3wgO8NCi9xR371MZq <list [37]> 
drive_download(x)
#> Error: The file doesn't seem to have downloaded.
```

The metadata retrieved by `drive_get` looks correct (`x$drive_resource[[1]]`), for example it finds the correct name of the dataset maintainer.

The downloaded file (`URDJ.faa.tar.bz2`) has the following content:

```
{
 "error": {
  "code": 500,
  "message": null
 }
}
```

It seems that `drive_get` can find the public file, but that `drive_download` cannot. Is downloading download external shared files not supported?

**Comment by jennybc** [comment]
I don't have any experience trying to download a `.tar.bz2` but that aspect of this certainly grabs my attention.

FWIW an error code >=500 generally means it's a server-side error vs, say, an ill-formed request. I'll try to have a look.

**Comment by jennybc** [comment]
Yeah I can't download it either. But I also don't fail outright, i.e. I download something but it's not the actual or whole file.

I suspect that this SO thread is relevant:

https://stackoverflow.com/a/39225039/2825349

Specifically, this:

> When downloading large files from Google Drive, a single GET request is not sufficient. A second one is needed, and this one has an extra URL parameter called confirm, whose value should equal the value of a certain cookie.

**Comment by jennybc** [comment]
I don't really consider this a googledrive issue at the moment, but am happy to discuss further if it becomes more clear what the angle of attack should be.
