### ISSUE TITLE
Drive Download Fails with Badly Named Files

### ISSUE THREAD

**Issue by medewitt** [tidyverse/googledrive#248]
I am trying to download a file using `drive_download`. The file that I am trying to download has a file name that has quotations and apostrophes (don't ask me....). As such I am getting a failure notification.

```r
# Loads just fine
(chicken <- drive_upload(
  drive_example("chicken.csv"),
  'README-chicken "Just an Example" (Really Bad).csv'
))
# Search for my file
a <- googledrive::drive_find(n = 5)

my_id <- "ID for my files"

# Try to download my file
googledrive::drive_download(as_id(my_id), type = "csv")
```
And I get the following error message:
```
Ignoring `type`. Only consulted for native Google file types.
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Failed to open file michael\README-chicken "Just an Example" (Really Bad).csv
```

However, when I add a more appropriate name to the path argument I can download it.

```r
googledrive::drive_download(as_id(my_id), type = "csv", path = "test.cvs")

> File downloaded:
> * README-chicken "Just an Example" (Really Bad).csv
> Saved locally as:
>  * test.cvs
```

So a workaround exists, but a little bit of a bug nonetheless.

**Comment by jennybc** [comment]
Thanks for the clear reprex. Note that I get the same result in both cases. Did you mean to use the file extension "cvs" instead of "csv"?

``` r
> googledrive::drive_download(as_id(my_id), type = "csv")
Ignoring `type`. Only consulted for native Google file types.
File downloaded:
  * README-chicken "Just an Example" (Really Bad).csv
Saved locally as:
  * README-chicken "Just an Example" (Really Bad).csv
> googledrive::drive_download(as_id(my_id), type = "csv", path = "test.csv")
Ignoring `type`. Only consulted for native Google file types.
File downloaded:
  * README-chicken "Just an Example" (Really Bad).csv
Saved locally as:
  * test.csv
```

I'm still looking into what's going on.

**Comment by jennybc** [comment]
OK yeah, the message is actually correct. You should not be specifying `type` here. It is only consulted when you are exporting a native Google file type (e.g. a Sheet or Doc) to something else (e.g. csv or txt).

This simpler command does a simple download:

``` r
> googledrive::drive_download(as_id(my_id))
File downloaded:
  * README-chicken "Just an Example" (Really Bad).csv
Saved locally as:
  * README-chicken "Just an Example" (Really Bad).csv
```

**Comment by jennybc** [comment]
I'm not sure what's going on in your case:

```
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Failed to open file michael\README-chicken "Just an Example" (Really Bad).csv
```

Where the the "michael" come from"? In any case, I think something else is going on there in terms of a bad input.
