### ISSUE TITLE
Upload folder & contents

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#25]
* currently with `drive_upload()` you can input a folder, and it will upload a folder of that name to google drive, but not the contents of the folder 🙃🌴

**Comment by LucyMcGowan** [comment]
hmm actually this is trickier that I assumed since there doesn't seem to be a way to do it in one call. maybe the best thing would be to do something like:
```
input <- dir("~/foo", full.names = TRUE)
output <- paste("foo", tools::file_path_sans_ext(basename(input)))
purrr::map2(input, output, drive_upload)
```
and we could wrap that in a function like `drive_upload_dir`?

**Comment by jennybc** [comment]
I'll just point that R itself doesn't really have a nice way to copy a directory. So I'm not surprised that this is a bit more involved than one first thinks!

The interface question is a good for one for next week. Should `drive_upload()` be "smart" and detect a directory as input? Or should there be an argument to indicate this? Or should you make a second wrapper, i.e. `drive_upload_dir()`?

**Comment by jennybc** [comment]
I'm going to close this as "not an immediate goal" to package as a function. But we will show how to do this in a simple scenario somewhere.
