### ISSUE TITLE
Drive_ls fails on public folder with api_key based auth

### ISSUE THREAD

**Issue by lukaskawerau** [tidyverse/googledrive#252]
I am trying to access a public folder ("Anyone with link can view") without using OAuth configuration. If I understand the [documentation](https://www.rdocumentation.org/packages/googledrive/versions/0.1.3/topics/drive_auth_config) correctly, this should work by deactivating auth and attaching an api_key.  
I'm using googledrive v0.1.3, installed from CRAN.  
The following code fails with the error message below:

```r
library(googledrive)

drive_auth_config(active=FALSE, api_key='my_api_key') 
# example folder that is safe to share:
drive_ls("https://drive.google.com/drive/folders/1ox_HwuhS3KZX5TKbm5oxa01I898LrgGL?usp=sharing") 
```
```
Error: HTTP error [403] The user does not have sufficient permissions for this file.
  * domain: global
  * reason: insufficientFilePermissions
  * message: The user does not have sufficient permissions for this file.
```

Permissions both on the folder and the file in it are set correctly: "Anyone with link can view".

**Comment by jennybc** [comment]
You need to indicate that you're providing the file via a URL (which, to us, means via file id), as opposed to its filename. Surround that URL with `as_id()`.

```
> drive_ls(as_id("https://drive.google.com/drive/folders/1ox_HwuhS3KZX5TKbm5oxa01I898LrgGL?usp=sharing"))
# A tibble: 1 x 3
  name            id                                           drive_resource
* <chr>           <chr>                                        <list>        
1 bugreport-sheet 1ZlnA1ovR-rd_W7IwRaHe9Q48GJ0Cbv2xzCCe9QAUov8 <list [29]>   
```
