### ISSUE TITLE
Path does not work when scopes is set to drive.file

### ISSUE THREAD

**Issue by giocomai** [tidyverse/googledrive#255]
It appears that if - using the version currently available on github - I set scopes to "https://www.googleapis.com/auth/drive.file" (https://developers.google.com/identity/protocols/googlescopes#drivev3) with an app ID I created then I cannot use standard folder paths to upload/download/list files.

If I provide dribbles instead of a path, all works well. 

Find below reprex, with key and secret hidden:

``` r
library("googledrive")
google_app <- httr::oauth_app(
  "*****",
  key = "*****",
  secret = "*****"
)

googledrive::drive_auth_config(app = google_app)

googledrive::drive_auth(email = "*****",
                        scopes = "https://www.googleapis.com/auth/drive.file")


googledrive::drive_mkdir(name = "example_for_issue")
#> Folder created:
#>   * example_for_issue


googledrive::drive_upload(media = googledrive::drive_example(path = "chicken.csv"),
                          path = "example_for_issue")
#> Error in inherits(d, "dribble"): HTTP error [404] File not found: 0ABVQmP0dhv-pUk9PVA.
#>   * domain: global
#>   * reason: notFound
#>   * message: File not found: 0ABVQmP0dhv-pUk9PVA.
#>   * locationType: parameter
#>   * location: fileId

folder_dribble <- googledrive::drive_ls() %>% 
  dplyr::filter(name == "example_for_issue")

googledrive::drive_upload(media = googledrive::drive_example(path = "chicken.csv"),
                          path = folder_dribble)
#> Local file:
#>   * /home/*****/R/x86_64-redhat-linux-gnu-library/3.5/googledrive/extdata/chicken.csv
#> uploaded into Drive file:
#>   * chicken.csv: 1yMmemNssPIb2TA_TapUeFT6ieXsEIJ2h
#> with MIME type:
#>   * text/csv

googledrive::drive_ls(path = "example_for_issue")
#> Error: HTTP error [404] File not found: 0ABVQmP0dhv-pUk9PVA.
#>   * domain: global
#>   * reason: notFound
#>   * message: File not found: 0ABVQmP0dhv-pUk9PVA.
#>   * locationType: parameter
#>   * location: fileId

googledrive::drive_ls(path = folder_dribble)
#> # A tibble: 1 x 3
#>   name        id                                drive_resource
#> * <chr>       <chr>                             <list>        
#> 1 chicken.csv 1yMmemNssPIb2TA_TapUeFT6ieXsEIJ2h <list [38]>
```

<sup>Created on 2019-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jennybc** [comment]
I think this behaviour is expected. The Drive API only supports file access by ID. All access based on file name and file path is provided by the googledrive package and, to do that, we need to be able to list your whole Drive and lookup the parent folder(s) of each file, in order to construct the file hierarchy.

With the scope you've specified, here's what the consent screen shows:

<img width="277" alt="Screen Shot 2019-07-24 at 4 25 54 PM" src="https://user-images.githubusercontent.com/599454/61835488-bfbcde80-ae30-11e9-8a40-8e8d5c51c205.png">

With this scope, we're only allowed to look at files created with this specific app, which is going to basically break our ability to derive file ID from file name or path. So, yeah, you'll need to be very aggressive about working with a `dribble`, which identifies files by ID, if you want to work with a token scoped like this.

**Comment by giocomai** [comment]
Thank you for this careful explanation. I'll probably go around it with more local caching (e.g. storing locally the dribble identifier when creating the folder), and including in functions a fallback option based on actually listing available contents within this scope first.

Thanks again!

**Comment by jennybc** [comment]
I gather that you must have a reason for be conservative with scopes. But maybe even adding `"https://www.googleapis.com/auth/drive.metadata.readonly"` would restore your ability to use googledrive's path functionality. It's worth a try.

**Comment by giocomai** [comment]
I am considering to include some integration with `googledrive` in a couple of packages I've been working on, in order to facilitate basic backup/restore (and perhaps sharing) of files generated by the package. I feel I'd be asking too much trust from users by demanding access to *all* of their Google Drive files just to backup some files, which is why I felt the permission request as it appears in the screenshot above is less intimidating, and ultimately better-fitting. Even `drive.metadata.readonly` exposes much more data than I'd need in this context. But I understand why `drive.file` it doesn't work as I initially hoped.

Also, I used this on a shared Rstudio server that is occasionally used by colleagues... again, I'm fine with colleagues potentially having access to a specific backup folder, but less so if access must be given to *all* of my Google Drive. 

While the latter use case could (and should!) be approached by better internal organisation, perhaps  some documentation on "Best practices for integrating `googledrive` in your package" could be nice, as there's anyway the not so straightforward and related issue of how to include app key and secret.

Thanks again for your suggestion!
