### ISSUE TITLE
createTcpServer: permission denied

### ISSUE THREAD

**Issue by hwsamuel** [tidyverse/googledrive#259]
Step 1. Install **googledrive** package
Step 2. `library(googledrive)`
Step 3. `drive_find(n_max=10)` (was shown authentication prompt in browser and function call worked fine)
Step 4. Repeat Step 2 & 3, gets the following error

```
createTcpServer: permission denied
Error in .subset2(public_bind_env, "initialize")(...) : 
  Failed to create server
```

**Comment by jennybc** [comment]
This error comes from some lower level tool, not googledrive itself.

Are you getting any errors that reveal anything about ports? This has a vague smell of a zombie process sitting on a port a la [this thread](https://github.com/jennybc/googlesheets/issues/343#issuecomment-370202906).

Googling "createTcpServer: permission denied" is fairly productive, so perhaps something you see there will resonate with other details you're seeing.

**Comment by hwsamuel** [comment]
Thanks for the super-fast reply, the link you gave mentioned using `options(httr_oob_default = TRUE)` and that worked for me! After using that, I can re-authenticate and it works fine

**Comment by jennybc** [comment]
Great! But that's a very disappointing solution, in the long-term (out-of-band auth). I'd encourage you to figure out the problem, because the other browser flow is much nicer.
