### ISSUE TITLE
create demos or articles of quirky use cases

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#26]
some I've thought of so far:
* ability to push slides made in RStudio to drive every time you render
* creating a "live" resume like [this](https://lucymcgowan.shinyapps.io/live-cv/) with Google Drive + shiny (or a semi-live one that just needs re-rendering like [this](http://www.lucymcgowan.com/html-cv/live-cv.html))
* storing an .rda file on Google drive & using it in an R analysis (like #17)
* collaborating on a .Rmd on Google Drive & rendering in R (tricky, because versioning...would work fine if it was only edited on the Google Drive, but hard to manage that)
* creating a document & adding a tibble of people by sending them an email (with glue!)

**Comment by LucyMcGowan** [comment]
if you don't have pandoc you can actually use googledrive as a converter

**Comment by jennybc** [comment]
trying to find a file that has been renamed but used to be called "foo" ... or something like that

there's a field for original file name in the files resource

**Comment by jennybc** [comment]
also local csv --> Google Sheet --> local xlsx, w/o actually having excel

**Comment by jennybc** [comment]
Let's fold this into #123
