### ISSUE TITLE
Error 413 when fetching data

### ISSUE THREAD

**Issue by dgplaco** [tidyverse/googledrive#260]
Hi Jenny! Sorry to bother you again, but I looked everywhere and I didn't find anyone having a problem such as this. Using the cool advice you gave me a couple of days ago, I've been building a Shiny+GoogleDrive app which works (almost) perfectly. Here's the code:

```r
analisisdiscurso <- 'drive.google.com/longurl1'
discurso <- 'drive.google.com/longurl2'
planificacion <- 'drive.google.com/longurl3'

search <- function(words, date, folder=NULL){
    
    if (missing(date)){
        
        terminos <- toString(words)
        query_words <- paste0(c("fullText contains ", "'", terminos, "'"), collapse = "")
        query_search <- drive_ls(path = as_id(folder),
                                 recursive = TRUE,
                                 q=query_words)
        
        
    }
    
    else {
        terminos <- toString(words)
        fecha <- toString(date)
        query_words <- paste0(c("fullText contains ", "'", terminos, "'"), collapse = "")
        query_date <- paste0(c("modifiedTime > ", "'", fecha, "'"), collapse = "")
        query_search <- drive_ls(path = as_id(folder),
                                 recursive = TRUE,
                                 q=query_words,
                                 q=query_date)
        
    }  
    
}
```

An abridged version of the UI/server is as follows:

```r
##UI
checkboxGroupInput(inputId = 'carpeta',
                               label = 'Carpetas',
                               choiceNames = list('Análisis del discurso', 'Discurso', 'Planificación'),
                               choiceValues = list(analisisdiscurso, discurso, planificacion))

##server
doc_found <- eventReactive(input$buscar,{
        holder <- search(input$terminos, req(input$fecha, cancelOutput = TRUE), input$carpeta)
        holder %>% select(name) %>% rename("Nombre del archivo"= name)
    })

```
Regardless of how well crafted and optimized is that code (I'm sure it can be improved), I'm receiving a strange error message only when using what I called "planificacion", which is the third possible option. It says "Error 413 (Request Entity Too Large)!!1" (and a huge chunk of what I assume is HTML code), and I have no idea how to fix that (or what is that). I don't have any problem with the other two options, or even with no option at all (which looks for content everywhere in the drive, with no folder specification).

Any clues? Thank you once again!

**Comment by jennybc** [comment]
Congratulations (?) because I think you're successfully using googledrive and encountering a puzzle with the Drive API itself. Any error in the 400s generally means you've sent problematic input. Two lines of investigation:

1. Are you sending the input you think you're sending? In a regular R session (not Shiny), find the smallest bit of code that generates the error, then run it again inside `httr::with_verbose()` to see exactly what's going out over the wire. Example:

``` r
httr::with_verbose(
  googledrive::drive_find(n_max = 5)  
)
```

Do same with a "good" call and scrutinize for differences.

2. Google "413 Request Entity Too Large Google API" or "413 Request Entity Too Large Drive API". I'm fairly confident this is not a problem with googledrive but just something tricky about calling the Drive API. So errors and solutions from other languages might help you figure it out.

You're welcome to reopen if it looks like this package really is part of the problem.

**Comment by jennybc** [comment]
BTW from my Googling, I suspect this means the payload you're ?sending? is too large. Does one of these folders you're searching have _lots_ of subfolder and the `q` is getting huge?

**Comment by dgplaco** [comment]
Thanks Jenny, I'm the luckiest guy ever (?). 
I'll try the bit you suggested in the first message, but what you said on the second one might be the key: perhaps there are many subfolders at that one (somewhere between 30 and 40, that doesn't sound like a lot, but who am I to judge?). 
What baffles me is the fact that it doesn't fail when I set no folders at all (and it does return every content needed, even when searching inside that problematic folder), but it looks like you're right and it isn't a problem with the package, but with the Google API. At least we're all learning something, hahaha!

**Comment by jennybc** [comment]
There may be some limit in terms of how much you can cram into a `q` clause and this recursive search is causing us to form such a clause. The Drive API does not support recursive search, so googledrive is recursively creating the list of parent directories and expressing that as a `q` clause.
