### ISSUE TITLE
drive upload is too opinionated

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#27]
* thinking of eliminating the [type logic](https://github.com/tidyverse/googledrive/blob/master/R/drive_upload.R#L59-L94) (it definitely needs to change, it is way too narrow)

**Comment by LucyMcGowan** [comment]
@jennybc what are you thoughts on letting `httr::upload_file()` handle guessing the mime type using their `guess_type()` logic?

**Comment by jennybc** [comment]
When you say "their" `guess_type()` logic, what are you referring to?

**Comment by LucyMcGowan** [comment]
being worked on in #19
