### ISSUE TITLE
Intermittent duplicates in drive_ls()

### ISSUE THREAD

**Issue by andrie** [tidyverse/googledrive#272]
I get intermittent errors when using `drive_ls()` on one of my folders.

```R
library(googledrive)
drive_auth(email = "my_email")
drive_ls("~/some/folder/")
#> Error in add_id_path(nodes, root_id = root_id, leaf = leaf): 
#> !anyDuplicated(nodes$id) is not TRUE
```

For some strange reason, this fails most of the time, but sporadically succeeds, in the same folder!

PR to follow.

**Comment by davidmasp** [comment]
I also got this problem, it was very puzzling...

**Comment by jennybc** [comment]
Can anyone describe the situation in a bit more detail? It's very hard for me to figure out the source of the duplication (is it us or google?) without knowing this.

**Comment by davidmasp** [comment]
how can we test it? happy to help but I am not sure what's the cause either, sorry. I can confirm that after installing the PR from @andrie the issue was fixed though.

**Comment by jennybc** [comment]
I’m wondering if it affects, E.g., a file with more than 1 parent directory. Or a file that shares the same name with a distinct file in the same folder. That sort of thing. Both are possible on Drive.

**Comment by andrie** [comment]
I moved some of my files on Google Drive, and now I can no longer replicate the issue.

**Comment by jennybc** [comment]
I still have yet to experience this phenomenon or get enough data to truly study it.

But I have formed an untestable hypothesis about the root cause and installed a fix 🤞

Needless to say, please open a new issue if you update to this dev version and *still* see the phenomenon.

**Comment by cisoto** [comment]
I did something that worked for me.  
I was not sure if tokens were still alive, so i refreshed them just before calling the file_cp, or file_mv, or file_whatever.  
I do not understand the behaviour of the Auth system, but sure the solution is there

**Comment by jennybc** [comment]
I'm skeptical this is related to auth.

It's intermittent for everyone, which makes it easy to falsely attribute success to something that's a coincidence.
