### ISSUE TITLE
Authentication pains

### ISSUE THREAD

**Issue by DataStrategist** [tidyverse/googledrive#280]
I'm attempting to use the new gargle method of authentication, and I'm really struggling to follow the instructions on the gargle page.

**My use case:** "I would like to non-interactively authenticate into google drive, in order to upload, download and edit files. I'm using Rstudio server."

**My problem:** "I can't access any of the files on that Drive"

I've checked out the instructions here: https://gargle.r-lib.org/articles/non-interactive-auth.html, and here's where I get stuck:

 1. I create a service account token as per https://gargle.r-lib.org/articles/get-api-credentials.html#service-account-token
 2. Upload json to the correct repo
 3. run the following code: 

```
> options(gargle_quiet = FALSE)
> googledrive::drive_auth(path = "storied-shelter-255312-6a11718e6afe.json")
trying token_fetch()
trying credentials_service_account()
adding 'userinfo.email' scope
service account email: driveaccesser@storied-shelter-255312.iam.gserviceaccount.com
```

So it IS authenticating into the token, but it's going to an email address of that specific service account, not into the actual email address of the googledrive itself. 

What am I doing wrong?

**Comment by jennybc** [comment]
It is working as documented and designed. I'm not sure what you mean by "email address of the googledrive itself".

The authenticated user = the email address.

So when you log in as `driveaccesser@storied-shelter-255312.iam.gserviceaccount.com`, via a service account token, you present yourself to the Drive API as that user. What other user or email address are you thinking of? I don't see another one mentioned above.

If this code needs to run on a remote server, I would continue using a service account. Then, this service account needs to either own the files it needs to access or be added by the owner with an appropriate role (see `drive_share()`). Example: add the service account as a `"reader"` or `"writer"`.

If this code is running locally, it's fine to keep using the same user OAuth token you are already using. In the code that runs non-interactively, do `drive_auth(email = TRUE)` or `drive_auth(email = "target_user@gmail.com")` as described in the section "I just want my `.Rmd` to render":

https://gargle.r-lib.org/articles/non-interactive-auth.html#sidebar-2-i-just-want-my--rmd-to-render

**Comment by DataStrategist** [comment]
Thanks for taking the time Jenny.

The email whose files I wanted to access was the main google account, ie "blah@gmail.com" rather than the "blah.gserviceaccount.com".

The problem w/ using `drive_share` would be that the gserviceaccount.com login (what the server had) couldn't see the files, so I would have had to share them from an interactive session for the service account to be able to see them... since there are many files being created at different times this wasn't tenable, as I'd have to every so often log in from my laptop and reshare the new files.

But then something strange happened... I am using this on two repos, and I realized that one of the repos DID have access to the full list of files, while the other one did not. using the exact same code! Which was `googledrive::drive_auth(path = "storied-shelter-255312-6a11718e6afe.json", email = "BLAH@gmail.com")`. Then I remembered that during my tests I had done the `oob` auth, and that had gotten stored SOMEWHERE... no idea where, it couldn't have been `~/.R/gargle/gargle-token-orwhhatever` because if so, then both repos would have had access to it. It also wasn't stored anywhere in that project, so it's a bit of a mystery.

Anyway, long story short, I tried doing `drive_auth(use_oob = TRUE)` once in the other repo, cleared the authentication, and now just using `googledrive::drive_auth(email = "BLAH@gmail.com")` seems to work, even when run by crontab, without even providing the service account creds. 

In fact, that's why it's working now. I just did `drive_about` and sure enough, it's using the `blah@gmail.com` rather than the service account.

I could have sworn I tried that before unsuccessfuly,  but it seems to work now. When I switch to ggooglesheets4 I'll make a screencap just to verify that I'm not crazy. 

I'll close.

PS - I still love you, you're awesome and this package is awesome, and these improvements are awesome... I'm just frustrated at myself because I've been wrestling with this for 3 days on and off and I'm not used to that, and what's even worse, I can't PR you any improvements because I have no idea why things worked out in the end.

**Comment by jennybc** [comment]
What you describe makes sense to me: it sounds like you successfully did auth once, using out-of-bound auth, and therefore have a cached token. And indicating `googledrive::drive_auth(email = "BLAH@gmail.com")` is exactly what's needed to allow this token to be used and for your code to run successfully via cron.

If you want to confirm all of this, get the cache location with `gargle:::gargle_default_oauth_cache_path()` and go look in that directory. You will presumably see a file named something like `abcdefghijklmnopqrstuv_BLAH@gmail.com`. That is the token that's being used.

For even more detail, set `options(gargle_quiet = FALSE)` and you'll see lots of information about the auth process, most of which you won't care about.

**Comment by jennybc** [comment]
Responding to another issue just reminded me of this function:

`gargle::gargle_oauth_sitrep()` will give you an overview of the OAuth user token cache, e.g. cache location and a summary of the tokens found there.

**Comment by DataStrategist** [comment]
so now it looks exactly like it should:
![image](https://user-images.githubusercontent.com/8094091/66589540-a6e9dc80-eb86-11e9-8194-63cd61ac4bed.png)

but then I have no idea why it didn't work before for the second repo. IE, 2 repos, using the same exact functions, one passed, one didn't, until I did `oob auth` for the second repo... 

Anyway... just happy it all seems to work. and by that I mean at least THIS PART WORKS, now I can spend the rest of my evening figuring out why the SQL Server doesn't think a table exists only when crontab calls it. sigh... is it beer-o-clock yet?
