### ISSUE TITLE
drive_upload() and drive_update() hang when uploading... errr... medium-ish sized file

### ISSUE THREAD

**Issue by ben519** [tidyverse/googledrive#283]
First off, thank you for this wonderful package Jenny (and your other work as well). Over the recent months it's become more and more vital to my workflow and my company's daily reporting and processes. Hence the issue..

It appears that one of the google sheets that I update daily has grown to the point where drive_update() just hangs and never completes. Thing is, the file itself is not that large. (FYI, I would append rows to this file, but to my knowledge that functionality doesn't exist yet, so I'm stuck using `drive_update()` to essentially rebuild the entire spreadsheet with a few extra rows every day.)

# Reprex
Here's a simple reprex that uses `drive_upload()` on a one-column CSV file with 100K rows (which works) and then on a one-column CSV file with 120K rows (which hangs). I haven't run timings, but the 100K-row file uploads in <30 seconds while the 120K-row file hangs for minutes before I cancel the process.
```
library(googlesheets4)
googlesheets4::sheets_auth(email = "myemail@mydomain.com", use_oob = TRUE)

# 100,000 rows (works)
foo <- data.frame(x = seq(1, 100000))
write.csv(foo, file.path(tempdir(), "foo.csv"))
file.info(file.path(tempdir(), "foo.csv"))$size  # 1377797 bytes
foo_ss <- googledrive::drive_upload(media = file.path(tempdir(), "foo.csv"), type = "spreadsheet", path = "foo.csv")

# 120,000 rows (hangs)
foo2 <- data.frame(x = seq(1, 120000))
write.csv(foo2, file.path(tempdir(), "foo2.csv"))
file.info(file.path(tempdir(), "foo2.csv"))$size  # 1697797 bytes
foo2_ss <- googledrive::drive_upload(media = file.path(tempdir(), "foo2.csv"), type = "spreadsheet", path = "foo2.csv")
```
Maybe I missed something in the docs, but I haven't found anything regarding file-size limits.

Thanks

**Comment by jennybc** [comment]
Hmm. I think there is no quick fix for this. I am working on the write/edit capability for googlesheets4 right now, so perhaps watch that repo so you can try those features as they roll out.

Otherwise, I think this suggests that gargle needs to facilitate resumable uploads, which was already on my radar:

https://developers.google.com/drive/api/v3/manage-uploads#resumable

That is not a small piece of work and I believe write/edit capability will arrive in googlesheets4 first.

**Comment by jennybc** [comment]
If you're really stuck, over in googlesheets4, we could probably help you craft the commands you need to update your specific Sheet, using all the same low-level helpers I do, as an interim solution, until general high-level functions are in place.

**Comment by ben519** [comment]
Okay, thanks Jenny. I'll take a look at googlesheets4 and let you know if I need help. Honestly, it might be more cost effective for me to manually upload the sheets I need, as that only takes a second or two (albeit, a pain).

To your point about resumable uploads, [googleCloudStorageR](https://github.com/cloudyr/googleCloudStorageR) already does this well, in case you weren't aware. Might be worth reviewing [that code](https://github.com/cloudyr/googleCloudStorageR/blob/master/R/upload.R) before you get started building it yourself.

**Comment by jennybc** [comment]
googlesheets4 will be able to write soon. The interface might be in flux for a little while, but it will be a usable feature soon.

**Comment by jennybc** [comment]
@ben519 I'd welcome a new issue on googlesheets4 describing in prose or pseudo code exactly what sort of write/update command you need. It helps to see examples.

**Comment by ben519** [comment]
@jennybc, just to be clear, should I assume you're working on write/update functionality *without* resumable upload capability? At least, in the interim. (The file size constraint changes how I might go about updating spreadsheets. Without a file-size constraint, I'd almost always opt to `read data from cloud > process locally > overwrite entire spreadsheet in cloud` since it's easy and has less room for error)

**Comment by jennybc** [comment]
> should I assume you're working on write/update functionality without resumable upload capability?

Yes.

What command do you wish existed? I'm particularly interested in the issue of the "complete overwrite of ... a spreadsheet? a single sheet within a spreadsheet? a named range within a sheet?" vs. "append" workflows.

**Comment by ben519** [comment]
Got it. Give me a day or so to play around with googlesheets4 and I'll try to get back to you a clear FR. Thanks again.

**Comment by jennybc** [comment]
I'm going to close this and:

  * open an issue in gargle about resumable upload
  * anticipate further discussion in googlesheets4
