### ISSUE TITLE
driv_auth and google colaboratory

### ISSUE THREAD

**Issue by jobdiogenes** [tidyverse/googledrive#284]
I'm trying to use googledrive and [googlesheets4](https://github.com/tidyverse/googlesheets4) in Google Colaboratory, but tips about drive_auth found in #276 or #274, did not solve.

Here is the Colab Notebook. [Demo of use GoogleDrive with R in Google Colaboratory](https://colab.research.google.com/drive/1nXsie313OuXjIZMsSOnJULcUpwecsRB-#scrollTo=M5qbBfJn3fc4)
that I'm testing. 

The error is 

> trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: googledrive
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
Error: Can only use oob authentication in an interactive session
>Error: Can't get Google credentials.
>Are you running googledrive in a non-interactive session? Consider:
>* `drive_deauth()` to prevent the attempt to get credentials.
>* Call `drive_auth()` directly with all necessary specifics.
>
>Traceback:
>
>1. drive_auth(use_oob = TRUE)
>
>2. stop("Can't get Google credentials.\n", "Are you running googledrive in a non-interactive session? Consider:\n", 
> .     "  * `drive_deauth()` to prevent the attempt to get credentials.\n", 
> .     "  * Call `drive_auth()` directly with all necessary specifics.\n", 
> .     call. = FALSE)

**Comment by jennybc** [comment]
I've requested access to your Colab notebook from my RStudio email address. I'll take a look when I'm allowed.

**Comment by tingjhenjiang** [comment]
> 
> 
> I'm trying to use googledrive and [googlesheets4](https://github.com/tidyverse/googlesheets4) in Google Colaboratory, but tips about drive_auth found in #276 or #274, did not solve.
> 
> Here is the Colab Notebook. [Demo of use GoogleDrive with R in Google Colaboratory](https://colab.research.google.com/drive/1nXsie313OuXjIZMsSOnJULcUpwecsRB-#scrollTo=M5qbBfJn3fc4)
> that I'm testing.
> 
> The error is
> 
> > trying token_fetch()
> > trying credentials_service_account()
> > Error: Argument 'txt' must be a JSON string, URL or file.
> > trying credentials_app_default()
> > trying credentials_gce()
> > trying credentials_byo_oauth()
> > Error: inherits(token, "Token2.0") is not TRUE
> > trying credentials_user_oauth2()
> > Gargle2.0 initialize
> > attempt from: googledrive
> > adding 'userinfo.email' scope
> > loading token from the cache
> > no matching token in the cache
> > Error: Can only use oob authentication in an interactive session
> > Error: Can't get Google credentials.
> > Are you running googledrive in a non-interactive session? Consider:
> > 
> > * `drive_deauth()` to prevent the attempt to get credentials.
> > * Call `drive_auth()` directly with all necessary specifics.
> > 
> > Traceback:
> > 
> > 1. drive_auth(use_oob = TRUE)
> > 2. stop("Can't get Google credentials.\n", "Are you running googledrive in a non-interactive session? Consider:\n",
> >    .     "  * `drive_deauth()` to prevent the attempt to get credentials.\n",
> >    .     "  * Call `drive_auth()` directly with all necessary specifics.\n",
> >    .     call. = FALSE)

same issue here.

> 
> 
> I've requested access to your Colab notebook from my RStudio email address. I'll take a look when I'm allowed.

Actually all you need is to save a copy of that ipynb file to your own drive, or you might just run it.

**Comment by jennybc** [comment]
OK I've replicated all of this.

The fundamental problem seems to be that both `interactive()` and `rlang::is_interactive()` report `FALSE` on Google Colab. So you out-of-band auth won't work. But you can also only use out-of band auth!

I'm going to have to consult with the Google Colab expert: @craigcitro.

Here's a notebook @craigcitro where I've replicated what the others say. By setting options manually, I can establish the gargle cache directory. But out-of-band auth still fails because a Colab R runtime appears to always report that we are not in an interactive session. So I'm wondering how auth could ever work 🤔

https://colab.research.google.com/drive/1pp8-7aFzvrGtnpwxHmzlTXADPGbw8_Rh

**Comment by jennybc** [comment]
Here's where httr forbids oob auth in a non-interactive session. Although I think it might actually work on Colab?

https://github.com/r-lib/httr/blob/af25ebd0e3b72d2dc6e1423242b94efc25bc97cc/R/oauth-init.R#L227-L234

**Comment by jobdiogenes** [comment]
After some research I found a way to make it work.
I did some small changes in htr oauth.  (myfork), test and propose these changes to the team.
Maybe not the perfect code for now, but works. 

Anyone which want to test, I just update the [Demo of use GoogleDrive with R in Google Colaboratory](https://colab.research.google.com/drive/1nXsie313OuXjIZMsSOnJULcUpwecsRB-#scrollTo=M5qbBfJn3fc4)

**Comment by terzieff** [comment]
I have the exact same issue, not in Colab, but running JupyterLab (Version 1.2.1) in my own environment on Google Kubernetes Engine.

```
interactive()
FALSE

rlang::is_interactive()
FALSE

sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS/LAPACK: /opt/conda/lib/libopenblasp-r0.3.7.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.6.2  IRdisplay_0.7.0 pbdZMQ_0.3-3    tools_3.6.2    
 [5] htmltools_0.4.0 pillar_1.4.3    base64enc_0.1-3 crayon_1.3.4   
 [9] Rcpp_1.0.4      uuid_0.1-4      IRkernel_1.1    jsonlite_1.6.1 
[13] digest_0.6.25   repr_1.1.0      rlang_0.4.5     evaluate_0.14  
```

I was able to make it work with the same hack @jobdiogenes posted here - https://github.com/r-lib/httr/pull/634#issuecomment-579873173.

**Comment by jennybc** [comment]
@terzieff You might want to subscribe to https://github.com/r-lib/gargle/issues/130 which is about GKE and we are making progress.

**Comment by jennybc** [comment]
Now tracking in https://github.com/r-lib/gargle/issues/140
