### ISSUE TITLE
Waiting for authentication in browser...

### ISSUE THREAD

**Issue by shahab3476** [tidyverse/googledrive#286]
I have been using this package for a while and it worked well. I have a jenkins job that runs a R script that does some calculation, creates a csv, and uploads it to a google drive location.

Since last week the jenkins job is broken. It gives me this:
**Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Please point your browser to the following url:** 

Clicking on the link takes me to a localhost location that does not work.
Others have posted about this that I should use the use_oob option which I was already using.

Going back to Rstudio and running it directly there also always require this prompt:
**The googledrive package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort.**

which asks to confirm the email address that I have for google drive. I can get around this by adding a line for drive_auth(email=email@com), but the same workaround does not work for jenkins.

**Comment by jennybc** [comment]
What measures have you taken to use the pre-obtained token in the jenkins context?

In the place where you're having trouble, you can use `gargle::gargle_oauth_sitrep()` to get good information on the location and contents of the token cache.

You can also put `options(gargle_quiet = FALSE)` at the top of a script to make gargle much more verbose about what's happening as it tries to secure a token.

**Comment by jennybc** [comment]
Also note that oauth tokens don't last forever. So the one that was working on Jenkins could have become invalid in some way and, therefore, unrefreshable. This generally happens through disuse or getting a lot of new tokens elsewhere (the 25 most recently obtained tokens are valid and older ones roll off the end).

**Comment by shahab3476** [comment]
I have not taken any measure to pre-obtain the token in jenkins. It is on the same server as RStudio and when I first got it working in RStudio, it worked in jenkins as well.
It has access to .R/gargle/... so that might be the place that it gets the token from.

I added the verbose option and it says

attempt from: googledrive
trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: googledrive
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache

when I do the same in RStudio, it only says 
attempt from: googledrive

This is happening when I am using the drive_upload

**Comment by jennybc** [comment]
I think you need to compare and contrast the two ways this code gets run with respect to:

  * What `gargle::gargle_oauth_sitrep()` reports: are they finding the same cache? Are they seeing the same tokens?
  * R and package versions: Are the lib paths somehow different? Are you somehow using different versions of R? Because the version of R and other packages can potentially affect has tokens are hashed, which then determines our ability to find a matching token and use it.

I think at least one of these must differ between the environment when you run this code interactively in RStudio and when this code is being run via Jenkins.

**Comment by shahab3476** [comment]
Thanks for your feedback Jenny. 
The version is the same between Rstudio and Jenkins.
Previously when using version 0.1.3, there is a authentication file created (.httr-oauth) that is used in jenkins. 
For the new version that authentication file is created under .R/gargle/... and it seems jenkins can't access it.
For now, we have downgraded to version 0.1.3 as a workaround.

**Comment by jennybc** [comment]
> For the new version that authentication file is created under .R/gargle/... and it seems jenkins can't access it.

Is it a permissions problem then? Or a different notion of who the current user is and, therefore, the default cache location?

> For now, we have downgraded to version 0.1.3 as a workaround.

It would be good to get to the root cause, though, because this won't self-resolve.
