### ISSUE TITLE
Re-wrangle stored info re: Drive API

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#29]
From #20 
> You might want to consider a two-layer request builder, like here:
> https://github.com/tidyverse/googlesheets2/blob/8caf705a92b7c0638783ce478eb0449a3a92c1de/R/gs_build_request.R#L47

> The inner layer, gs_build_request(), is very dumb and mechanical. But would work if someone really knew what they were doing and only wanted help setting base URL, path param expansion, and managing auth.

> The outer layer, gs_generate_request(), is smarter and what I plan to use! It needs to be given a known endpoint and then it looks up everything we know, checks that input looks good, and massages it into shape before calling gs_build_request().

**Comment by LucyMcGowan** [comment]
* build it out `build_request()` to mimic googlesheets2
* change how the endpoint is saved to mimic [this](https://tidyverse.github.io/googlesheets2/articles/articles/sheets-api-v4.html#spreadsheets-batchupdate)
* allow to pass the .endpoint to the function (so it is general to drive & googlesheets)

**Comment by jennybc** [comment]
This shall be our definitive source of API info moving forward:

https://www.googleapis.com/discovery/v1/apis/drive/v3/rest
