### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by bshor** [tidyverse/googledrive#293]
I'm trying to use drive_download(), which has worked for me in the past. When I use it today, it tells me to finish the authentication in the browser. I do so, and Google tells me there's "success" but then the progress bar continuously updates with no change. That is, authentication never completes. Here's what my browser window looks like:

![image](https://user-images.githubusercontent.com/468070/73210910-d65e2e00-4110-11ea-9d0b-abb7f402922a.png)

I've never had difficulties with Google authentication with any other apps, or even Google Drive in the past.

Any ideas?

**Comment by jennybc** [comment]
I have not seen this before, no 😬

**Comment by jennybc** [comment]
I assume this was an intermittent or else I'd be hearing more about it.
