### ISSUE TITLE
Unable to delete file user doesn't own

### ISSUE THREAD

**Issue by tklebel** [tidyverse/googledrive#298]
I am unable to delete a file that is in a shared folder but does not belong to me. I can delete the file via the browser. Because of #297 I'm unable to provide a working reprex, but here is some pseudocode:

```r
library(googledrive)

file <- drive_upload(
  drive_example("chicken.txt"),
  name = "chicken-share.txt",
  type = "document"
)


# move file to shared folder
...
# change file ownership to someone with access to shared folder
...

drive_trash(file)
#> Error: Client error: (403) Forbidden
#> *  domain: global
#> *  reason: insufficientFilePermissions
#> * message: The user does not have sufficient permissions for this file.


```

**Comment by tklebel** [comment]
From https://developers.google.com/drive/api/v3/reference/files/delete:

> Permanently deletes **a file owned by the user** without moving it to the trash.

Maybe this is simply not supported? Than it would be good to state it in the docs.

**Comment by jennybc** [comment]
Perhaps we are miscommunicatingn but ... it seems to make sense that one can't delete a file one doesn't own?

**Comment by tklebel** [comment]
I simply expected the API to give me the same rights as I have when browsing drive.google.com. When I do the latter, I *can* delete files in a shared folder that are owned by someone else. This makes sense to me, because all people with write access to said folder are in some way "owners".

The whole issue arose because we had a team member quit whose files I needed to take ownership of. Since you cannot change ownership of non-google files (i.e. .docx, .pdf, etc.), neither via API nor GUI, I opted for copying and them and deleting the old version. Deleting the files via API doesn't work, but via GUI it does work.

**Comment by jennybc** [comment]
> I simply expected the API to give me the same rights as I have when browsing drive.google.com. When I do the latter, I can delete files in a shared folder that are owned by someone else. This makes sense to me, because all people with write access to said folder are in some way "owners".

I would look into whether you are, perhaps, deleting a copy or deleting your access to these files. How sure are you that, if logged in as the files' owner, that the files are truly gone?

In any case, perhaps you've discovered a difference between browser UI and the API. But googledrive can only expose the features in the API.

**Comment by tklebel** [comment]
> I would look into whether you are, perhaps, deleting a copy or deleting your access to these files. How sure are you that, if logged in as the files' owner, that the files are truly gone?

Thanks for the suggestion. It seems that the files are truly gone, the previous owner does not see/have them any more. 

But as you write, googledrive cannot do anything about it, so I'll close here. Sorry for the hassle!

**Comment by jennybc** [comment]
Reading the docs for the endpoint ...

https://developers.google.com/drive/api/v2/reference/files/delete

>  The currently authenticated user must own the file or be an organizer on the parent for shared drive files.

What is your role on the parent folder?
