### ISSUE TITLE
Obtain a googledrive-specific client secret and id

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#3]
Looks like you're using the secret and id from googlesheets here in googledrive

<img width="419" alt="screen shot 2017-05-10 at 7 54 10 pm" src="https://cloud.githubusercontent.com/assets/599454/25930570/d4a77dd6-35bb-11e7-8392-11dbf408f440.png">

We should create an app/project for this package specifically. I should probably be the one to do that, using the existing account that owns the googlesheets project.

**Comment by LucyMcGowan** [comment]
Yes! I am. I copied over the full `auth` and in the process also grabbed those [here](https://github.com/tidyverse/googledrive/blob/master/R/src.R) - I agree it'd be good to have a separate one.

**Comment by jennybc** [comment]
I've provided these to you. Once you add them, I'll be interested to know how a fresh auth process goes, what the auth screen looks like, etc. In theory, this is good to go. But reality will be the true test.

**Comment by LucyMcGowan** [comment]
looks like it's working 🎉 
<img width="601" alt="screen shot 2017-05-12 at 9 56 58 am" src="https://cloud.githubusercontent.com/assets/8431897/26003837/71625e82-36f9-11e7-8e13-b47d03cd61a9.png">

**Comment by jennybc** [comment]
No, it should be other way around. Which way did you have it when you captured that screen above 🤔?

The web app credentials is for a Shiny workflow that I imagine you've not tackled yet. I haven't touched that part of googlesheets in a long while.

**Comment by LucyMcGowan** [comment]
oh! hmm I did it the way above and got the screen above. OH but seeing now it says `googlesheets` not `googledrive`. I switched them and I still see `googlesheets`  🤔

**Comment by jennybc** [comment]
Make sure to start completely afresh with respect to the token and the googledrive package. So delete or remove all `.httr-oauth` and re-build and install or re-`load_all(".")` googledrive. Restarting R is probably unnecessary but could not hurt re: ensuring that the options are truly starting afresh.

**Comment by LucyMcGowan** [comment]
ah yes - it's actually working now! 🎉 
<img width="562" alt="screen shot 2017-05-12 at 11 16 20 am" src="https://cloud.githubusercontent.com/assets/8431897/26007034/7955a0b2-3704-11e7-9e6d-b0dfd3644c34.png">

**Comment by jennybc** [comment]
Great! Done in 2b537977ea5f152d7f5652a8c53b4b3217ca3054.
