### ISSUE TITLE
drive_file() should return root folder by default

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#30]

**Comment by LucyMcGowan** [comment]
brilliant 💡 this would make `root_folder()` unnecessary?

**Comment by jennybc** [comment]
Exactly.

**Comment by jennybc** [comment]
This also gives a user an easy way to get the id of root folder. Example of usage to see folders that have root has direct parent:

```r
drive_list(q = "'0AEGh-SuuA2nTUk9PVA' in parents and mimeType='application/vnd.google-apps.folder'")
```

Maybe this should have an alias of `drive_root()`?
