### ISSUE TITLE
drive_update() deletes all Autocrat rules set

### ISSUE THREAD

**Issue by viquiff92** [tidyverse/googledrive#305]
When drive_update() is used, it works accordingly, but the rules set in the Autocrat add-on disappear. Therefore I understand the Google Sheet is being replaced instead of refreshing the content of the Google Sheet. 

I would expect to mantain the setting of Autocrat, so it can run when the Google Sheet content is updated. 

Thanks in advance

**Comment by jennybc** [comment]
I don't know what Autocrat is. As in, I don't know what it is specifically or even what general category of thing it is.

The main (only?) guarantee I associate with `drive_update()` is that the file ID does not change. I imagine that the endpoint it wraps, which replace the existing media, cannot support what you hope for.

https://developers.google.com/drive/api/v3/reference/files/update

If you need to make a more nuanced edit to a Drive file that is a Sheet, that suggests you should be looking at using googlesheets4.
