### ISSUE TITLE
drive_mkdir() interface

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#31]
This feels like it needs some work. Should take inspiration from `dir.create()` and `mkdir`. For example, there shouldn't be separate arguments `dir` and `path`. I think that should be just `path`.

**Comment by LucyMcGowan** [comment]
do we still think this? I think maybe the split between `dir` and `path` is nice so a user can input a drive id for `path`.

**Comment by jennybc** [comment]
Yes you are right. All of the functions that take a thing and a parent of the thing should be as uniform as possible. But I agree it's important to have the ability to specify them separately. But also a way to specify both at once. I think we can close this specific issue.
