### ISSUE TITLE
drive_upload overwrite does not work when type is set

### ISSUE THREAD

**Issue by pseudorational** [tidyverse/googledrive#312]
Thank you for developing and maintaining library(googledrive). I ran into the following problem with drive_upload. 

drive_upload(...., overwrite=T) will only overwrite the previous version of the file on Google Drive when type is not set. For instance, if I set the type to 'spreadsheet', drive_upload generates multiple copies of the file, i.e., overwrite no longer works. 

```r
library(googledrive)
write.csv(mtcars,'mtcars.csv',row.names = F)
drive_upload(media = 'mtcars.csv',type = 'spreadsheet',overwrite = T)
```

**Comment by nacnudus** [comment]
For me it doesn't even overwrite when `type` isn't set.

**Comment by Ihmor** [comment]
Hey,
I see similar behaviour. In my case, I am not setting the type, but store the data in a team drive. I guess that `[overwrite_hits](url)(https://github.com/tidyverse/googledrive/blob/master/R/drive_put.R#L71)`  is too strickt and searches only in my personal domain, not the team drive. Yet I am using a dribble to specify path. 

Any ideas? Do you need a reproducible example?

Phillip

PS: thanks for the great package! :)

**Comment by jennybc** [comment]
I can't reproduce this.

``` r
library(tidyverse)
library(googledrive)
library(googlesheets4)
#> 
#> Attaching package: 'googlesheets4'
#> The following objects are masked from 'package:googledrive':
#> 
#>     request_generate, request_make
```

``` r
mtcars_path <- tempfile("mtcars", fileext = ".csv")
write.csv(mtcars, mtcars_path, row.names = FALSE)

iris_path <- tempfile("iris", fileext = ".csv")
write.csv(iris, iris_path, row.names = FALSE)

ss1 <- drive_upload(
  name = "overwrite-test",
  media = mtcars_path,
  type = 'spreadsheet',
  overwrite = TRUE
)
#> Local file:
#>   * /var/folders/pv/l2mbh7j90y5_vslh_1wyqxj00000gn/T//RtmpdNuEbQ/mtcars180375b3ae369.csv
#> uploaded into Drive file:
#>   * overwrite-test: 16Zu-tSK-R_g3vVrD22zhcwgP3TFzclIc0iRLG3vr6aA
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet

ss1 %>% 
  drive_reveal("mime_type") %>% 
  select(name, mime_type)
#> # A tibble: 1 x 2
#>   name           mime_type                              
#>   <chr>          <chr>                                  
#> 1 overwrite-test application/vnd.google-apps.spreadsheet

read_sheet(ss1) %>% head()
#> Reading from "overwrite-test"
#> Range "mtcars180375b3ae369.csv"
#> # A tibble: 6 x 11
#>     mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>   <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1  21       6   160   110  3.9   2.62  16.5     0     1     4     4
#> 2  21       6   160   110  3.9   2.88  17.0     0     1     4     4
#> 3  22.8     4   108    93  3.85  2.32  18.6     1     1     4     1
#> 4  21.4     6   258   110  3.08  3.22  19.4     1     0     3     1
#> 5  18.7     8   360   175  3.15  3.44  17.0     0     0     3     2
#> 6  18.1     6   225   105  2.76  3.46  20.2     1     0     3     1

ss2 <- drive_upload(
  name = "overwrite-test",
  media = iris_path,
  type = 'spreadsheet',
  overwrite = FALSE
)
#> Error: One or more items already exist at the target filepath and `overwrite = FALSE`:
#> * ~/overwrite-test: 16Zu-tSK-R_g3vVrD22zhcwgP3TFzclIc0iRLG3vr6aA

ss2 <- drive_upload(
  name = "overwrite-test",
  media = iris_path,
  type = 'spreadsheet',
  overwrite = TRUE
)
#> Files trashed:
#>   * overwrite-test: 16Zu-tSK-R_g3vVrD22zhcwgP3TFzclIc0iRLG3vr6aA
#> Local file:
#>   * /var/folders/pv/l2mbh7j90y5_vslh_1wyqxj00000gn/T//RtmpdNuEbQ/iris1803777283149.csv
#> uploaded into Drive file:
#>   * overwrite-test: 130zcuZeg7Ljut8o50pasjdobsqhswRHf2CLPzOj2a6w
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet

ss2 %>% 
  drive_reveal("mime_type") %>% 
  select(name, mime_type)
#> # A tibble: 1 x 2
#>   name           mime_type                              
#>   <chr>          <chr>                                  
#> 1 overwrite-test application/vnd.google-apps.spreadsheet

read_sheet(ss2) %>% head()
#> Reading from "overwrite-test"
#> Range "iris1803777283149.csv"
#> # A tibble: 6 x 5
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#>          <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#> 1          5.1         3.5          1.4         0.2 setosa 
#> 2          4.9         3            1.4         0.2 setosa 
#> 3          4.7         3.2          1.3         0.2 setosa 
#> 4          4.6         3.1          1.5         0.2 setosa 
#> 5          5           3.6          1.4         0.2 setosa 
#> 6          5.4         3.9          1.7         0.4 setosa

ss1 %>% 
  select(name, id)
#> # A tibble: 1 x 2
#>   name           id                                          
#>   <chr>          <chr>                                       
#> 1 overwrite-test 16Zu-tSK-R_g3vVrD22zhcwgP3TFzclIc0iRLG3vr6aA

ss2 %>% 
  select(name, id)
#> # A tibble: 1 x 2
#>   name           id                                          
#>   <chr>          <chr>                                       
#> 1 overwrite-test 130zcuZeg7Ljut8o50pasjdobsqhswRHf2CLPzOj2a6w

drive_rm(ss1, ss2)
#> Files deleted:
#>   * overwrite-test: 16Zu-tSK-R_g3vVrD22zhcwgP3TFzclIc0iRLG3vr6aA
#>   * overwrite-test: 130zcuZeg7Ljut8o50pasjdobsqhswRHf2CLPzOj2a6w
```

<sup>Created on 2020-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I think `drive_upload()` is behaving exactly as documented (**emphasis** mine):

> Uploads a local file into a **new** Drive file. To update the content or metadata of an existing Drive file, use `drive_update()`. To upload or update, depending on whether the Drive file already exists, see `drive_put()`.

Above `drive_upload(name = "overwrite-test", media = iris_path, type = 'spreadsheet', overwrite = TRUE)` correctly moves the pre-existing Sheet named "overwrite-test" to the trash and creates a new Sheet with that name, with new data, as promised.

`drive_upload()` ALWAYS creates a new file id. The `overwrite` argument is just about what to do when there's a pre-existing file with that name.

To update the media of an existing file (id), use `drive_update()` or `drive_put()`.

@Ihmor If you think you have a Team Drive specific problem, then yes please open a new issue with an example I'd be able to run.

**Comment by nacnudus** [comment]
I can reproduce it, and I think I can refine the reprex.

* Neither type nor name specified: trashes previous file
* **Type but not name specified: trashes a previous csv file, but not a previous spreadsheet**
* Type and name specified: trashes a previous spreadsheet

```r
library(googledrive)

write.csv(mtcars, 'mtcars.csv', row.names = FALSE)

drive_reveal("mtcars")
#> # A tibble: 0 x 4
#> # … with 4 variables: name <chr>, path <chr>, id <chr>, drive_resource <list>

ss1 <- drive_upload(media = 'mtcars.csv', overwrite = TRUE)
#> Local file:
#>   * mtcars.csv
#> uploaded into Drive file:
#>   * mtcars.csv: 1YhVOGY86QKd46Ii8atCPAGHEvPSscJP8
#> with MIME type:
#>   * text/csv

ss2 <- drive_upload(media = 'mtcars.csv', overwrite = TRUE)
#> Files trashed:
#>   * mtcars.csv: 1YhVOGY86QKd46Ii8atCPAGHEvPSscJP8
#> Local file:
#>   * mtcars.csv
#> uploaded into Drive file:
#>   * mtcars.csv: 19hWLn5f7vP31bgBWq6u8MoGBjCuJw78g
#> with MIME type:
#>   * text/csv

ss3 <- drive_upload(media = 'mtcars.csv', type = 'spreadsheet', overwrite = TRUE)
#> Files trashed:
#>   * mtcars.csv: 19hWLn5f7vP31bgBWq6u8MoGBjCuJw78g
#> Local file:
#>   * mtcars.csv
#> uploaded into Drive file:
#>   * mtcars: 1jMJ3F483YzF5Ex9tr6lZkANgPQEn0LhYFf56SihKUxs
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet

ss4 <- drive_upload(media = 'mtcars.csv', type = 'spreadsheet', overwrite = TRUE)
#> Local file:
#>   * mtcars.csv
#> uploaded into Drive file:
#>   * mtcars: 1CLpwDdt5b3Vy6IHG0PYKoWkJFPu7_R2L0QKDYgX7bX4
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet

drive_reveal("mtcars")
#> Items so far:
#> 111
#> # A tibble: 2 x 4
#>   name   path     id                                           drive_resource
#>   <chr>  <chr>    <chr>                                        <list>
#> 1 mtcars ~/mtcars 1CLpwDdt5b3Vy6IHG0PYKoWkJFPu7_R2L0QKDYgX7bX4 <named list [35]>
#> 2 mtcars ~/mtcars 1jMJ3F483YzF5Ex9tr6lZkANgPQEn0LhYFf56SihKUxs <named list [35]>

ss5 <- drive_upload(media = 'mtcars.csv',
                    type = 'spreadsheet',
                    overwrite = TRUE,
                    name = "overwrite-test")
#> Local file:
#>   * mtcars.csv
#> uploaded into Drive file:
#>   * overwrite-test: 1Y0zgugT09Gf8I8VJJF6Nwonvb1tIv-CUr3OwvzyonhE
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet

ss6 <- drive_upload(media = 'mtcars.csv',
                    type = 'spreadsheet',
                    overwrite = TRUE,
                    name = "overwrite-test")
#> Files trashed:
#>   * overwrite-test: 1Y0zgugT09Gf8I8VJJF6Nwonvb1tIv-CUr3OwvzyonhE
#> Local file:
#>   * mtcars.csv
#> uploaded into Drive file:
#>   * overwrite-test: 1smS6nQkq9AMxIhXypQXg3MZoOq6K3T5wQhwDLMeOANU
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet

drive_reveal("overwrite-test")
#> Items so far:
#> 111
#> # A tibble: 1 x 4
#>   name         path           id                                drive_resource
#>   <chr>        <chr>          <chr>                             <list>
#> 1 overwrite-t… ~/overwrite-t… 1smS6nQkq9AMxIhXypQXg3MZoOq6K3T5… <named list [35…

drive_rm(ss1, ss2, ss3, ss4, ss5, ss6)
#> Files deleted:
#>   * mtcars.csv: 1YhVOGY86QKd46Ii8atCPAGHEvPSscJP8
#>   * mtcars.csv: 19hWLn5f7vP31bgBWq6u8MoGBjCuJw78g
#>   * mtcars: 1jMJ3F483YzF5Ex9tr6lZkANgPQEn0LhYFf56SihKUxs
#>   * mtcars: 1CLpwDdt5b3Vy6IHG0PYKoWkJFPu7_R2L0QKDYgX7bX4
#>   * overwrite-test: 1Y0zgugT09Gf8I8VJJF6Nwonvb1tIv-CUr3OwvzyonhE
#>   * overwrite-test: 1smS6nQkq9AMxIhXypQXg3MZoOq6K3T5wQhwDLMeOANU
```

<sup>Created on 2020-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
Sidebar: @nacnudus Everywhere that you use `drive_reveal("mtcars")`, I think you should use `drive_find("mtcars")` instead. I think "mtcars" is a `pattern` in the `drive_find()` sense, instead of a `file` in the `drive_reveal()` sense.

Thanks immensely for a full-fledged reprex for us to discuss. It makes all the difference.

I'll narrate what I see above:

* We verify that we're start with nothing named "mtcars" or "mtcars.csv" (I've run the whole reprex myself, but using `drive_find("mtcars")`).
* `ss1 <- drive_upload(media = 'mtcars.csv', overwrite = TRUE)`
  - Creates a Drive file named "mtcars.csv", an automatic name is derived from the uploaded file
* `ss2 <- drive_upload(media = 'mtcars.csv', overwrite = TRUE)`
  - Deletes the pre-existing "mtcars.csv" file and creates a new file named "mtcars.csv"
* `ss3 <- drive_upload(media = 'mtcars.csv', type = 'spreadsheet', overwrite = TRUE)`
  - Deletes the pre-existing "mtcars.csv" file and creates a new Sheet named "mtcars", a name automatically generated by the server
* `ss4 <- drive_upload(media = 'mtcars.csv', type = 'spreadsheet', overwrite = TRUE)`
  - Creates a second Sheet named "mtcars", , a name automatically generated by the server
* `ss5 <- drive_upload(media = 'mtcars.csv', type = 'spreadsheet', overwrite = TRUE, name = "overwrite-test")`
  - Creates a new Sheet named "overwrite-test", an explicit name
* `ss6 <- drive_upload(media = 'mtcars.csv', type = 'spreadsheet', overwrite = TRUE, name = "overwrite-test")`
  - Deletes the pre-existing "overwrite-test" Sheet and creates a new Sheet named "overwrite-test", an explicit name

I think the lesson here is the for `overwrite` behaviour to be completely predictable, you have to specify the `name` of the targeted Drive file explicitly. Once we request `type` conversion, automatic name generation introduces some ambiguity. The "mtcars.csv" --> "mtcars" name conversion, when uploading a csv as Sheet, comes from Drive API, not from the googledrive package.

**Comment by nacnudus** [comment]
Thanks for your annotations, which make it even clearer.  The inconsistency seems to be on Google's side, defaulting to the uploaded file name for deletions, but the automatically generated file name for creations.  Would you like a PR to document it in `@param overwrite`?

**Comment by jennybc** [comment]
> The inconsistency seems to be on Google's side, defaulting to the uploaded file name for deletions

Well, the existence check and deletion is entirely a googledrive matter. The Drive API will let you create 10 files with the same name, no problem. So we pre-emptively check for a file named `name` and if `name` is not given, we default to `media`.

The point is, if `name` has not been specified, we have to guess what the file's name will be. And when `type` conversion is used, there can be some transformation and we won't know until the upload has already been done.
