### ISSUE TITLE
Error: Can't get Google credentials

### ISSUE THREAD

**Issue by cmchuter** [tidyverse/googledrive#313]
The full code rode run was: 

```
{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Clear Variables
rm(list=ls(all=TRUE))

{r packages}
# Load packages
test<-require(googledrive)   
if (test == FALSE) {
  install.packages("googledrive")
  require(googledrive)
}
test<-require(googlesheets4)   
if (test == FALSE) {
  install.packages("googlesheets4")
  require(googlesheets4)
}
{r authenticate, echo=TRUE}
# set up to load from Google
options(gargle_quiet = FALSE)
drive_auth(email = "cmchuter@gmail.com")
gs4_auth(email = "cmchuter@gmail.com")
```

The full error code is as follows: 
```
Error: Can't get Google credentials. Are you running googledrive in a non-interactive session? Consider: * `drive_deauth()` to prevent the attempt to get credentials. * Call `drive_auth()` directly with all necessary specifics. * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```
Session Info is as follows: 
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googlesheets4_0.2.0 googledrive_1.0.1  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     knitr_1.28       magrittr_1.5     tidyselect_1.1.0
 [5] R6_2.4.1         rlang_0.4.6      httr_1.4.1       plyr_1.8.6      
 [9] dplyr_1.0.0      tools_4.0.0      xfun_0.13        tinytex_0.22    
[13] ellipsis_0.3.0   yaml_2.2.1       tibble_3.0.1     gargle_0.5.0    
[17] lifecycle_0.2.0  crayon_1.3.4     purrr_0.3.4      vctrs_0.3.1     
[21] fs_1.4.1         curl_4.3         glue_1.4.0       compiler_4.0.0  
[25] pillar_1.4.4     cellranger_1.1.0 generics_0.0.2   jsonlite_1.6.1  
[29] pkgconfig_2.0.3 
```
How can I switch to an interactive session or otherwise solve this error?

**Comment by jennybc** [comment]
This error says it all:

```
Error: Can't get Google credentials.
Are you running googledrive in a non-interactive session?
Consider:
* `drive_deauth()` to prevent the attempt to get credentials.
* Call `drive_auth()` directly with all necessary specifics.
* Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```

> How can I switch to an interactive session or otherwise solve this error?

Have you followed the link given in "Read more ..."?

<https://gargle.r-lib.org/articles/non-interactive-auth.html>

There is an explicit section called [I just want my .Rmd to render](https://gargle.r-lib.org/articles/non-interactive-auth.html#sidebar-2-i-just-want-my-rmd-to-render"). That really is my best effort at explaining this.

Have you definitely cached a token through interactive use of googledrive and googlesheets4 as `cmchuter@gmail.com`?

If `gargle_quiet` is `FALSE`, I would expect much more output, as it falls through all the other auth methods, before reaching OAuth2.

Is there any other wrinkle here re: we're in a Docker container, running RStudio server, etc etc?

**Comment by cmchuter** [comment]
Thanks jennybc! I'm new to R, how can I cache a token exactly? I did follow that link, but am having trouble understanding (there's a lot of new vocabulary). I can give it a couple more reads, but a, feeling pretty stuck.

**Comment by jennybc** [comment]
I think this might be the best section:

https://gargle.r-lib.org/articles/non-interactive-auth.html#i-just-want-my--rmd-to-render

You must get this code to run at least once, interactively, resoundingly to all auth prompts. Then, unless you are running it in some different or special context, as long as you authorize the re-discovery and re-use of those previously cached tokens, it should run successfully, non interactively.

**Comment by cmchuter** [comment]
Thank you so much, I ran the first step: 
```
library(googledrive)
# do anything that triggers auth
drive_find(n_max)
```
But this error code came up: 
```
Error in drive_find(n_max) : object 'n_max' not found
```

**Comment by jennybc** [comment]
I am hoping this is resolved now, through some combination of user persistence and better errors/guidance from gargle.
