### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by kongdd** [tidyverse/googledrive#315]
suggest adding the following functions:

1. add progress bar in drive_download
2. add timeout in all functions

**Comment by jennybc** [comment]
Progress is tracked in https://github.com/r-lib/gargle/issues/64

I'm not going to thread a timeout argument through all the functions. googlesheets4 ultimately uses httr, so it is possible to adjust some curl parameters for an individual call by placing it inside `httr::with_config()`.
