### ISSUE TITLE
drive_ls error

### ISSUE THREAD

**Issue by bllittle** [tidyverse/googledrive#316]
---
In trying to run the following code: 
GDriveExisting <- drive_ls(path="<path to folder>",
                           recursive = TRUE)
I get the following error: 
Error: Expected content type 'application/json' not 'text/html'.
<HTML>
<HEAD>
<TITLE>Bad Request</TITLE>
I had seen elsewhere a previous issue with the request to run traceback() so here is what I got: 
> traceback()
17: stop(fallback)
16: signal_abort(cnd)
15: abort(glue_collapse(message, sep = "\n"), .subclass = "gargle_error_request_failed", 
        resp = redact_response(resp), )
14: stop_request_failed(message, resp)
13: check_for_json(resp)
12: response_as_json(resp)
11: error_message(resp)
10: glue_collapse(message, sep = "\n")
9: is_null(msg)
8: validate_signal_message(message, class)
7: abort(glue_collapse(message, sep = "\n"), .subclass = "gargle_error_request_failed", 
       resp = redact_response(resp), )
6: stop_request_failed(error_message(resp), resp)
5: gargle::response_process(page)
4: do_paginated_request(request, n_max = n_max, n = function(x) length(x$files), 
       verbose = verbose)
3: (function (pattern = NULL, trashed = FALSE, type = NULL, n_max = Inf, 
       team_drive = NULL, corpus = NULL, ..., verbose = TRUE) 
   {
       if (!is.null(pattern) && !(is_string(pattern))) {
           stop_glue("`pattern` must be a character string.")
       }
       stopifnot(is_toggle(trashed))
       stopifnot(is.numeric(n_max), n_max >= 0, length(n_max) == 
           1)
       if (n_max < 1) 
           return(dribble())
       params <- toCamel(rlang::list2(...))
       params[["fields"]] <- params[["fields"]] %||% "*"
       if (!rlang::has_name(params, "orderBy")) {
           params[["orderBy"]] <- "recency desc"
       }
       params <- marshal_q_clauses(params)
       trash_clause <- switch(as.character(trashed), `TRUE` = "trashed = true", 
           `FALSE` = "trashed = false", "(trashed = true or trashed = false)")
       params$q <- append(params$q, trash_clause)
       if (!is.null(type)) {
           mime_type <- drive_mime_type(type)
           mime_type <- purrr::discard(mime_type, is.na)
           params$q <- append(params$q, or(glue("mimeType = {sq(mime_type)}")))
       }
       params$q <- and(params$q)
       params <- append(params, handle_team_drives(team_drive, corpus))
       request <- request_generate(endpoint = "drive.files.list", 
           params = params)
       proc_res_list <- do_paginated_request(request, n_max = n_max, 
           n = function(x) length(x$files), verbose = verbose)
       res_tbl <- proc_res_list %>% purrr::map("files") %>% purrr::flatten() %>% 
           as_dribble()
       if (!is.null(pattern)) {
           res_tbl <- res_tbl[grep(pattern, res_tbl$name), ]
       }
       if (n_max < nrow(res_tbl)) {
           res_tbl <- res_tbl[seq_len(n_max), ]
       }
       res_tbl
   })(q = "('1nIZ0e7joeaPQAc00D-GozfXFKtoK91M0' in parents or '1-JNMf8LW8sTmUmWl7qCkKocppw494-c-' in parents or '18Z43mSeXAk4K99WmPYdCOwhLpjgtwi76' in parents or '11sVNKdo9yDY7OMRGAxOPnH8_rvntcDi4' in parents or '1z2aJUDsE1o0C6QcjDbteQ4RXBzaEbYUS' in parents or '1UpfLD0u4UBLoB698XGLeHSo08JWORRdu' in parents or '1VgiPysNFW3VIeK95IISImKGCUlO6f8Ce' in parents or '1HmPQld3rNqu8Amtm-m-T0GMZp01oSaH6' in parents or '1cmmvxDkYwKwzrcu7KxP1Lz5I5tRVG-kl' in parents or '1VMC3V1JoyLzYFRrv5YwMIb6RdqLliJ7o' in parents or '1bTeTWFBNfiNks1Hkuublz3l_5shn_eIX' in parents or '1DG02EXOCRaw_ryoc2rX68QvrxJp8hpdI' in parents or '1YHsQ_BUt1i5QMhOS3zq4o6k5PtoiYl1q' in parents or '1zRmk1P2sEYpWA0Zc5_RiIvBUPwoQt1lk' in parents or '1_5CjskTqh-KFbesbDtcRxkBPdDvsO-Q8' in parents or '1XuzdBeoNLgZs7im_z4Ztf0TvhTbEouZ2' in parents or '16mFH_4ojpYL9RWuhGzDWtSwMD5hPGksj' in parents or '1h2NIxN3XFv2at3eFlStM7Q7cPgavdWte' in parents or '1CQ2FidqqUb0VRCU_LCqDRcxbSRIYDroA' in parents or '1Ln78mocEAeuQhNpeDvmorNdg2NMy5ou7' in parents or '1oDKfjBfgroxTVTwpz7o8tLPD5lOOtPIm' in parents or '1hmJR_0jabogORsMK5jB6uGOW6DG7LLjD' in parents or '1eWHN9wmKBOnQ2epzLQwgeVhE67G90JS0' in parents or '1my8VyVubj5pzrAnb16vqV7ctg-qcvBu5' in parents or '1AWI2tRHuEg_OFZfPrxNLbKSM8wh9EJqv' in parents or '1pc_gA--OTajGNxK6eP6op70wVImzjuKV' in parents or '1nzBD9M5AmpjYc_svlevjsDl4wzWO5glV' in parents or '1Dhf4lVWuFELzV3etWHIAacz8rSDcHC8T' in parents or '1X7OyJqQgyd_aKMejgFy5rwvNxtNUSW4_' in parents or '1KGrTMkRB-MN8Q06Hfc-nrLY4vYGbYtDZ' in parents or '1EdUkEuXo7WTuB4EvWi0cGcLpnjRKxok4' in parents or '1a49CAKX98fL2bQaiUZJkheanAjtJ3y62' in parents or '1AoUcXKY7H4OpUNmx5cHAQSDViKEaGOlx' in parents or '1kBTvKMDwvjYQqt-ClYJhiGYNPPe-XYcL' in parents or '1FIklFh1iIqEzw2EPxllcfWoBcPbDFzeZ' in parents or '15dhWrxy91GiBKADARDQ8Bu9cOx6V1-Jz' in parents or '1Xwy2NqPwcdmON0koWoAtYQu_a32WNTxL' in parents or '1FMK2Kqr9rvyUiRBf3f5mJicRlzPduF8Z' in parents or '1EB6kjtInevTB0G6AqU9iqYKhdkHTDgRg' in parents or '1jMfLRZyu-iSAoZdyq035PFnZHeA5P_8d' in parents or '1Z8gaLST4B4HX-VFaBpwXj7Uk8PkWT4sK' in parents or '19cZcEhtTIaEGr-FAKxZdxk9rvaL9T1e6' in parents or '1jYk2QCHYMpwWkf0Pd9i7gPGAmzS_kH5e' in parents or '1amoQITBFg7s8wxENCvTe4vnEpJP3qTBj' in parents or '1fB5fTCz8ddqMKEm5VkNUi9BuogjnOm5l' in parents or '12gHFP2eYTP8wBJMsVOQhJ5bITydAa5wc' in parents or '1sEiY4VS-BMg4dw156ydL15NjMmpPrc76' in parents or '1OZrYoAb8pdyXk7IZ0VZJSSO_R9pqDnfW' in parents or '1RAcqo5DJ5Da-eb0kruDdwvkPePM6u9Mn' in parents or '15rHDtpGGV3LjfnKjzEj2SI7Ym1RdqLRi' in parents or '17zvXxU1iugIQ_KiLAqXGxZZqm9o3p1YX' in parents or '1u4iwlpNJfTEEAqhlaEJ4pwuF7i1R9oDS' in parents or '1j4oM2s9qCciZNOREGHiOBphWLvhwG7q_' in parents or '1HULLnjAD2cSYGK1Y_F_-bcEi44y48tLS' in parents or '1BMOBnk6uw-ILxcvk_NvLI_vZwuY0xG3b' in parents or '1qB8th3zhO2gn1z3peHJTO5nnMy0-WVAt' in parents or '1M1lUK8oqkujkIJBwXOs8JMMzZV87fwBl' in parents or '1_uQ4FEGZbEBiSNynrQ9XRvqGp-v9oHIe' in parents or '1Vg1c3kK5wAACgJUzi3xquN-JXmzTS1Jg' in parents or '125re7I3wIjE2f1oXVb34z00ctoOsIuYT' in parents or '1WlreQKB37Y2fIWkoo4MVPOtyY7gp8SXI' in parents or '1iUT3XLx_A7gJ6a4SFiEDohkV7LyO8Wyc' in parents or '1rr3cTTAtHEdBimm6h9MLcWKArJ9kr20z' in parents or '1rMtBrhp95193fEvPx9UbvJ-kA4m1DREk' in parents or '1izN_JxtrmaPOjLTKbuLhHgmkvqpzk6-Q' in parents or '16s_a5fsuwP9R0po1cwWy1H4ySr2gqR18' in parents or '15xi-MbmLN0g5qi1CqnmdosgGrVS0EDf7' in parents or '1XnPO9j2xhzJUy4wAnj3hkjvm3doquJbi' in parents or '1ipj_Iqx-i8Xzns6grDk1ZK5H90b4PBRH' in parents or '197j9yl-4UsFHUp7Vg6x-iDKO4ZfgEDyE' in parents or '1hxdv5aVVDh0lek0tsPGp87T-iz33O3a6' in parents or '1xtRVxSOtVrUjP6f17Wu3vuXeAIfcRDwC' in parents or '1YzInzoVz55E1ZtaNejSatt13Hu1ZaD4l' in parents or '14IjvyJAhrNeao2gbaIe_UAV4th_er72M' in parents or '1JbUtM7sxHdYXK9H0eYOhP0xQ2gelq5le' in parents or '16RrrxcinDfCf2urHYOr0OOAaKEZXn1IY' in parents or '1cFcDnQbGEnfjzVW1uUcuMfPID7pCSsVs' in parents or '14Rrc62JNb5Z2EDYASk7umSYaI0-hsiiX' in parents or '1cXW_Q0oHY80lGZNpkv5_PN8-ThhXesD-' in parents or '1lzaowDXqjLeaDltyfvqSw9Z7gsxlCi8p' in parents or '17d7Xn8741H1KoY9WmCDmyViMYAxh_lLs' in parents or '16jubflnTiYJGwkMsqkYr16JwSisyqPnT' in parents or '1gEe5aSdlVxEw-8mw0Q7J3xdHAhMazs8X' in parents or '1R4vvJQa7cvUfFfZpXJo9YthwjaABMXfa' in parents or '1qVOc2s8HMQmxFBed4zMNTWo5jBROP49_' in parents or '1_YZxTiOkT4XER5zyTECKO5YH54cpfXVF' in parents or '1v5Ki9eC_UZMqeNqcijYn6j72o8FM-lZP' in parents or '1UrNi1gLS76atkxBbBsS1FadrSNNyobb4' in parents or '1OfP6vr7Gk7KKG7ynJ7yeM04C5I5RpN8V' in parents or '1IRklkdNV-cldz4BoXHn13kDcXbPQOnl9' in parents or '1-zVoA10ap33UXA1pr9x7Q0UitW0tt1Fj' in parents or '1VBG47xUY6D6yvrxyOyZgRLh-qA3yZ3_M' in parents or '1elh5pVr383wpW6QsPDENX3hpwaCKvSX1' in parents or '1_9r6bkBPN1MQyfzf35egsRLBELiN9nd9' in parents or '1ObeW-u4fU1tJQeZpDK02j0U_z-_XGLI1' in parents or '1okXNQhwEcgE0yuJJ7WpurQ-Do3JsS2cR' in parents or '1E-Uz2uSW2YsxEOKcc451k-QJW2sqQ-LJ' in parents or '1yZLAuYKLUtE3kAgS1gR6rpEDyTRfE5Ay' in parents or '1Zr2wO7cOdzaovOKHL5erUbTHrwd__dcp' in parents or '1jw0cPncewN0BHDU0yfEulHk0zCz7AH6O' in parents or '1VgNclji0CDAPdESvpXZd08A3dcxFe1Rk' in parents or '1aJD7dPw2ieIOZkr4YNAeOKMD0R4gGfXx' in parents or '1K6yqOFhUpRzTfU_KUpIUFr0yq5fHB2CZ' in parents or '1KN-rlK73DWKQ2PTc6vTojThS2VGj_xTI' in parents or '1Vh4Q4-dlFaG8Xy4ZVYva3cJ2J6sdILaM' in parents or '1OrGWe72eFXL0aLIf38xI-RVxJL-5YuD5' in parents or '1oTh2ltSdXnJYhTmTlzJEno4-PKXlaDDx' in parents or '1uL_ksQOnm_t8KyudMc0chpofZ1e0H9JK' in parents or '1SdCcz-m3VLanYJ9jQJDMr6CL49mkIGVy' in parents or '1edT9cOwn4nXWUePf-4nboy8EaBZ_9fWu' in parents or '1BcG1tAFp__2S25gn6BmgGiVo1Kn6U_wp' in parents or '1_U_HQtjBtNu6hfoCR7YUwwBqkk7flGSI' in parents or '1ujTMXq3DBu5mdkg-nls5mIKOmhliY-et' in parents or '1B2kBwQQdo6iVQL_orgdhNh1D587DPQLe' in parents or '13iiXaq8t9l5yYO_n2OjK9hqfTZB-kWSX' in parents or '1gh-6R-DhOEAXWLl7NUrigQG9h6pulzsN' in parents or '12YZDR6dNAylL8CuxPtzsJvdR7jmKmVBX' in parents or '1UpLKQXHDDJtj5sKvUQmhEANT4YRuSC3V' in parents or '11nZQB2ZOfs-8CYjfthxMuIEKG8W3_lSO' in parents or '1R-SR08qBJ0r4-kJrAYSDz2HvMRjGbVMB' in parents or '1YwRJJzYGYnAfWwTup2yvoGq2AQ83gkPT' in parents or '1_wyocn8rn4LCzViX7bwShXKdf2h0eS4g' in parents or '1O4g6plvMHmAbhF7xOQ0D2y4vnKRGHZj6' in parents or '1OhCH7jecOGb4Y9WOy5TNKXgfluwHsd1c' in parents or '1hdJMvRp4E3hNafb_YnNjB8t8HI-RSh8p' in parents or '1EdrQnk0zUZYNVrL_CuyfWbDFPwKppJZJ' in parents or '1922WR19iukoxWqRoIrGoqkSidHrdB0nc' in parents or '1C0n5Qg_uS-jQMPGJV1HAeq5k97x4skwM' in parents or '1D0ogF5L2Vc_Rwht3iMn2yYGLWmOy7rIh' in parents or '16IOEfGmPFGBtO1hh2IPiYzx5xQBh3P2h' in parents or '1GIskFq8oP4lxCXbFyEpz4OwsixAcsjHv' in parents or '103F-NjrnWK8gbzLGS6Ta-qcKIEFmHTm0' in parents or '1bgvPdKK3ecm81LdHUst1GMXyw4Vjyp4f' in parents or '1JarJLME_iYWAxfuSj7em-22gMVSs4bMh' in parents or '1xEWL4Uqg-_9gTDwsndnb3S--tKbP0UVe' in parents or '1LuxHvMpirhTTnFVFbnI0IIT9ctwGTHmU' in parents or '1sTg4g2kaviwrLcwRht3xxjh8PUTbRzSd' in parents or '1z4oCQyvVpHQmNV_-qwr8Ij6XWl4UVFY1' in parents or '14wowj7q0ly9bsdOSnZnzU_BDhpG_d9vS' in parents or '13GcrH1ISCfUYUa_QoeqKd42YMobr9RE8' in parents or '1gACNm2N3TlPkOFg-8GcDFifuyzjsUFKg' in parents or '19jZrp9_M8qdGRA9NgX4StkcYob15Trg7' in parents or '1lzzGZS0DadNmNW6uxDCxwBCG6Pz13yCp' in parents or '14I7Vy1gJcwM_hqZ35Y-oXM5u5TV-7pje' in parents or '1CtFiBtZFVg1ANGCzmCrMZ6VgxWh2x4P2' in parents or '1iBuJL_BjMEBy4sQp2_y7-jlw7XCd2OOH' in parents or '1jauYgzpHOKfVbSrINlYsi7oKQqW3_GCT' in parents or '1QZ_pYL4LdjQnalddVnXnUqZAAKP3K5oD' in parents or '1rkp9DpPIa5Mh9-Ty7QrHb-9D8UKw6ijm' in parents or '1IuMqNLKOZGMc3Tzv8lkttfqMSQFpIo_G' in parents or '1qWMcAXSqaAxogzNQ_8wJoSJ6au9_zac2' in parents or '1l2e1h9V80KGSPBt-VINbJjho8XNOuSmw' in parents or '1q3SmTsYpZTBNdCZYgQKrebMGq4fiv6E0' in parents or '1FMSoCMkxyjaQD0RjhlqXJQSYCYkqFj5V' in parents or '1Rh1oltd7VIe4hZ11LkkuCAcRrMH2_db1' in parents or '1WEV1RlCV3DWmbh17H3VSwBL_9nnZ8b5t' in parents or '11vKLeTldS4JQ-Q4AmFi0Ad446JuwUAl0' in parents or '1lv0wU8FfjTwOzWkqMFwLaYIyDz9vSrCc' in parents or '1ufH89duQ1UyShEyakYVsUAWBsa1J7C7K' in parents or '1NGkyUvuAMCzT8FSFyDmiTVCqGskhjYZo' in parents or '1mq0R9YF12KLbQXiasPoyORMST0ZxiZRH' in parents or '1Xk9qr2z4o5rcK6NsA082KMluNF9VWymn' in parents or '1sV3064eztcCtbvzt9EM53iMyn-IsoHiI' in parents or '1-JHuCGc1D_1lQAs4fKuJ4EVTqvH9Cjio' in parents or '1Pw5R1jvjsUqLRNFY_zCSrIuFoxfUtibl' in parents or '1QJumLtcB7kdBLGD7MXr7u7F9c23KufRx' in parents or '1HFF9FUS5taGm7N8b2yJZy8On7eG8sq8b' in parents or '1CTDGb5uVpksyCtKlva77ZzpfLBY6sK5M' in parents or '1r6b5xlGoKT5lSPj8MWBD1kEbekP1bcjy' in parents or '1g6cUB9MXTEu9rZei-7BpTlKgMY2TFCUj' in parents or '1gyquZzB9ESeP0qbozGvyo0Jmbqpl8cDj' in parents or '1_eFuYLh8j5GVpPVVo6IqImIU66TnJ_x-' in parents or '1ULYF0AMnwlzadNVwf3wVx2L6eOmT7Rxk' in parents or '1gVytg6_JU0i4tuw4_L9eBEB1_fi42BrO' in parents or '1BW2ZEyhrcGNm6sz-JunZOObh1G1F15w_' in parents or '1msWRQCE43-GtSBNOD3VHzg4JNd_6IqKl' in parents or '1lTwKN0ZIsyERYz61DZ2KresqWuxks_TR' in parents or '1yLU-0NHYPUdz_eDkoPGRB3X5QfGwoJG6' in parents or '1X25vxEY-83QIoWHoVuRQENbUhFL5WkGI' in parents or '1ebjhpoNnyMvxFC3piSSb091P4A1cZv7T' in parents or '1Na67f9Z68zZTAY_5t4Ns-1ujKHbbAnPd' in parents or '1AGdfWRypvDtiqTVoIz83jLOFHphmLmxc' in parents or '1WhM3v04YHBxn4XOZ3lzP4DsU5xGYPv0p' in parents or '1N45I9dT0Cihie-DEyQDom5_qSE9gj2jD' in parents or '1fbd-o3rYd78isQCP5McgOcZSwVw_4gJJ' in parents or '1659DMmHo4ScNnQW3lpyEHSczaduhzODF' in parents or '1TfDNLgYAn68TdOJTTMELYBl1JZCm1VuC' in parents or '1_r7EdhGlHF7FaYh4KjW2qmSLZ1o2e1a1' in parents or '1q1ruym7a_uuu7McaWcMJA7p4j0wOcCdM' in parents or '1uV7yfTeyprNO2NxErTSiFShTaIN0jDeM' in parents or '1isVd_LaDMXviDWhfgJTGJnqFVSAni_pt' in parents or '1qUoRVkVHRbQ6Io0yg8q1SDOXssnugRIR' in parents or '1xcI0WemDA_ySJF5pX4xrU2-8vfMgVJVl' in parents or '1i8x2FvUAO251gRki_e-Wbb4sxexzZ7mh' in parents or '1alGcjY4cp5PegYKH-AT2mDeMAsMwN_HP' in parents or '1r3bUDdbtnY81rZhW_txq_Cfv5IaHe8UO' in parents or '1eYVjvFelIIWwNSHO2GxwS_K060R0k62x' in parents or '1e4VP-wXlGVTEjZykNY0HpbvMfY1IP9cJ' in parents or '1q73xk5sVZzlIoe0Htbz3mB5eXzwLk7Nx' in parents or '15FBZeYUtbLdbxAq0nXAw40bK7heBpadi' in parents or '1xgYfD0hiBEQYp9rtP1WrE6vbTH14dRvj' in parents or '1yOA_XXg1Ccp3MjHqAdAHtF3DabQW4juD' in parents or '1iTZr0X_TwOuWI8UORoLeubJmG9yWhf9H' in parents or '1zagsr2lgSJ2dHOdHMAUMngbzIa9b-KBx' in parents or '1akYylNRo9c6sAsaGwZ9reEsZNjU3FArf' in parents or '1aB1OyQVVWHsd4c73sC3s48yOtcuXjBs2' in parents or '1SxLjDt9rnX7dSkMGOzU32C9gVYB0v4wl' in parents or '16np6IoH9tcBbl9E0xNjEkVTXdhCS_lHY' in parents or '1nwt1PNSVgG_FyAEofk-8JX80IOXsn7Ax' in parents or '1lZfEbwmwYZs3AmQVUI61cPGlrOp31BJ0' in parents or '1CP99qfqYKsTg920nStE0EdmKm0_BkqmI' in parents or '1HcfwjgPoIHxVI9k_srP8NzGAZcaA2OrO' in parents or '1L8TvH0KKaDReu_vZMuLbMAaTnrHWzjr0' in parents or '1fcykH6WWtLkjdrKbGX10hFtGZs35YmAY' in parents or '18OBdRM9L0Fq_gI5pFbkiZgBo1cMRTc72' in parents or '1Vfdzij0X6C0BHHP37jqY6kRQKfENOpc7' in parents or '1ipMZBiJyJzimYi7YTfwA2Bin-tllKkil' in parents or '1_ozEgyIbHda8Ld-m0AX4cFdD-pE1JPDa' in parents or '1i9PSKgk2kdJc2BzHzmA6gadUzZCimkzR' in parents or '1N4gv7eh4xtmE-C8UJefEuvN_gzDR4TWI' in parents or '1sr9vX6Zbuas7Nj_yBkvKpwuHa8T6jjSj' in parents or '1erCWzhIlG8oMA-cBqBBzBqX0rv3E6_ek' in parents or '10gG-49Gx_6GeeoaJKvxxG7jmoXznXVi2' in parents or '1h4isspAmU1-Z4Ln-vKRQbo1b9bY3-710' in parents or '1AgeD-fBXOIPUTNTs9M5-f0OJ7_MbCD0a' in parents or '1Cp7CLJG5L-vB6__21qUzoDlaogzJnZMD' in parents or '1ep9rrPS9QE5uefS0BV6zE4OOmrBeQeTc' in parents or '1L6zJde_seCSDjAlk3Ha4NNaK7klY9reD' in parents or '1aZA7PjHS8y-XIFDlHby-8eN9OgRKtqFJ' in parents)")
2: rlang::exec(drive_find, !!!params)

**Comment by jennybc** [comment]
What is your goal with `drive_ls(path="", recursive = TRUE)`? Specifically what is the intention of specifying `path = ""`, i.e. the empty string?

If you want to list your Drive, just call `googledrive::drive_ls(recursive = TRUE)`. This can be sort of slow, but even for me, with >1000 files, it's not that bad.

**Comment by bllittle** [comment]
Hi,

The "empty string" is not empty in practice, but since I am not the owner
of the folder, I wanted to minimize the possibility of
inadvertently providing access the information in the folder. It appears
the "placeholder" I'd put in the place of the actual URL to indicate that
has been stripped.

But the objective is to retrieve the data about the contents of the folder.
I placed 12 subfolders, 213 subfolder distributed amongst those, and 233
sheet files distributed amongst the 213, thus the recursive=TRUE. In our
experience, some of our audience will not follow directions and likely will
have made copies of some of those files to make edits, so we'll need to
reach out to them to manually process data that will likely not be in our
intended format. Of the rest, I'll use the modified dates to determine from
which I need to extract updates.

I had first tried path="our parent level folder URL". Then I tried creating
an object first: drID <- drive_get("our parent level folder URL", verbose =
TRUE) and used drID as drive_ls(drID, recursive=TRUE). Finally I tried path
= as_dribble("our folder URL"). All these methods took several minutes,
then returned the same error message.

**Comment by jennybc** [comment]
Without some code I can run, it's hard to say.

But as your original error message shows, we are forming a very clunky search query in the background (all those `or` statement about a certain ID being in `parents`). The Drive API does NOT support recursively listing a folder. That is implemented by googledrive. So one theory is that you've just got too many files / too much recursion going on and the request that we create hits some technical limit.

**Comment by bllittle** [comment]
Thanks for the feedback. I can break down the loop a bit to perform the
recursive operation on the 12 division subfolders -- that would cut down on
the recursion and total return for each step quite a bit. I'll try that and
let you know. I've encountered odd technical limits previously -- in one
previous project using a similar technique, I'd reach a maximum number of
requests allowed per a certain time period so ended up putting in a counter
which would trigger a pause in the loop when the limit was being
approached. I didn't get a similar Google request error this time, but it
may be masked in some way by the recursion.

**Comment by jennybc** [comment]
I have other suggestions for the "too many requests" problem. The dev version of gargle, which googledrive and googlesheets4 use under the hood, has a branch that automatically handles the retries and backoff.

Your error smells more like something else, such as the `or` statement has simply gotten too large.

**Comment by bllittle** [comment]
Just to close the loop on this, when I only get the first level of folders at the "parent" level then loop through each of those to get the subfolders and files within each, it works fine. So, although I didn't do enough experimentation to find the limit, it does appear to be an issue with the length of statement generated by the recursive operation.
