### ISSUE TITLE
Error: No method asJSON S3 class: form_file

### ISSUE THREAD

**Issue by wuc66** [tidyverse/googledrive#319]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

get the error

```r
#Googledrive oauth
library(googlesheets4)
library(googledrive)
library(httr)
options(httr_oob_default = TRUE)
drive_auth() #email

## create .csv files in Home directory
write.csv(DM, file = "DM.csv", fileEncoding = "UTF-8",row.names = FALSE)  

## upload file to My Drive
drive_upload("DM.csv", path = as_id("1xaTIUMdiEQcd2W9g11ATolPa8oI2tGD4"),name = "DM",type = "spreadsheet", overwrite = NA)  # "1xaTIUMdiEQcd2W9g11ATolPa8oI2tGD4" is googledrive folder id
drive_upload("DM.csv", path = NULL,name = "DM",type = "spreadsheet", overwrite = NA)  # path = NULL
```

**Comment by jennybc** [comment]
I cannot reproduce your problem.

``` r
library(googlesheets4)
library(googledrive)

drive_auth(email = "jenny@rstudio.com")
gs4_auth(token = drive_token())

write.csv(head(iris), file = "iris.csv", row.names = FALSE)  

folder <- drive_mkdir("test-folder")
#> Created Drive file:
#>   * test-folder: 1iQ-ULUCbpqWj1dnpbJolVOatKRZ7122-
#> with MIME type:
#>   * application/vnd.google-apps.folder

drive_upload(
  "iris.csv",
  path = folder,
  name = "iris-test",
  type = "spreadsheet"
)
#> Local file:
#>   * iris.csv
#> uploaded into Drive file:
#>   * iris-test: 1zOuf_f5GA8HeFiMJ8QusZ-PgWk82podLV9tuSc6hYfM
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet

drive_upload(
  "iris.csv",
  name = "iris-test-2",
  type = "spreadsheet"
)
#> Local file:
#>   * iris.csv
#> uploaded into Drive file:
#>   * iris-test-2: 1NTnvlmWFW2KTOUc5ESINeeyRNEWOzp3b-oGCDECOVKU
#> with MIME type:
#>   * application/vnd.google-apps.spreadsheet
```

<sup>Created on 2020-10-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

Please notice that you should be able to run my code:

  * I use the iris data, not `DM`. I do not have `DM`,  only you do.
  * I create the folder I'm uploading into. I do not have access to write into your folder with file ID `1xaTIUMdiEQcd2W9g11ATolPa8oI2tGD4`.

Can you make your problem happen with code I actually run?

**Comment by wuc66** [comment]
Hi Jenny,
    Thanks for your reaching out. I reproduced your code, and  It worked.
So I closed the issue.
     I will try to find the reason that caused the error.


> library(googlesheets4)> library(googledrive)> > drive_auth(email = "chunyan.wu@roche.com")> gs4_auth(token = drive_token())> > write.csv(head(iris), file = "iris.csv", row.names = FALSE)  > > folder <- drive_mkdir("test-folder") # create a folder in MyDriveCreated Drive file:
  * test-folder: 1DZcjItYJO9AVJ8le1QSve04LsrE85szz
with MIME type:
  * application/vnd.google-apps.folder> > drive_upload(+
"iris.csv",+   path = folder,+   name = "iris-test",+   type =
"spreadsheet"+ )Local file:
  * iris.csv
uploaded into Drive file:
  * iris-test: 12RMgfdK5VP3MPYREgSiicwQ1Mxf4ReWETXYnMFs5RnU
with MIME type:
  * application/vnd.google-apps.spreadsheet> > drive_upload(+
"iris.csv",+   name = "iris-test-2",+   type = "spreadsheet"+ )Local
file:
  * iris.csv
uploaded into Drive file:
  * iris-test-2: 1TUPBlJwLkQVOAkPBHBtre4Bcjxg11cwPMNtNnfZVBgo
with MIME type:
  * application/vnd.google-apps.spreadsheet

>

Kind Regards,
Chunyan Wu
Data Manager
Product Development Shanghai, China
4th Floor, Building 11, 1100 Long Dong Ave, Shanghai 201203
Office:  +86 21 2892 2649 <http://0>
Mobile: +86 18817226393
Mail to: chunyan.wu@roche.com
Upcoming OoO:
Sept.30th - Oct.8th (National Day Holiday)

**Comment by jennybc** [comment]
Ok. Let me know if you can reproduce and then we can look into it. Otherwise, carry on!
