### ISSUE TITLE
Save a token to be used instead of prompting the user to use a pre authorized account or obtain a new token

### ISSUE THREAD

**Issue by dollarvora** [tidyverse/googledrive#320]
I'm tring to source a R script into another R script, the original script accesses a list of files using the drive_ls function and then downloads the latest file using the drive_download function

The script works fine without any interruption when ran using my local machine, but while I try to run it using a remote desktop its always throws the following prompt "The googledrive package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort."

I'm wanting to have this script run using the task scheduler so that I don't need to have any sort of human intervention

Another part of my script accesses the googlesheets4 package and even it throws the same prompt while using the read_sheet function

Is there a way to save the token of an account that I've already authorized and load it to the environment to get rid of this prompt ?

**Comment by jennybc** [comment]
Please read:

https://gargle.r-lib.org/articles/non-interactive-auth.html

You can probably get by with just reading [Sidebar 2: I just want my .Rmd to render](https://gargle.r-lib.org/articles/non-interactive-auth.html#sidebar-2-i-just-want-my-rmd-to-render), which is essentially your scenario.
