### ISSUE TITLE
Feature Question

### ISSUE THREAD

**Issue by ian-adams** [tidyverse/googledrive#323]
I have a one-off project to download all files (of the same Google doc type) from a specific drive folder. I've searched about a bit, and have successfully used the package to generate a "files" object containing a list of the 199 files within the Google Drive folder. But I can't seem to get the drive_download function to download ALL the files, just one at a time. I'm wondering if I'm missing this functionality somewhere else in the package? Or perhaps this is a feature that is easier than I'm making it out to be?

**Comment by jennybc** [comment]
`drive_download()` just works with 1 file at a time.

For the time being, your best bet is to use one of the examples I collect in an issue about "missing workflows":

https://github.com/tidyverse/googledrive/issues/123#issuecomment-508962300

https://github.com/tidyverse/googledrive/issues/123#issuecomment-563484927

**Comment by ian-adams** [comment]
Thank you Jenny, those look promising. I can get it to work smoothly right
up until the `walk2` call, and then I get an error out of `curl` saying it
can't open the first .docx file. I'll continue following the package to see
what else develops!
______________________
Ian T. Adams

University of Utah
Department of Political Science <https://poli-sci.utah.edu/>
Ph.D. Candidate

Current CV available here <http://iantyleradams.com/ianadamscv/>
Google Scholar Profile
<https://scholar.google.com/citations?user=g9lY5RUAAAAJ&hl=en>
https://ianadamsresearch.com/

**Comment by jennybc** [comment]
Hard to say what's wrong without more information.
