### ISSUE TITLE
Error during authentication

### ISSUE THREAD

**Issue by ctgrubb** [tidyverse/googledrive#325]
I can't get googledrive/gargle to authenticate successfully. I am running Microsoft R Open 4.0.2 on Pop!_OS 20.04. I have tried all the solutions I can find.

I don't have anything blocking the needed port.
I have installed libcurl4-openssl-dev and libssl-dev.
I have tried both with and without httpuv, with the same result.

My gargle is 0.5.0 and googledrive is 1.0.1.

```r
library(googledrive)
options(gargle_quiet = FALSE)
drive_auth()
```
This yields:

trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: googledrive
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
initiating new token
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort

After selecting the google account I want to use, I get:

Authentication complete.
Error: failed setting cipher list: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
Error: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html

I am trying this in an interactive session. I have tried googling the "failed setting cipher list" error unsuccessfully. I found some people getting similar issues with curl, but I couldn't find any solution that applies to my OS or to R/googledrive specifically.

Any ideas?

**Comment by jennybc** [comment]
I don't want to ignore you or leave you hanging but, yes, I'm afraid your problem report is rather unique. Which is generally not good. So it seems likely that it is something specific to your setup.

**Comment by ctgrubb** [comment]
I figured out what was going on (was actually having a lot of other issues also). I somehow did not have curl or httr installed. I don't fully understand how this was achieved, as googledrive was installed using install.packages(), which should make this impossible, but it somehow happened.
