### ISSUE TITLE
Feature request: Use googledrive::drive_share to restrict ability to download files

### ISSUE THREAD

**Issue by vnijs** [tidyverse/googledrive#326]
I posted a question to Rstudio Community a few weeks ago (link below). I believe the googledrive package does not currently offer an option to restrict ability to download. 

https://community.rstudio.com/t/use-googledrive-drive-share-to-restrict-ability-to-download/93313

I can go into my google drive and select this permission manually (see screenshot) but it would be nice to have access to this setting from the drive_share function. I see references to canDownload in the github repo for googledrive but the API documentation linked on GitHub don't seem to mention it. I also tried canDownload as an argument to drive_share but that resulted in an `unknown parameter` error.

It would be a useful feature to restrict download through the googledrive package

![image](https://user-images.githubusercontent.com/2998956/107989717-b271c280-6f87-11eb-9f34-18f56a0629ef.png)

**Comment by jennybc** [comment]
I'm about to start a big update and I'll look into this in due course.

**Comment by jennybc** [comment]
This is already possible using `drive_update()`.

``` r
# https://developers.google.com/drive/api/v3/reference/files/update
# copyRequiresWriterPermission  boolean
# Whether the options to copy, print, or download this file, should be disabled
# for readers and commenters.

devtools::load_all()
#> ℹ Loading googledrive

x <- drive_upload(drive_example("chicken.csv"), "chicken-upload.csv")
#> Local file:
#>   * /Users/jenny/rrr/googledrive/inst/extdata/chicken.csv
#> uploaded into Drive file:
#>   * chicken-upload.csv: 1UHn8qZra7tanmjqfiIRaZ1VoDVKqMlOa
#> with MIME type:
#>   * text/csv
drive_share_anyone(x)
#> Permissions updated
#>   * role = reader
#>   * type = anyone
#> For files:
#>   * chicken-upload.csv: 1UHn8qZra7tanmjqfiIRaZ1VoDVKqMlOa
x$drive_resource[[1]][["viewersCanCopyContent"]]
#> [1] TRUE
x$drive_resource[[1]][["copyRequiresWriterPermission"]]
#> [1] FALSE
drive_browse(x)

x <- drive_update(x, copyRequiresWriterPermission = TRUE)
#> File updated:
#>   * chicken-upload.csv: 1UHn8qZra7tanmjqfiIRaZ1VoDVKqMlOa
x$drive_resource[[1]][["viewersCanCopyContent"]]
#> [1] FALSE
x$drive_resource[[1]][["copyRequiresWriterPermission"]]
#> [1] TRUE
drive_browse(x)

drive_trash(x)
#> Files trashed:
#>   * chicken-upload.csv: 1UHn8qZra7tanmjqfiIRaZ1VoDVKqMlOa
```

<sup>Created on 2021-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by vnijs** [comment]
Just wanted to say thanks for this great package @jennybc. Your suggestion to use `drive_update` works wonderfully!
