### ISSUE TITLE
Token becomes invalid after several uses

### ISSUE THREAD

**Issue by christopherkn** [tidyverse/googledrive#327]
I'm using non-interactive authorization to access google sheets with the following code:

```r
gs4_auth_configure(path = "path to .json")
options(
  gargle_oauth_cache = ".secret",
  gargle_oauth_email = "my email address"
)
gs4_auth(email = "my email address")

setwd("a different directory")
files <- list.files()

google_data <- read_sheet("sheet URL",
                          range = "SheetName!A:A",
                          col_types = "c")
```

I believe the first time I ran this, it actually required interactive authorization, but after that it always worked non-interactively. I copied the entire project folder over to a remote server, where it was happily running for several days before Friday 2/26/2021, when it resulted in the error:
```r
Error: Can't get Google credentials.
Are you running googlesheets4 in a non-interactive session? Consider:
  * `gs4_deauth()` to prevent the attempt to get credentials.
  * Call `gs4_auth()` directly with all necessary specifics.
See gargle's "Non-interactive auth" vignette for more details:
https://gargle.r-lib.org/articles/non-interactive-auth.html
Execution halted
```

Going over to my local copy of the project, I get the error:
```r
Unable to refresh token: invalid_grant
Token has been expired or revoked. 
```

The only search result with that error is: https://stackoverflow.com/questions/58296089/r-gmailr-how-to-re-establish-original-oauth-after-blastula-install-oath-overwrit

That person seems to have found the solution to be adding `gm_auth(cache=".secret")`, something my code already has.

I've done my best to heed the advice provided in the following links (and many more), to no avail:
https://github.com/tidyverse/googledrive/issues/239
https://stackoverflow.com/questions/60507013/gmailr-without-selecting-a-pre-authorised-account-in-r
https://gargle.r-lib.org/articles/non-interactive-auth.html
https://gargle.r-lib.org/articles/get-api-credentials.html#service-account-token
https://googlesheets4.tidyverse.org/reference/index.html#section-auth

Did something happen last week that is causing this?

**Comment by christopherkn** [comment]
I edited the code so that the working directory didn't change and that seems to have fixed the issue.

**Comment by jennybc** [comment]
```
Unable to refresh token: invalid_grant
Token has been expired or revoked. 
```

That sounds like a token that can no longer be refreshed. Why might this happen? It can happen if you go a long time without using a token or ...

> A specific Google user (email) can only have a certain number of OAuth tokens at a time (something like 50 per OAuth client). So, whenever you get a new token (as opposed to refreshing an existing token), there is the potential for it to invalidate an older token. This is unlikely to have any practical effect for a normal user, but can be noticeable for someone developing against a Google API or someone working from many different machines / caches.

(quoting from https://gargle.r-lib.org/articles/troubleshooting.html)

So perhaps your cumulative acquisition of Google oauth tokens eventually made this "fall off the end" and become invalid?

I'm commenting because I'm not too confident that this working / not working / working again had anything to do the working directory business.(But I also believe it's better to write your code without futzing the working directory.)

**Comment by christopherkn** [comment]
I'm 99% sure that I didn't run out of OAuth tokens because this is the only circumstance in which I'm using them, and I only ran the script a couple times a day ever.

The only other clue I have is that I had a .secret folder in my project directory (the working directory for the script), and then ended up with a .secret folder ALSO in the "a different directory" directory that the working directory gets set to after the initial `gs4_auth_configure()` and `options()` functions are run. My thought is perhaps that because something gets cached in the "a different directory" directory, and then when the script gets run again, it is looking in the project directory, it runs into a problem. The reason I'm confused about that being the issue is that I believe that the script ran successfully several times over the course of a couple days before it finally failed. 

But the fact that editing the code so that the working directory doesn't change seems to have fixed the problem points toward that being the issue.

**Comment by christopherkn** [comment]
Interestingly, the .secret folder appeared to be empty, whereas before (when the authentication was working) it had a file in it.

I ran a local copy of the script (where I got a slightly different error), but then was able to get it to interactively authenticate via my browser. Before the successful authentication, the .secret folder on my local machine was empty. After that, there was a file ("ORG file"? whose filename is a long series of numbers and letters followed by an underscore and my email address) in the .secret folder. I copied that file into the .secret folder on the server, and now the script works again.

This is the only script I use that uses an OAuth token, and I only run it once a day (when it's working), so I can't imagine I'm running out of tokens. I'm very confused about what's going on, so any ideas a greatly appreciated!

**Comment by jennybc** [comment]
> from the cron job log
> copied the entire project folder over to a remote server

Let's talk about these things. In this setting, I *strongly* recommend using a service account token.

https://gargle.r-lib.org/articles/non-interactive-auth.html

https://gargle.r-lib.org/articles/troubleshooting.html

If you're going to use a user token created and cached on machine A, then move it over to machine B, I would also check whether both machines are using the same package versions, especially for everything in the googlesheets4/gargle stack.

**Comment by christopherkn** [comment]
Unless I'm completely misunderstanding what a service account token is (which is completely possible. I don't use APIs hardly at all and have really struggled with all the documentation for this non-interactive auth stuff), I'm pretty sure I'm using one, and it's the file I reference in:
`gs4_auth_configure(path = "path to .json")` (see the very first post for my full code, although now I've eliminated the change of working directory)

I've never been able to do non-interactive auth without first doing interactive-auth and then moving either the entire project over or the file that ends up in the .secret folder. 

Re: package versions, I'll look into that. But would could that really explain why the script would work for several days on the server via the cron job, and then fail? I'm asking earnestly, I honestly don't know.

**Comment by jennybc** [comment]
> Unless I'm completely misunderstanding what a service account token is (which is completely possible ...

I'm afraid, yes, this is true 😁

`gs4_auth_configure()` is how you, the user, provide your own OAuth app:

https://googlesheets4.tidyverse.org/reference/gs4_auth_configure.html

That app is then used as part of so-called "three-legged oauth" to get a user token, also on your behalf. You are providing 2 of the 3 legs and Google is the third.

You are still making an OAuth token on behalf of yourself as a normal user and this type of token is designed primarily for interactive use.

It's still not clear to me why you are able refresh your token ?a couple of times? and then it stops refreshing.

---

A service account is a type of account designed for unattended computer-to-computer work. As soon as I hear "cron job" and "remove server", I know that this is the most appropriate type of auth for whatever it is your are doing.

Once you have a service account, with the correct APIs enabled (Sheets in this case), and with permission to read/write/whatever the relevant Sheets, you would provide a service account token (also a `.json` file) to the `path` argument of `gs4_auth()`. Or put that file in a place that will be discovered by the [Application Default Credential search strategy](https://gargle.r-lib.org/reference/credentials_app_default.html).

---

The Non-interactive auth article describes all this and I know you've seen it, but maybe it will start to make more sense now:

https://gargle.r-lib.org/articles/non-interactive-auth.html

**Comment by christopherkn** [comment]
Wow. I was sure that the .json file I had been using was the service account token, but it appears it was something else (the file name begins with "client_secret" then is a string of letters, numbers and dashes, and then ends with ".apps.googleusercontent.com.json"). I had already created a service account and given it ownership permissions for my google sheet, but I couldn't see where to re-download the .json of the service account token, so I created a new account, downloaded the service account token .json, gave it permissions to my sheet, and changed the authentication portion of my code to a single line:

`gs4_auth("path_to_json")`

and it is currently working. I do NOT understand how I've struggled for now over a month on this. The documentation is definitely pretty intimidating for me (someone with no experience with APIs, service accounts, gargle, OAuth, etc), so it feels like the documentation could be improved, but when I actually just DID everything that it says in the "Provide a service account token directly" section of https://gargle.r-lib.org/articles/non-interactive-auth.html it worked (at least for now!).

One thing that I know I got stuck on the first time I was working on this was that I didn't know I needed to create a GCP account. I don't think the documentation says that anywhere. So for a very new user like me, I just had no idea how to get these tokens everyone was talking about. It also then took a little while after I figured out about the GCP bit that I also realized I had to make a service account, and then go to the google sheet of interest and give the email address from the GCP service account permissions to the sheet.

Perhaps non-interactive auth is just not something you're expecting someone with this little knowledge of these things to be trying to do, and it seems like there's a LOT of different ways in which people may want/need to set up the non-interactive auth, but a "GS4 Non-interactive auth for dummies" section that lays out everything from the very beginning would have been SUPER useful to me a month ago! I think I got lost in all the different options that are laid out in such (probably super useful to many people) detail in the documentation currently.

I think it would have been helpful to me to have details that say you should/can:

1. Create a GCP account
2. Create a service account
3. Create a key and download the .json
4. Make the service account email address an owner (or whatever) to your google sheet
5. Point gs4_auth() to the .json from step 3
6. You are now always and forever (hopefully) authenticated.

Maybe this is just a me problem and the documentation already says all that, or maybe it's just not worth adding yet ANOTHER section of documentation that puts together things that already exist elsewhere, but just figured I'd let you know about my experience and what seems like it would have been helpful. I'm very excited by what I'm really hoping is the permanent solution to my non-interactive auth problem! We'll see in a couple days if it's still running smoothly! Thanks for all the troubleshooting, I hope this was helpful to you as well.

**Comment by jennybc** [comment]
Thanks for the feedback and I'm glad you are unstuck!

Yes I know there is or may be a documentation problem. But I keep writing more and more docs and it's ... not helping? So I will try to make improvements but am also not convinced more words are the solution. I have interacted with many people who said something similar to this:

> but when I actually just DID everything that it says in the "Provide a service account token directly" section of https://gargle.r-lib.org/articles/non-interactive-auth.html it worked

As for knowing one needed a GCP project, I feel like that is clear in the "How to get your own API credentials":

https://gargle.r-lib.org/articles/get-api-credentials.html

which is presumably where you got the instructions on how to get an OAuth app (which you seem to have) and a service account token (which you also have).

I will keep mulling over the docs, but I think is just plain hard the first time you confront it.

**Comment by jennybc** [comment]
If your problem is solved, I think we can close this issue.

**Comment by christopherkn** [comment]
Last thought with regard to "when I actually just DID everything..." is that, at the beginning of my journey to figure this all out, it felt like many things linked to many other things and you only needed to do parts of each thing and it got confusing what HAD to be done, what things were multiple ways to do the same thing, when each was necessary vs optional, etc.

Agree that very often, more words isn't the solution. Also I understand that actually writing the documentation is a million (or more?) times harder than commenting on how it didn't work for me!

Problem is solved (at least for now, we'll see in a few days) so I'll close the issue! Thanks for your attentiveness.

**Comment by jennybc** [comment]
Yeah, part of the problem is that these things are documented at the gargle level, because otherwise the docs would have to be duplicated across googlesheets4, googledrive, gmail, and bigrquery, just for starters. If I did that, they would inevitably not be correct and in sync.

Also, some people need and OAuth app and some people need a service account token and some people are going to insist of using an OAuth token, even when they shouldn't, because it's the token they know. So it's also hard to write a clean: do X, Y, and Z, in this order.

But yes I realize there is room for improvement and am actively cogitating on what to do about it.
