### ISSUE TITLE
googledrive authorization issue 

### ISSUE THREAD

**Issue by MichaelTD83** [tidyverse/googledrive#328]
I recently installed the most recent version of R and updated all the packages that needed it and I am now having issues connecting to the googledrive package that I did not have before. I have looked through https://gargle.r-lib.org/articles/non-interactive-auth.html but cannot seem to figure out what I need to do and the suggestions in that artice give me the same results. Before when I first started using theh googledrive package I had a webpage pop up with my gmail account asking permission for the tidyverse package to give permissions. Once granted I never had to deal with this again. Now I continually get one of the following messages. 
```
The googledrive package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort.

1: mtd25@nau.edu
```
or 
```
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html
```

But when I select 1 in the first error message I still am not able to access google drive. Also, I have had multiple times when the web browser popped up and asked me to authorize tidyverse again but still with no success. Here are some of the steps I've tried so far from similar examples found in your issues section that were similar.

Also, this is happening on my work computer that is connected to a network. While my personal computer is not having this issue and I did all of the same updates on the same day on for both computers.

Any suggestions would be appecieated.

```
 library(rgee)
 library(reticulate)
 library(gargle)
 library(googledrive)

Attaching package: ‘googledrive’

The following object is masked from ‘package:gargle’:

    request_make

 options(gargle_oauth_email = "mtd25@nau.edu")
 # drive_auth(use_oob = TRUE)
 # 4/1AY0e-g7oZPmGF_4GS4k6mt93vWlisdqG8VtFomLlx-F0gVIhxQYsmG3pVZY
 library(googleCloudStorageR)
 
 ee_Initialize("mtd25@nau.edu", drive = TRUE, gcs = TRUE)
-- rgee 1.0.8 --------------------------------------------------------------------------------------- earthengine-api 0.1.257 -- 
 √ email: mtd25@nau.edu 
 √ Google Drive credentials:Error: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html

```
Yet when I do not request to connect to Google Drive I get authorized for google cloud storage without issue.
```
 library(rgee)
 library(reticulate)
 library(gargle)
 library(googledrive)

Attaching package: ‘googledrive’

The following object is masked from ‘package:gargle’:

    request_make

 options(gargle_oauth_email = "mtd25@nau.edu")
 # drive_auth(use_oob = TRUE)
 # 4/1AY0e-g7oZPmGF_4GS4k6mt93vWlisdqG8VtFomLlx-F0gVIhxQYsmG3pVZY
 library(googleCloudStorageR)
 ee_Initialize("mtd25@nau.edu",  gcs = TRUE)
-- rgee 1.0.8 --------------------------------------------------------------------------------------- earthengine-api 0.1.257 -- 
 √ email: mtd25@nau.edu 
 √ GCS credentials:  FOUND
 √ Initializing Google Earth Engine:  DONE!
 √ Earth Engine user: users/mtd25
```

```
library(googledrive)
 drive_find("Maple")
The googledrive package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort.

1: mtd25@nau.edu

Selection: 
Enter an item from the menu, or 0 to exit
Selection: 1
Auto-refreshing stale OAuth token.
Items so far: 
200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400 8500 8600 8700 8800 8900 9000 9100 9200 9300 9400 9500 9600 9700 9800 9900 10000 10100 10200 10300 10400 10500 10600 10700 10800 10900 11000 11100 11200 11300 11400 11500 11600 11700 11800 11900 12000 12100 12200 12300 12400 12500 12600 12700 12800 12900 13000 13100 13200 13300 13400 13500 13600 13700 13800 Error: Server error: (500) Internal Server Error
  *  domain: global
  *  reason: internalError
  * message: Internal Error
Run `rlang::last_error()` to see where the error occurred.
 rlang::last_error()
<error/gargle_error_request_failed>
Server error: (500) Internal Server Error
  *  domain: global
  *  reason: internalError
  * message: Internal Error
Backtrace:
 1. googledrive::drive_find("Maple")
 2. googledrive::do_paginated_request(...)
 3. gargle::response_process(page)
 4. gargle:::stop_request_failed(error_message(resp), resp)
```
```
 library(googledrive)
 options(gargle_quiet = FALSE)
 drive_auth()
trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: googledrive
adding 'userinfo.email' scope
loading token from the cache
The googledrive package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort.

1: mtd25@nau.edu

Selection: 1
matching token found in the cache
```
```
 sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.4 tools_4.0.4  
```

**Comment by jennybc** [comment]
The first error seems to be coming from `ee_Initialize("mtd25@nau.edu", drive = TRUE, gcs = TRUE)`? Which I suppose is a function in googleCloudStorageR? So I don't think that is a problem within the scope of the googledrive package.

Then it looks like your pure googledrive work is working fine.

It is true your `drive_find("Maple")` call eventually hits a 500 Internal error, but that is just pure bad luck and happens to all of us from time to time.

This smells like some sort of problem with googleCloudStorageR and how it's ?maybe? piggy-backing on or integrating with googledrive's auth. It is true that the we recently rolled the internal credentials in gargle (which will affect googledrive), so it makes sense that you needed to re-auth once after the update. But the ongoing problems are something else (but possibly related).

**Comment by jennybc** [comment]
It is also true that we are now very careful about using a cached token and, if the user hasn't specified their email or otherwise given explicit directions, we ask for permission in an interactive session. So perhaps this is new for you?

If you never want to see this question:

```
The googledrive package is requesting access to your Google account. Select a pre-authorised account or enter '0' to obtain a new token. Press Esc/Ctrl + C to abort.

1: mtd25@nau.edu
```

you have to pre-authorize the use of the token we're finding, using any of the methods shown here:

https://gargle.r-lib.org/articles/non-interactive-auth.html#sidebar-2-i-just-want-my--rmd-to-render

**Comment by MichaelTD83** [comment]
Thanks for the quick response. ee_initialize is a function of the package rgee. I still the 500 Internal error happens every time I try to use the drive_find but I guess that was a bad example and I was able to get the function drive_get to work. The preauthorization methods seem to work for specific googledrive commands but it still does not work for the ee_initialize. I still haven't located the source of the problem but may be some kind of earthengine-api version update conflict.

**Comment by jennybc** [comment]
>  I still get the 500 Internal error happens every time I try to use the drive_find 

Hmm, that's strange. That could be issue-worthy, if we can make it reproducible, but I doubt we can. In any case, making your query as specific as possible, so that it happens **server-side** is my main advise, for example using a `q` clause:

``` r
drive_find(q = "name contains 'TEST'",
           q = "modifiedTime > '2017-07-21T12:00:00'")
```

Otherwise, I think this doesn't seem like a googledrive problem, which has not changed. gargle has updated and that caused your credentials to roll and you need to be more explicit re: which token to use non interactively. I think it's a good bet that the rgee integration is the problem.
