### ISSUE TITLE
speed issues with drive_ls

### ISSUE THREAD

**Issue by drwilkins** [tidyverse/googledrive#350]
I'm using googledrive to extract links and filenames from a googleDrive folder as part of a workflow and I've run into a *minor* issue that drive_ls() calls seem to return very slowly (~10sec). I was just wondering if this is due to using the default Oauth credentials or is it just a latency on the Google end of things? (i.e. should I set up my own Oauth credentials?...which is something I've never done before.)

**Comment by jennybc** [comment]
I think this is just the way it is. All of googledrive's path-based work requires a great deal of futzing behind the scenes, i.e. the Drive API is completely file id based. I could probably do some things to speed certain functions up (like batch requests, which I do plan to implement). But basically something like `drive_ls()` is always going to be slow and that can be made even worse by certain features of your particular Drive, i.e. lots of folders.
