### ISSUE TITLE
Cannot connect to google drive from R google colab

### ISSUE THREAD

**Issue by max-poltora** [tidyverse/googledrive#368]
I am trying to connect to google drive from my google colab project using the code below:
```
library(googledrive)
options(gargle_quiet = FALSE, gargle_oob_default = TRUE, gargle_oauth_cache = TRUE)
drive_auth()
```
But get the following Error:

> trying `token_fetch()`
> 
> trying `credentials_service_account()`
> 
> Error caught by `token_fetch()`:
> 
> Argument 'txt' must be a JSON string, URL or file.
> 
> trying `credentials_external_account()`
> 
> aws.ec2metadata not installed; can't detect whether running on EC2 instance
> 
> trying `credentials_app_default()`
> 
> trying `credentials_gce()`
> 
> trying `credentials_byo_oauth()`
> 
> Error caught by `token_fetch()`:
> 
> inherits(token, "Token2.0") is not TRUE
> 
> trying `credentials_user_oauth2()`
> 
> Gargle2.0 initialize
> 
> attempt to access internal gargle data from: googledrive
> 
> adding 'userinfo.email' scope
> 
> loading token from the cache
> 
> no matching token in the cache
> 
> initiating new token
> 
> Error caught by `token_fetch()`:
> 
> 'cli_abort' is not an exported object from 'namespace:cli'
> 
> Error: 'cli_abort' is not an exported object from 'namespace:cli'
> Traceback:
> 
> 1. drive_auth()
> 2. drive_abort(c("Can't get Google credentials", i = "Are you running googledrive in a non-interactive session? \\\n             Consider:", 
>  .     `*` = "{.fun drive_deauth} to prevent the attempt to get credentials", 
>  .     `*` = "Call {.fun drive_auth} directly with all necessary specifics", 
>  .     i = "See gargle's \"Non-interactive auth\" vignette for more details:", 
>  .     i = "{.url https://gargle.r-lib.org/articles/non-interactive-auth.html}"))

Can you please help me out with this problem?

**Comment by jennybc** [comment]
This is being tracked in https://github.com/r-lib/gargle/issues/140. The basic problem is that these notebooks "feel" interactive but then are not truly compatible with the interactive auth workflows, specifically those in httr, which gargle relies on. I think the current workarounds are to use an experimental fork of httr (see the gargle issue for more), create a token elsewhere and bring it to Colab, or to use a service account token.

**Comment by max-poltora** [comment]
@jennybc, thank you for your respond!
