### ISSUE TITLE
Make Files Read-Only on Google Drive via RStudio

### ISSUE THREAD

**Issue by huixinz2** [tidyverse/googledrive#370]
[Google Drive API v3](https://developers.google.com/drive/api/v3/reference/files/update) allows us to update a file's metadata/content. The "contentRestrictions[].reason" property under [Request Body](https://developers.google.com/drive/api/v3/reference/files/update#request-body) makes the content of a file read-only. I have explored ways to implement this request in R but could not seem to successfully lock the file's content.

```r
test <- shared_drive_get("test_drive")
test_upload <- drive_upload("test_file", path=test)

# I first tried to use a named parameter to pass along to the Drive API
test_upload <- test_upload %>%
  drive_update(contentRestrictions[].readOnly=TRUE)
# Received output "Error: unexpected symbol in:"

# I also tried to use "request_generate" but could not find the corresponding endpoint.
fileId <- "1e8L2QX_NDbxuQ2DPxH97Tdyd6Owy1CK7"
lockfile <- request_generate(
  endpoint = "ContentRestriction",
  list(fileId = fileId),
  token = drive_token()
  )

```

**Comment by jennybc** [comment]
Does this achieve what you want?

``` r
 drive_update(x, contentRestrictions = list(readOnly = TRUE))
```

**Comment by jennybc** [comment]
If you show me the curl command line produced by the API Explorer, that works for you, that might help me see what's different about what the `drive_update()` command above is sending.

**Comment by huixinz2** [comment]
The API Explorer uses the following code: 
{
  "contentRestrictions": [
    {
      "readOnly": true
    }
  ]
}

**Comment by jennybc** [comment]
OK, this works for me:

``` r
drive_update(x, contentRestrictions = list(list(readOnly = TRUE)))
```

**Comment by huixinz2** [comment]
This work - thank you so much! If you don't mind, could you briefly explain why it requires the following structure?
```r
list(list(...))
```

**Comment by jennybc** [comment]
Because, spurred by your example, I read the docs more closely for the `contentRestrictions` element of a `files` resource and I realized it's a JSON array. Basically, it's about finding the R list representation that `jsonlite::toJSON()` will translate into the appropriate JSON string.

*Also, TBH at this point in my journey with wrapping various APIs, I've realized that "just add another layer of `list()`" is often the solution 🤣*

**Comment by huixinz2** [comment]
Thank you very much!
