### ISSUE TITLE
drive_mv in Shared Drive environment

### ISSUE THREAD

**Issue by bllittle** [tidyverse/googledrive#377]
I would like to move files to another folder when uploading a new version so people have a record of previous files to refer to. drive_mv() worked fine for this in April 2021. Now when I try the same code in the same environment (and I continue with the same rights on the folders), I get the following error: 
Error: Client error: (403) Forbidden
A shared drive item must have exactly one parent.
* domain: global
* reason: teamDrivesParentLimit
* message: A shared drive item must have exactly one parent.
Run `rlang::last_error()` to see where the error occurred.
>       mvFiles <- drive_mv(file=as_id(curLink),
+                           path=archPath
+                           )

I've also tried this with the overwrite = TRUE parameter, but the same result. 
EDIT: Here is sample code: 
```
for(ri in 163:length(recFilterSchools)){
  #    ri <- 3 # for testing
    curSchool <- recFilterSchools[ri]
    curFile <- paste0(fileInputPath,curSchool,".xlsx")
    fSave <- paste0(curSchool, fReName, fDate)
    fSchoolURLS <- google_Fldrs_Results %>% filter(SchoolNum==curSchool, FolderName==tList)
    fSchoolURLS_Arch <- google_Fldrs_Results %>% filter(SchoolNum==curSchool, ParentFolder==tList, FolderName=='Archive')
    targetDir <- fSchoolURLS$FileURL
    targetArch <- fSchoolURLS_Arch$FileURL
    parentID <- fSchoolURLS$LocationID
    schID <- fSchoolURLS$schID
    curMslRow <- msl_Results %>%
      filter(SCHOOL_NUMBER==curSchool)
    
    curSchoolName <- curMslRow$School
    drID <- drive_get(targetDir, verbose = TRUE)
    curFolderContents <- drive_ls(targetDir, 
                                  pattern= tList,
                                  type='spreadsheet')
    #     typeof(curFolderContents)
    #      fmRows <- nrow(curFolderContents)
    fmRows <- nrow(curFolderContents)
    if (fmRows>0){
      for (fm in 1:nrow(curFolderContents)){
        #        fm <-1
        mvFiles <- drive_mv(file=as_id(curFolderContents$id[fm]),
                            path=targetArch
                            ,name= curFolderContents$name[fm])
        drResources <- mvFiles$drive_resource[[1]]
        OutUploadedDF <- rbind(OutUploadedDF, data.frame(stringsAsFactors = FALSE,
                                                         FileID = mvFiles$id,
                                                         FileName = mvFiles$name,
                                                         FilePath = drResources$webViewLink,
                                                         FileParent = parentID,
                                                         FileType = drResources$mimeType,
                                                         DateUploaded  = format(Sys.time(),'%m/%d/%Y'),
                                                         schID = schID))
        
        
      }    
    }
  #more code below to upload new file to folder 
}

```thanks

**Comment by bllittle** [comment]
Hi @jennybc,

I updated with more code -- any thoughts? 

Thanks,
Bruce

**Comment by jennybc** [comment]
More background, mostly for myself: the existing logic seems to work in a user's My Drive. But you do really have to remove parent +add parent if the file in question lives on a shared drive. This problem is currently only affecting people moving files around on a shared drive.

**Comment by bllittle** [comment]
Hi Jenny,

Sorry for coming back to this topic after so long. We're finally back in
need of this and still getting the same error in the loaded googledrive
package. Was the fix ever put into the production package?

I've been trying to load the "fix" package, but it hangs during the install
stage (has been installing for the past 20 minutes as I write this).

The scenario we have that would make it nice to actually move a file from
one folder to another is as follows:

   - We are a large urban school district. I work in Central Office and
   help in planning standardized testing.
   - We deliver files with lists of students who are scheduled for
   standardized tests to schools via a series of shared folders. We must
   manage sharing on these folders because the information about the students
   that we share should only be seen by administrators and teachers at THAT
   school and not any of our other schools
   - We use outside vendors to supply the tests themselves. We get files
   from vendors on which students THEY think are scheduled for testing at a
   particular school.
   - Since families move, there are many instances when a student may
   change schools. Or, a parent may decide they do not wish for their child to
   participate in standardized testing. Anyway, there are many situations
   where the lists of students at a given school may change.
   - Due to that fact, we re-publish files on a weekly basis from early in
   the semester until testing is completed.
   - School level administrators have requested that we maintain prior
   files for reference. The preferred method is to MOVE this file into an
   "archive" folder. Without the move capability, we resort to renaming the
   file. But this results in many files an administrator must scroll through
   to get to the most recent student list file.

Thanks for the great package otherwise.

Thanks,
Bruce

**Comment by bllittle** [comment]
Well, now I have a red face.

After sending this, I stopped the install process. I got an "RStudio is not
responding" message and allowed it to restart. I went back to the original
load process and now it is indeed moving files.

At least you got a broader context of the need. 😎

Thanks again.

**Comment by deschen1** [comment]
Not sure if entirely related this bug, but I have the same error/issue and it still doesn't work, see my SO post: https://stackoverflow.com/questions/73750125/trying-to-move-a-google-drive-file-with-googledrive-package-results-in-403-error

**Comment by jennybc** [comment]
@deschen1 Apparently I haven't released googledrive since I made this fix. This appears to the be only (substantive) change made since the last release.

So for now, you need to use the dev version.

**Comment by deschen1** [comment]
Ah ok, that probably explains it.

Since we are here, do you have any idea/plan on next releases? I understand the desire to avoid the overhead of publishing a new release just for a supposedly minor bug fix, but since it's several people now making it so far to respond on the dev page of the package, I feel there's indeed an audience for an updated version. ;-)

**Comment by jennybc** [comment]
I have to release gargle soon for other reasons, so then it would make sense to release googledrive (which currently depends on dev gargle). I'll put this on my near-term todo list.
