### ISSUE TITLE
The documentation needs update about a feature relating to roles of folders in shared drives.

### ISSUE THREAD

**Issue by Falnesio** [tidyverse/googledrive#381]
`drive_share()` is able to set permissions on individual folders inside shared drives.

 - Setting role to "writer" makes user gain the contributor permission. 
 - Setting role to "fileOrganizer" makes user gain the content manager permission.

(using terms from https://support.google.com/a/answer/7337554?hl=en)

This is something that is possible but that I could not find anywhere online.

**Comment by jennybc** [comment]
I basically have a policy of trying to not re-state Google's own docs, i.e. documenting things about Google Drive vs. documenting what the googledrive package does. This policy is based on learning the hard way, i.e. when Google changes things.

So I'm happy for googledrive to document how to use `drive_share()` to grant some entity a specific role. But I'm not willing to take the responsibility of explaining all the implications of that role.

I generally use the "See Also" section to link to more info, when I can.

`drive_share()` links to:
https://developers.google.com/drive/api/v3/ref-roles

If you think the link you give is helpful to those using shared drives, I'd be happy to take a pull request to add it to `drive_share()`'s "See Also" section.
