### ISSUE TITLE
drive_mv error: cannotAddParent when trying to move files from one folder to another

### ISSUE THREAD

**Issue by cpilat97** [tidyverse/googledrive#386]
Hi there, 

I've been experiencing an issue related to the drive_mv function. I've tried to recreate a reprex as best as possible for the larger scale issue i'm facing.

Context: I have a google form that has > 10 uploads associated with it. Because of how drive & forms works with doc uploads, each upload is placed in an individual folder. What I need to do is move the files out of those folders and into a folder associated with that given submission. So all of submission_id A's uploads will be in a "ID A" file rather than the individual upload files (apologies if that's a bit muddled....the way forms does the back end file creation is a little odd to me). I've grabbed the sheets export from the form that contains all the links to the uploads, pivot_longer() so i have a long tibble associating each link to the given id. 

What i'm trying to do is akin to : `file_move <- map2_dfr(.x = vector_of_links, .y = vector_of_folder_id, drive_mv)`.  But each time i do this, i run into the following error: 
```
Error in `cli::cli_abort()`:
! Client error: (403) Forbidden
Increasing the number of parents is not allowed
• domain: global
• reason: cannotAddParent
• message: Increasing the number of parents is not allowed
```

I'm using a service account, have everything permissioned correctly (service account email is set to editor on all pertinent files), and can read individual stuff via various googledrive and googlesheets4 calls. i.e. if i try to copy the files using `map_dfr(.x = vector_of_links, ~ drove_cp(.x, path = drive_link))` that works without a hitch. I'm trying to avoid creating duplicates/copies of the file submissions if i can. 

I've tried my best at creating a reprex of my issue using a test form, please see the following: 

Form Link: https://docs.google.com/forms/d/e/1FAIpQLSc3vQ8YS5wFtQjUR0P9JOiIbJeHTQwyEctTq_drccasMElSlQ/viewform?usp=sf_link

Note, i've set the permissions to this file to be any link on internet if you'd like to look at it. 
Form Export Sheet: https://docs.google.com/spreadsheets/d/16w9nWJCIu3O-SaESWqee7XzZn8ORsd9KCwWtfMLpxUM/edit?usp=sharing

Top level folder that the form is saving the files to: https://drive.google.com/drive/folders/1SNNog41l1JtwCtsjs080K15eQVE6P9R_PmaTrD_HcKNC5nLevuGh6sDfJr1jUE0XsQf1rBEL?usp=sharing

```r
library(googlesheets4)
library(googledrive)
library(tidyverse)

drive_auth(path = 'my_service_account.json')
gs4_auth(token = drive_token())

#link from above, reading in the data. There's two test uploads of a nearly blank txt file. 
test_form_export <- range_read(gs4_get('16w9nWJCIu3O-SaESWqee7XzZn8ORsd9KCwWtfMLpxUM'), sheet = 1, 
                               range = "A1:C2") %>% 
  pivot_longer(!Timestamp)


#> print(test_form_export)
# A tibble: 2 × 3
  Timestamp           name          value                                                             
  <dttm>              <chr>         <chr>                                                             
1 2022-02-14 13:06:58 form_upload_1 https://drive.google.com/open?id=1rtFh1IoiUHS1eIDOx2_3zwkDeAoAgGtz
2 2022-02-14 13:06:58 form_upload_2 https://drive.google.com/open?id=1rqxyEqUX2bthoOzNb9hlWpOMPMc1wMxC

#test folder i've created to move too, also publicly available
folder_to_move_to <- as_id('https://drive.google.com/drive/folders/1MUWgTFDiiEYL6NJTpsla6qEpq3XFuGm2')
 
#I'm trying to do one of the following. But to no avail: 
test_move <- map_dfr(test_form_export$value, ~ drive_mv(.x, path = folder_to_move_to, overwrite = TRUE))
test_move_2 <- map2_dfr(.x = test_form_export$value, .y = folder_to_move_to, drive_mv)

Error in `cli::cli_abort()`:
! Client error: (403) Forbidden
Increasing the number of parents is not allowed
• domain: global
• reason: cannotAddParent
• message: Increasing the number of parents is not allowed
Run `rlang::last_error()` to see where the error occurred.
#> test_move_2 <- map2_dfr(.x = test_form_export$value, .y = folder_to_move_to, drive_mv)
Error in `cli::cli_abort()`:
! Client error: (403) Forbidden
Increasing the number of parents is not allowed
• domain: global
• reason: cannotAddParent
• message: Increasing the number of parents is not allowed
Run `rlang::last_error()` to see where the error occurred.

#Trying the following creates the same issues: 
#Get a single vector of the files to move: 
files <- pull(test_form_export, value)
test_move <- map_dfr(files, ~ drive_mv(.x, path = folder_to_move_to))
test_move_2 <- map2_dfr(.x = test_form_export$value, .y = folder_to_move_to, drive_mv)


#This does work though: 
#copy seems to work though: 
test_copy <- map_dfr(test_form_export$value, ~ drive_cp(.x, path = folder_to_move_to))
test_copy_2 <- map2_dfr(.x = test_form_export$value, .y = folder_to_move_to, drive_cp)
```

I did see you have some closed issues im assuming related to this. #356  & #334 , and the google links associated with them ([single-parent changes](https://developers.google.com/drive/api/v3/ref-single-parent) ) so i'm not sure if i'm maybe just misreading something here? The created folder is a child folder of the folder where the form upload documents sit. 

Apologies this is so long!! Trying to include as much info as possible/helpful. I'm also just going to include a rlang::last_error & rlang::last_trace call incase thats helpful: 

```r 
cpilat>rlang::last_error()
<error/gargle_error_request_failed>
Error in `cli::cli_abort()`:
! Client error: (403) Forbidden
Increasing the number of parents is not allowed
• domain: global
• reason: cannotAddParent
• message: Increasing the number of parents is not allowed
Backtrace:
 1. purrr::map2_dfr(...)
 2. purrr::map2(.x, .y, .f, ...)
 3. googledrive .f(.x[[i]], .y[[1L]], ...)
 4. googledrive:::drive_update_metadata(file, params)
 6. gargle::response_process(response)
 7. gargle:::gargle_abort_request_failed(error_message(resp), resp)
 8. gargle:::gargle_abort(...)
 9. cli::cli_abort(...)

cpilat>rlang::last_trace()
<error/gargle_error_request_failed>
Error in `cli::cli_abort()`:
! Client error: (403) Forbidden
Increasing the number of parents is not allowed
• domain: global
• reason: cannotAddParent
• message: Increasing the number of parents is not allowed
Backtrace:
     ▆
  1. └─purrr::map2_dfr(...)
  2.   └─purrr::map2(.x, .y, .f, ...)
  3.     └─googledrive .f(.x[[i]], .y[[1L]], ...)
  4.       └─googledrive:::drive_update_metadata(file, params)
  5.         ├─googledrive::as_dribble(list(gargle::response_process(response)))
  6.         └─gargle::response_process(response)
  7.           └─gargle:::gargle_abort_request_failed(error_message(resp), resp)
  8.             └─gargle:::gargle_abort(...)
  9.               └─cli::cli_abort(...)
 10.                 └─rlang::abort(...)

```

Thanks, and apologies if this isn't an actual issue....i was trying to do my research/troubleshooting and then felt like i was maybe going in circles after hoping between a few google articles. 

Best, 
Cory

PS 02/15/2022; 0946hrs EST - I also tried going back to basics following the [googledrive walkthrough](https://googledrive.tidyverse.org/reference/drive_mv.html) on my account. Created a simple text file & folder for it to site in, and tried to move it into a folder i created using `drive_mkdir()` and received the same error.

**Comment by cpilat97** [comment]
I may have figured out at least the base issue here, though i'm not sure of a way around it (or if that means it's not necessarily an issue here since it is probably more with googles api). 

Using the form & file links above, I used `drive_deauth()` to remove my service account key, ran `drive_auth()` and authorized via my own personal account & the Tidyverse OAuth screen (my personal gmail is the "owner" of the parent folder). Then, trying to use `drive_mv()`, i had no issues moving the files. 

So i'm guessing that this has to do with who is marked as the owner of the file even though my service account had editor access on all files and folders involved. 

My issue still standing is a way to grant that kind of access to the service account. The reasoning behind this is we have responses to the form regularly coming in, and my ultimate goal was to have this script run on a cron schedule where it would run, reorg the files, etc... every so often so the team i'm supporting can go through and do what they need with these files. When i try to transfer ownership of a file, ownership isn't transfered until the new owner accepts the transfer request which poses a unique issue since i (don't believe i) cannot access a service accounts email. 

I've spent the morning trying to read through google api docs to hopefully pass something to the `...` arg of `drive_update(file, media, ...)` but honestly, that's a bit beyond me....

**Comment by cpilat97** [comment]
Apologies for one last addendum here...but after my last post and seeing it was something i can do under my own account using the general googlesheets4/tidyverse resources, I switched to an OAuth app i have set up and tried through that authing under my own personal gmail and that worked too. 

So at the end of all this, i'm suspecting that this isn't an issue an issue so much with `googledrive` package itself, but rather maybe how service accounts interact with the parent settings the google api moved to a year and a half ago. 

Happy to mark this as closed, just let me know. Thanks!!

**Comment by cpilat97** [comment]
Closing this. 

As i've spent more time than I thought reading through google API docs, this is absolutely has nothing to do with `googledrive`, the package, itself, rather how the file structures & ownership is set up within drive. 

Thanks!

**Comment by jennybc** [comment]
I'm not really watching this repo right now, but I've taken a quick peek at this. The main thing I want to point out is that the fix related to `drive_mv()` and the multiple parent error is only in the dev version. So to benefit from that, you'd obviously need to be running a version of googledrive installed from GitHub. An error like "Increasing the number of parents is not allowed" could definitely be the same problem and, I hope, could also already be fixed in dev.

**Comment by cpilat97** [comment]
Thanks Jenny, appreciate this follow up. What I did for the time being was write an R script for the owner of the folders, gave them the credentials for the OAuth app so they could log into our cloud api resources via their email, and then allow them to run the file moves from there. And that worked without an issue (which was another reason i closed). 

I'll try out the dev version and see if I experience the same results, would be interesting to see if I encounter the same issues or not. Thanks for pointing to the dev version. As I said, my ultimate goal with this was to automate the file movements with my service account key so it could be done invisibly in the backend. The solution i wrote above is working though, thankfully (there were.....a lot of files). 

Thanks so much for your help and continued work on these (drive, sheets, etc...) packages! I think i've said this in another issue, but these packages (and purrr has been a huge win lately) have really helped contribute to rolling out universal 3K and PK to NYC families. Appreciate the work you put into these!
