### ISSUE TITLE
provide a mechanism to display/remove gargle cache path

### ISSUE THREAD

**Issue by jonathancallahan** [tidyverse/googledrive#395]
I am testing **googledrive** for suitability for a project and, when prompted in a browser, gave permission to manipulate my Google Drive files.

But I had inadvertently authenticated with my personal account. Now I want to remove that cached information entirely and start over again with a different account. I have removed the ability to manipulate files with the following:

```
> drive_auth(email = NA)
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> gargle::gargle_oauth_cache()
[1] TRUE
```

I think I'm safe now, but I would be much more comfortable if I knew where the cached information was located so I could remove that directory (file?) entirely and start over.

This issue could also be solved with a short "Package configuration" article describing how **gargle** caches information.

**Comment by jennybc** [comment]
Please see the docs for `gargle::gargle_oauth_sitrep()`:

https://gargle.r-lib.org/reference/gargle_oauth_sitrep.html

and the article on troubleshooting gargle auth:

https://gargle.r-lib.org/articles/troubleshooting.html
