### ISSUE TITLE
drive_mkdir doesn't allow for multiple folders with the same name in the same path

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#40]
as mentioned in #24 
I think there may be a small bug in the get_leaf function - when I run:
```
drive_mkdir("baz", path = "test_8675309/foo/yo")
```
I see
```
## Error: The path 'test_8675309/foo/yo/' identifies more than one file:
## File of type folder, with id 0B0Gh-SuuA2nTOEVQX1BteW1Fa3M.
## File of type folder, with id 0B0Gh-SuuA2nTN3VMYWdOZlhrM0k.
```
but on drive I have:
test_8675309
+-- foo
| +-- yo (id 0B0Gh-SuuA2nTOEVQX1BteW1Fa3M)
+-- yo (id 0B0Gh-SuuA2nTN3VMYWdOZlhrM0k)

so in fact test_8675309/foo/yo should be unique (since the other one that it's fussing about is actually test_8675309/yo)

Also, when checking through the path, match [here](https://github.com/tidyverse/googledrive/blob/master/R/drive_path.R#L33) doesn't allow for nested folders with the same name. For example if we had "foo/foo", which is perfectly logical, match only matches the first, so we would have depth 1 for both, where they should each be listed as both depth 1 and 2.

**Comment by jennybc** [comment]
I'll play with your solution. Some parts definitely look necessary so 👍. I think I might modify the fix near the end.I think I should be checking these root paths for length and/or resolving name-wise to the path pieces that we have.
