### ISSUE TITLE
forthcoming change to Google oauth flow

### ISSUE THREAD

**Issue by achubaty** [tidyverse/googledrive#401]
I've recently been seeing the following warning when doing `drive_auth()`:

![image](https://user-images.githubusercontent.com/3435577/195967922-a09fb412-c98b-4c70-b35e-4a3018e016e2.png)

Not sure if this package or perhaps `gargle` is responsible for implementing the oauth flow, so please move this issue as appropriate.

**Comment by jennybc** [comment]
This is under control and tracked here https://github.com/r-lib/gargle/issues/202.
