### ISSUE TITLE
drive_ls don't works 

### ISSUE THREAD

**Issue by RafaelFNovi** [tidyverse/googledrive#404]
drive_ls("~/Shared with me/folder1/folder2")

Error in `as_parent()`:
! Parent specified via `path` is invalid:
x Does not exist.
Run `rlang::last_error()` to see where the error occurred.

**Comment by jennybc** [comment]
Presumably a duplicate of #396

**Comment by RafaelFNovi** [comment]
Hi Jenny, thank you!
I used this and works :)
 drive_ls(as_id("id of my folder"))
