### ISSUE TITLE
`drive_upload()` fails when "vctrs_vctr" class is cached as a child of "list"

### ISSUE THREAD

**Issue by idmn** [tidyverse/googledrive#409]
Code to reproduce:

```r
library(posterior) # (>= 1.3.0)
library(googledrive)

# posterior makes "vctrs_vctr" be cached as a child of "list"
getClassDef("vctrs_vctr") 
#> Virtual Class "vctrs_vctr" [package "posterior"]
#> 
#> Slots:
#>             
#> Name:  .Data
#> Class:  list
#> 
#> Extends: 
#> Class "list", from data part
#> Class "vector", by class "list", distance 2
#> 
#> Known Subclasses: "rvar"

gd_id <- as_id("<some GD folder URL>")
class(gd_id)
#> [1] "drive_id"   "vctrs_vctr" "character"

drive_example_local("chicken.jpg") %>%
  drive_upload(
    name = "name-squatter",
    path = gd_id,
    overwrite = TRUE
  )
#> Error: C stack usage  7954920 is too close to the limit
```

I was able to find out that this happens because `drive_upload()` [at some point](https://github.com/tidyverse/googledrive/blob/c7325dfcf1da648ad4764e7f6c6e5e2fc6a5d593/R/drive_upload.R#L135) needs to write a list, one of which elements is a drive id, to json. If you run `jsonlite:::asJSON(gd_id)`, you'll get the same C stack error.

An output of `as_id()` has the following classes: `c("drive_id",  "vctrs_vctr", "character")`. So I think this is what happens:

1. `asJSON` doesn't have a method for "drive_id" and "drive_id" is not extended by any other class (`extends("drive_id")`), so it applies the "ANY" method. See `selectMethod(jsonlite:::asJSON, "drive_id")`.
2. This method basically just [strips away the first class of the object](https://github.com/jeroen/jsonlite/blob/13e48ded961666495a6dbeaf4ceff1ff0f3dbb31/R/asJSON.ANY.R#L13) and leaves `c("vctrs_vctr", "character")`.
3. Then R searches for a `asJSON` method for "vctrs_vctr" and because it is extended by "list" (because of `posterior` loaded), applies the list method. See `selectMethod(jsonlite:::asJSON, "vctrs_vctr")`.
4. The "list" method traps into endless recursion [here](https://github.com/jeroen/jsonlite/blob/13e48ded961666495a6dbeaf4ceff1ff0f3dbb31/R/asJSON.list.R#L35) when it tries to `vapply()` `asJSON()` to the object because `x[[1]]` is identical to `x`.

I can't really tell whether it's something that `jsonlite` should've handled, or it's `posterior` doing something wrong. But I think regardless it's a matter of a simple update to prevent this from happening in `googledrive`?  
- drive id can be explicitly converted to character before being passed to `toJSON` in `drive_upload()`
- or "drive_id" class can be defined as a child of "character". If I run `setClass("drive_id", contains = "character")` at the beginning of the session, I don't get the error.

**Comment by jennybc** [comment]
I believe I am already using the vctrs recommended approach for expressing that `drive_id` inherits from `character`.

https://github.com/tidyverse/googledrive/blob/c7325dfcf1da648ad4764e7f6c6e5e2fc6a5d593/R/drive_id-class.R#L26

I feel like the real story / problem lies external to googledrive here and I am not eager to fiddle with handling of `drive_id` in googledrive for this specific case, given that it's been working well in general for quite a while. I also see that things are getting rationalized elsewhere.
