### ISSUE TITLE
unable to generate Google autharization tokens in rstudioserver

### ISSUE THREAD

**Issue by naveenbussari** [tidyverse/googledrive#436]
Hi @jennybc 
We are trying to generate Oauth tokens on Rstudio server to work on googledrive files using the following code.

```
options(gargle_oauth_client_type = "web")

googledrive::drive_auth(email = "bussari.naveen@olaelectric.com")

googlesheets4::gs4_auth(email = "bussari.naveen@olaelectric.com")
```

first we got the error createTcpServer: address already in use 
<img width="543" alt="Error in googledrivedrive_auth()°" src="https://github.com/tidyverse/googledrive/assets/88088284/d6e78c99-4a0f-4c7a-95bd-59b03c0d54d0">

I did this
<img width="826" alt="9 17304" src="https://github.com/tidyverse/googledrive/assets/88088284/cfd49a9f-80f6-495b-a4c0-9426b57dbad1">

Now I re-run the above code.
It's generating the token and we are able to copy the authorization code.
<img width="584" alt="Complete the Google auth process" src="https://github.com/tidyverse/googledrive/assets/88088284/6076d80c-c15b-49f3-8e01-f319734a1c52">

But the console is stuck forever with `'Waiting for authentication in browser'` and there's no `'Enter authorization code '` prompt.
<img width="795" alt="Pasted Graphic 21" src="https://github.com/tidyverse/googledrive/assets/88088284/3ef5eb96-57a8-4752-bf3d-cc33aca2ccd7">

At the same time in the server,
<img width="762" alt="image" src="https://github.com/tidyverse/googledrive/assets/88088284/f257be7e-076c-40c2-99b7-51594b71082f">

we are using gargle 1.4.0 and tidyVerse 1.3.2

FYI we were facing similar issues earlier.
https://github.com/tidyverse/googledrive/issues/425
https://github.com/tidyverse/googledrive/issues/424

Regards
Naveen

**Comment by naveenbussari** [comment]
It worked after including the line
```
options(httr_oob_default = TRUE)
```

Thanks

**Comment by jennybc** [comment]
I'm glad you've got it working.

I'm curious though: on RStudio Server, gargle (which provide auth functionality for googledrive) should automatically detect that it should use an oauth client of "web" type and that it should use out-of-band auth. Are you setting these things explicitly for a reason? If not, I think perhaps you should try doing *less* and allow the auto detection to happen. But if this is in response to a failure of auto-detection, I'd be interested to learn more.

**Comment by jennybc** [comment]
I revisited the issues linked above and now I remember. You do auth in an interactive RStudio session, but then later need that token to work in a cron job. So it makes more sense to me now why you might need to set these options. But I think this is more sensible than what you're currently doing (basically: be consistent about setting gargle options, not a mix of gargle and httr):

``` r
options(gargle_oob_default = TRUE, gargle_oauth_client_type = "web")
```
