### ISSUE TITLE
Uploading an R object w/o writing to file

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#44]
In testing, I note its awkward to always have to write to file before uploading. We need to offer a way to upload from an R object directly to Drive.

**Comment by sanjmeh** [comment]
a gentle reminder that this is still open.
One more reason why writing to a file first is a bad idea is because the NAs are all lost. Also sometimes extra quotes are inserted that need cleaning. Thanks

**Comment by jennybc** [comment]
I can't convince myself this is needed. To implement, you have to have specific combinations of R object and destination file type in mind. The most common one would be a data frame and Sheet, but that's what googlesheets4 is for. Closing until a specific use case presents itself.

**Comment by jennybc** [comment]
I can't convince myself this is needed. To implement, you have to have specific combinations of R object and destination file type in mind. The most common one would be a data frame and Sheet, but that's what googlesheets4 is for. Closing until a specific use case presents itself.

**Comment by renatocava** [comment]
> I can't convince myself this is needed. To implement, you have to have specific combinations of R object and destination file type in mind. The most common one would be a data frame and Sheet, but that's what googlesheets4 is for. Closing until a specific use case presents itself.

Hello @jennybc, a necessity is when you want to use Google Drive to store backup copies that are created daily, then an RDS or CSV file will take up less space than a GOOGLESHEET. Any recommendation?

**Comment by jennybc** [comment]
@renatocava In general, closed issues aren't a good place for discussion. If you're really interested in this, you should open a new issue and, in this case, provide some concrete details about the size differences you observe.
