### ISSUE TITLE
Google authentication issue in r-studio while running code

### ISSUE THREAD

**Issue by abhishekmicky1** [tidyverse/googledrive#455]
While running r-studio code on R (version 3.4.4) facing google authentication issue. I also tried to create another google credential but it's not working.

<img width="576" alt="google authentication issue" src="https://github.com/user-attachments/assets/31f4f0f1-8d06-43a1-8764-037bee0e187b">

and here I'm getting this another window:

<img width="728" alt="google authentication issue2" src="https://github.com/user-attachments/assets/0ca123a0-f0bc-4ef5-8e62-300f76849bc7">

**Comment by mattwilliamson13** [comment]
I'm having the same issue

**Comment by throughthetrees** [comment]
Adding to this. 

Issue is present when used from google colab.

![image](https://github.com/user-attachments/assets/f96679d6-c5d3-41fa-8941-a838361f8c6a)

**Comment by kenkomodo** [comment]
I am having this exact same issue as well. The package works with using stored tokens but attempting to create new authorization gives me the same screen as @throughthetrees.

**Comment by kenkomodo** [comment]
As of this morning it seems this issue is resolved.

**Comment by jennybc** [comment]
Yes, I think there must have been some temporary glitch that is now resolved. Based on a different report that came in via email over the weekend, I tried various things and could not reproduce the problem.
