### ISSUE TITLE
Abbreviated file ids

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#5]
The full ids are very long. I wonder if there is any official support or convention for using, e.g. the first 7 characters, as we do with SHA-1's in git.

I suppose even in the absence of that, we could make things *feel* that way in some places in these 2 packages.

**Comment by LucyMcGowan** [comment]
Are you thinking for a print method? Or to actually shorten them?

**Comment by jennybc** [comment]
Definitely in print methods we should do a lot of `abcdefg...`.

But also maybe we should accept shorter versions when a user is specifying an Id? Less clear if this is worth it.

**Comment by LucyMcGowan** [comment]
I don't think they're all unique by the first couple (at least my folders don't seem to be until 12+ characters)

**Comment by jennybc** [comment]
Oh hmmm. I still think we should consider writing a format method that ellipsizes ids in the middle, so that tibbles containing these ids still have room to show other variables. We need to find a way to always reveal a bit of the name (probably also ellipsized) and a bit of the id when you `gs_ls()`.

`stringr::str_trunc()` is a pre-packaged solution but I'd prefer not to depend on stringr. Unless we already do, indirectly?
