### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#55]
We should send an API key with every request, because there are fruitful things that can be done w/o auth, such as accessing world-readable files.

@craigcitro is going to tell us about a specific header to send that clarifies whether the API key or auth token should be consulted re: quota, in the case where both are present in the request.

**Comment by craigcitro** [comment]
So in pondering this, I realized that our situation here is a bit simpler: you want an API key **iff** there's no token available.

Here's a proposal:

* Set an API key by default (for requests with no token)
* Drop the API key when setting a token, and add it back when dropping auth
* Leave an option open to set an API key anyway, for oddballs like me.

WDYT?

**Comment by jennybc** [comment]
OK we'll try to do it like so 👆.

Should we know about this header anyway?
