### ISSUE TITLE
Suggestion to change prefix of functions from "gd"

### ISSUE THREAD

**Issue by zkamvar** [tidyverse/googledrive#6]
Feel free to ignore this if you have already considered it, but "gd" can be interpreted as an expletive. 

My suggestion would be to use "gdr" instead. It does break the two-letter prefix consistency with googlesheets, but avoids the expletive interpretation.

**Comment by jennybc** [comment]
😄 yes we have fretted about this. If we switch prefix, the most likely candidate is `drive_*`, I think. Still undecided.

**Comment by zkamvar** [comment]
👍  for `drive_*`.

**Comment by jennybc** [comment]
Let's leave this open until we've done it. This is the prefix favoured by @hadley as well.

@LucyMcGowan I think you should make the change.
