### ISSUE TITLE
NULL parents and "Shared with me" files

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#60]
The parents field is frequently `NULL` for files that are "Shared with me". This makes such files impossible to access via `drive_path()`, because these paths are technically not rooted.

Current workaround: pull all "Shared with me" files and isolate the one you want with `pattern`.

```r
drive_list(q = "sharedWithMe = true", pattern = "A reactive build system")
```

**Comment by LucyMcGowan** [comment]
thinking about whether we should pull `sharedWithMe` out as a parameter in `drive_list()`. (brain dump on this) Currently we default to showing all files, both your own and those shared with you - if we added a parameter would we default to *only* showing files that are actually owned by you and if you say `shared = TRUE` we would show *only* files that are shared with you? Or maybe we'd have it so the user could somehow state "shared only", "mine only", or "both". Or maybe it should just stay in `q` 🤔.

**Comment by jennybc** [comment]
> maybe it should just stay in q

I'm inclined to to nothing special here. I'm not even sure I want to do anything about the interaction of "Shared with me" files and paths. This might just be a documentation issue, i.e. that `path` only works on files you own.

**Comment by jennybc** [comment]
The one point this does bring up is that if `path` is length 1, maybe I should exit early instead of going through the whole tree search that ultimately requires finding the root folder as parent.

**Comment by LucyMcGowan** [comment]
It seems from fiddling around [here](https://developers.google.com/drive/v3/reference/files/list) that `q = "sharedWithMe = false"` doesn't work (`q = "sharedWithMe = true"` does of course). So yes, in full agreement that we shouldn't be trying to do anything with this in the parameters.

**Comment by jennybc** [comment]
Not sure why the merge message didn't close this automatically?
