### ISSUE TITLE
Struggling with drive_mv() function

### ISSUE THREAD

**Issue by asltjoey** [tidyverse/googledrive#66]
Hi,

I'm unsure whether here is the proper place to ask questions, probably it is not a bug. I am struggling with moving a googlesheet file using drive_mv(). The task is pretty straightforward with the following detail.

file_to_move = drive_file("1TrAW3z8OglPzMPrdhhIBrv85OVZR6wdW5wDWuxbBm5g")
destination_folder = drive_file("0B4md9-n1qmKTflE4ZHo5aXBLSmpyR0JuREg3OEFXa0V0SGozMTU0RXFQdTdWaXJFVDVGemc")

Both statements work perfectly fine and they could be opened successfully via drive_browse i.e.
drive_browse(file_to_move)
drive_browse(destination_folder)

Unfortunately when it comes to the final action which is 

drive_mv(file_to_move, folder=destination_folder)

, it gives me this error message: "Error in regmatches(path, m)[[1]] : subscript out of bounds"

I have been searching for the solution but still have no luck.

Best regards,
Prakasit

**Comment by jennybc** [comment]
I leave it to @LucyMcGowan to answer you specifically, but this package is under intense development  and we are likely breaking things quite frequently. Sounds like you ran into one of these! It should settle down a lot in the next month.

**Comment by asltjoey** [comment]
No worries. Really appreciate what you guys are building including googlesheets package. I would love to stick around for the improvements. Really appreciate your reply.

**Comment by LucyMcGowan** [comment]
@asltjoey this was a quick fix (thank you for pointing it out!) I'd like to echo Jenny's comment that we will likely be breaking things over the next few weeks 🙈, but excited that you're making use of it!
