### ISSUE TITLE
Interface of drive_list()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#7]
I think you should make heavy reference to `list.files()`. Specifically:

  * `path`: Should default to meaning "list my Drive files", which strikes me as the closest match for "current working directory". But then user should also be able to specify a *folder* here as well.
  * `pattern`: that's what the regex should be called, instead of `search`
  * I think `type` should possibly be elevated to an argument in the signature of `drive_ls()` itself, as opposed to getting mopped up in `...`.
  * Lots of the other args of `list.files()` are also worth considering. Good to ask yourself: is there is an obvious translation of this into the world of Drive?

In general, you need to think about how to help people craft searches. Obviously step one is simply to link to the [file searching guide](https://developers.google.com/drive/v3/web/search-parameters), as we've done. And to include some good examples. But this is an example of something that might be ripe for an add-in down the road.

**Comment by jennybc** [comment]
Now that I actually understand this a bit better, these seem like areas to explore:

  * Forming `q`. At its simplest, people have to provide `q` verbatim. But it might be nice to accept a vector of `q`s or multiple `q`s in `...`, which `drive_list()` would then concatenate with `and`.  It feels like there's also a need for an internal "append this to `q`" helper.
  * Specifying the fields that are extracted into columns of the returned tibble. It feels like this should have a reasonable set of defaults (the current hard-wired ones?), but be exposed for the user to tweak.
  * Elevate `type` to an actual argument? repeated from above.

**Comment by LucyMcGowan** [comment]
from #21 

context: user is interested in the file `baz` in the folder `foobar` and would have to type
```
drive_list(path = "foobar", pattern = "baz")
```
>as a user, why can't I just provide foobar/baz? What would be the difference? 🤔 I suspect answering this has implications for drive_list() docs and/or logic. Maybe put this in the existing issue thread for drive_list() interface? It has nothing to do with the README.

@jennybc 🤔 that is a good point, the way we have the logic now we expect the path parameter to always be a folder. In the broad sense, the pattern would usually be something like you'd want to find all the files with baz in them in a specific folder? But I can see a user wanting to specify a specific file and being sad that this doesn't let you do that with just one parameter. But then also if you are trying to find a specific file is that the best use of a "list"? (as you can see I've talked myself right around in a circle here). If keeping with list.files I don't believe it lets you pass a full path to the first parameter, it expects a directory and lists everything inside it.

**Comment by jennybc** [comment]
I suspect it should be like so: user says `path = "foobar/baz"` and we pull down file ids where name is foobar and mime type is folder or name is baz. I've already noted the need to NOT assume the last bit is a folder in #24.

We've already acknowledged that `drive_list()` will often be used to identify a single file. Hence the need for a function that takes a single row output from `drive_list()` and output a `gfile` object. It checks a few things about the tibble, then just extracts the `gfile` element.

**Comment by LucyMcGowan** [comment]
oh so maybe only for the case where `pattern` is `NULL`? Oh potential hiccup is if you have `foobar/baz` as your path, but what you really mean is you'd like to look inside the folder `baz` inside the folder `foobar`. I think we'd want to be sure to look for `baz` as having a mime type folder, since someone could have both a file named `baz` and a folder named `baz` in the folder `foobar` and we'd have to have a way to know which they'd like us to return, the file itself, or the contents of the folder.

**Comment by jennybc** [comment]
Perhaps user can inform us that path should be interpreted as a folder by including a trailing slash?

If they've been ambiguous and we find both a file and a folder with same name, I suspect we should error and propose ways for them to be more specific.

**Comment by LucyMcGowan** [comment]
oh I like the idea of a trailing slash! maybe only required if there really are two with the same name? so if a user inputs `foobar/baz` we default to looking for the id of a folder named `foobar` and something named `baz` within it. If there are 2 things, we error, if they mean the folder, they can be explicit by adding the trailing slash, if they mean the file, they can be explicit by searching the exact name using `pattern`? or we default to returning the file if there are 2, and if they want the folder they use the slash.

**Comment by jennybc** [comment]
Agree with almost all of what you propose. Only tweak I'd make:

> or we default to returning the file if there are 2, and if they want the folder they use the slash

I would just error in this case. And who says there are 2? There could be 2 files and 2 folders 🙄 Now what?

In fact, I don't see how the "folder and a file" scenario is any different from the ">1 folder" scenario, in terms of errors. We always error if it's unclear what we should do, i.e. if the path is not uniquely defined. The main change I think we just agreed on is that the initial GET should allow for the last bit (if no trailing slash) to be folder or non-folder file. This also means we need to consult the type of the identified leaf and act accordingly.

**Comment by jennybc** [comment]
The more I think about this, I don't see how `drive_list(path = "foo/bar", pattern = "baz")` makes things unambiguous if there is both a `foo/bar/baz` folder and a `foo/bar/baz` non-folder file.

The trailing slash clearly indicates "folder". But the above doesn't provide a similarly clear statement of "non-folder file".

I think the only way to be precise here is for user to specify mime type.

**Comment by jennybc** [comment]
Current plan:

Allow for fact that `foo/bar/baz` could be path to a folder or a file.

If it uniquely identifies one file, return a `drive_list()`-style tibble with one row, i.e. for that file.

If it uniquely identifies one path, list contents of that path.

If it's not unique, error and provide remedies.

  * User can specify "folder" by using trailing slash, i.e. `foo/bar/baz/`.
  * User can specify a non-folder file via `q` (*I would need to look up that syntax*).

**Comment by jennybc** [comment]
Yeah, I think we might want to elevate `type` to an actual argument (it's mentioned in the very first comment). But let's wait until I get #24 done before we do anything.

**Comment by jennybc** [comment]
This drop down menu in the Drive search bar should be our guide, in terms of what people might expect:

<img width="182" alt="screen shot 2017-05-19 at 3 55 32 pm" src="https://cloud.githubusercontent.com/assets/599454/26269753/aaeeac5c-3cab-11e7-9be1-5a920c218e52.png">

**Comment by LucyMcGowan** [comment]
are you working on this as part of the `drive_list()` update, or should I give it a whirl with the mimeTypes?

**Comment by jennybc** [comment]
I am working on the path resolution, so you should hold off. They sort of interact.

**Comment by jennybc** [comment]
Closed in favour of more specific issues that we can tackle separately.
