### ISSUE TITLE
drive_upload(): when name or id already exists

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#71]
* In order to upload with a new mimeType, it seems you have to both upload & change the metadata simultaneously
* It seems the only way to do so is with a multipart upload 
    * don't know how to do that without writing a temporary file
* This was asked about on [SO](https://stackoverflow.com/questions/31080363/how-to-post-multipart-related-content-with-httr-for-google-drive-api).
* Addressed a bit here: https://github.com/hadley/httr/issues/253

**Comment by jennybc** [comment]
We need to distinguish between these two situations:

  * You want to upload into a file named "foo" and, if there's already a "foo", you are happy to clobber it.
  * You want to replace the contents of the file "foo" AND KEEP THE FILE ID.

Right now we're conflating the two with the way we think about `overwrite`. We need to be clear whether this addresses file name or file id.

If we conclude that this distinction is worth making, `drive_update()` or `drive_replace()` suggest to me that the file id would be preserved, but we are updating metadata and/or media. `drive_upload()` suggests we are making no promises about file id preservation. I imagine `drive_update()` or `drive_replace()` would be a wrapper around `drive_upload()` with `overwrite = TRUE` and a promise to keep the file id.
