### ISSUE TITLE
safer purrr mapping for drive_ids

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#75]
* We probably want to use one of purrr's safer mapping strategies, for when there's one bad path or id among others that work?

**Comment by jennybc** [comment]
The non-existence of a file specified by id throws an error. If specified by path and no file matches, you just don't get anything.

**Comment by jennybc** [comment]
I'm not convinced there's a clear action to take here. Perhaps wider usage will reveal if we need to do anything on this front.
