### ISSUE TITLE
Rename `is_one()`

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#77]
Not sure what the new name should be but `is_one()` implies it will return logical, which is confusing.

**Comment by jennybc** [comment]
Applies to `is_any()` as well.

Maybe `is_one()` and `is_any()` *should* exist, but live up to their names. We still need the functions that act as valves, only allowing the input to flow through if it has the required number of rows.

**Comment by LucyMcGowan** [comment]
ick I agree `is_one()` and `is_any()` really imply logical output. I wonder if we should have all of our `is_*()` functions, and then have some function that will check it & output a sensible error with glue? Is something like this worthwhile:
```
valve <- function(x, f, msg) {
 if (!f(x)) {
    stop(
      glue::glue_data(x, msg),
      call. = FALSE
    )
  }
}
```

**Comment by jennybc** [comment]
Yeah that's what I had in mind with `msg` in #74. This also seems related to mime type helpers. Other than checking length, a common thing is to make sure you have, say, a folder.

**Comment by LucyMcGowan** [comment]
does the above sketch make sense with 3 inputs? trying to think if there is a more efficient way to do it, but that doesn't seem too bad.
