### ISSUE TITLE
extract ids from urls

### ISSUE THREAD

**Issue by LucyMcGowan** [tidyverse/googledrive#85]
* write a small function to extract `fileId`s from the urls
* Notes:
    *  most urls have the form: `https://docs.google.com/*/d/fileId/edit` (where * is document, spreadsheets, forms, or presentation)
    * in all of the links that I have found so the`fileId` is preceded by /d/
    * found this [SO question](https://stackoverflow.com/questions/16840038/easiest-way-to-get-file-id-from-url-on-google-apps-script) that verifies that this is mostly true
    * Craig's advice: stick with /d/ - if the user has links that don't follow this pattern have them open in the browser and copy drive's redirect

**Comment by jennybc** [comment]
This recently merged PR on googlesheets (https://github.com/jennybc/googlesheets/pull/319) shows what URLs look like on Team Drives. All consistent with your notes/plans from above.
