### ISSUE TITLE
Setup and teardown for README and each article

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#92]
We need at least the same low tech solution we are using for the tests: well-preserved code for setup and teardown. I just failed to re-build the pkgdown site because:

```
Updating README.md
Error in drive_upload("chickwts.csv") : Path already exists:
My Drive/chickwts.csvPath already exists:
0AEGh-SuuA2nTUk9PVA/chickwts.csv
```

I deleted it manually, succeeded with site rebuild, and moved on. But we need to make that even easier.

**Comment by LucyMcGowan** [comment]
oh I'm sorry that was my fault, I was playing with it for the new download function 🙈 - I can go ahead and update this. Do you think it'd be preferable to name this something like `drive_upload("chickwts.csv", name = "README-chickwts.csv")` or to stick it in a README folder? `drive_upload("chickwts.csv", name = "chickwts.csv", folder = "README")` both would solve the problem, so it'd really be whichever we think will be more useful/less confusing for a new user glancing over this. The other option would be just to set `overwrite = TRUE`.

**Comment by jennybc** [comment]
No worries!

I think your idea to do this with naming, as we've done with tests, sounds good. I think the use of folders will tie our hands too much with what we might want to demonstrate in README or a vignette. Any code that will succeed or die based on presence/absence of a specific file should use the naming convention and should appear as necessary in hidden setup/teardown chunk(s).
