### ISSUE TITLE
Apply drive_id class to the id variable in a dribble

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#93]
It just occurred to me that the `id` variable in a dribble could have type `drive_id`. We already have this class and we can apply it inside the functions we already have for creating dribbles. This makes it more attractive to write a format method for `drive_id` objects that truncates / ellipsizes the ids. This is basically a revival of #5.

**Comment by LucyMcGowan** [comment]
Working on this this morning - when do you think would be the most natural time to introduce this class for `as_dribble.data.frame()` -- if passed a list, it is natural to assign the `id` a class, but for data frames currently we pass it through a `new_dribble()` function (that doesn't check any columns, just assigns the class) and then `dribble_validate()`. My inclination is `new_dribble()`, but then we'd be semi-validating it before it's been passed to `dribble_validate()` (to at least make sure it has a column `id` and assign it class `drive_id`.

**Comment by jennybc** [comment]
I'm not sure when to apply the class. The `drive_id` formatting isn't going to work in the near future anyway (https://github.com/tidyverse/tibble/issues/212), so let's wait and see what the world looks like once that's cleared up and we're motivated to move forward.
