### ISSUE TITLE
Document the URL extraction feature of as_id()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googledrive#94]
I think this important feature of `as_id()` made it into the code but not the help file. It's probably worth including in README? I'll definitely put in the file identification article once I get to that section.

**Comment by LucyMcGowan** [comment]
I think I added it to the argument but not the description 🙈 - I'll add it & I can add it to the README in the PR to update the file creation & deletion if that sounds good!

**Comment by jennybc** [comment]
Fixed in 8e217ba
