### ISSUE TITLE
What's the purpose of the `folder` argument in `drive_upload` 

### ISSUE THREAD

**Issue by tiernanmartin** [tidyverse/googledrive#96]
I see the description of the `folder` argument in the documentation:
> `folder`  Drive File, something that identifies the folder of interest on your Google Drive. This can be name(s)/path(s), marked file id(s), or a dribble.

I assumed that this allows a user to specify which folder to upload the file to, but that doesn't seem to work when I try the following psuedo-code:

```r
write.csv(chickwts, "chickwts.csv")

folder <- drive_path("~/data/"))  # this is the easiest way I could see to access the `data/` folder in my Drive

drive_chickwts <- drive_upload("chickwts.csv", folder = folder)

```
`drive_upload` succeeds but the file shows up in the root of my Drive directory instead of the specified folder.

**Comment by LucyMcGowan** [comment]
I actually think this is a little :bug: I just found in `drive_mkdir()` today too - I'll check it out tonight.

**Comment by LucyMcGowan** [comment]
Yes, I think this was the same issue I saw earlier today with `drive_mkdir()`, but let me know if that doesn't fix it & we will reopen this.

**Comment by tiernanmartin** [comment]
Looks good 👍

**Comment by LucyMcGowan** [comment]
Adding some tests now to keep this from breaking again, thanks for the issue @tiernanmartin!
