### ISSUE TITLE
Functions returning a `dribble` fail to print inline in R notebook

### ISSUE THREAD

**Issue by tiernanmartin** [tidyverse/googledrive#99]
Running a `googledrive` function within an Rmarkdown code chunk returns the following error:

> ```r
> Error in vapply(x, obj_sum, character(1L)) : values must be length 1,
>  but FUN(X[[1]]) result is length 6
> ```

Here's a screenshot of the `drive_search()` working fine in the console but returning the error in the Rmarkdown doc:
![drive-ss](https://user-images.githubusercontent.com/8197328/27304421-df37dff6-54f2-11e7-97f7-50915678f1ca.PNG)

**Comment by LucyMcGowan** [comment]
I believe this is actually an RStudio bug for all listcolumns ☹️ If you actually render the whole document it shouldn't be a problem, but it happens when you render inline.

**Comment by tiernanmartin** [comment]
Yep that seems to be the case: substituting `tibble::tribble(~my_list_col, list(1, 2)` resulted in the same error. More specifically, it seems that _nested_ list-cols  (i.e., list columns that contain lists) are the problem. 

I couldn't find any open issues to link this to, although it does seem to be related to https://github.com/tidyverse/tibble/issues/97.

**Comment by tiernanmartin** [comment]
Changing the[ chunk output settings ](http://rmarkdown.rstudio.com/r_notebooks.html#chunk_output) from "Chunk Output Inline" to "Chunk Output in Console
 works as a temporary fix:
![](http://rmarkdown.rstudio.com/images/notebook-collapse-all-output.png)

**Comment by LucyMcGowan** [comment]
Yep! That's how @jennybc and I have it set now. I'll try to get the status on that 🐛

**Comment by jennybc** [comment]
I think we should close this (although we can still update each other), because it has nothing to do with googledrive *per se*. I'll leave this for one of you to do, if you're on board.
